README.md, README.md.tmpl
issues-options heading does not exist anymore.
Closes thing is command-line-options.
=> readme: fix invalid link to issues-options

pkg/packages/resolver.go
Before that fix golangci-lint couldn't run analysis
if in any dir there was go file with corrupted `package` or `import`
statement.
After that fix it will only warn about such files and continue analysis.
But it will fail analysis after finding 10 packages with such errors
to not being too noisy in case of internal error.
=> Analyze project even if fatal import dir error

Gopkg.lock, vendor/github.com/OpenPeeDeeP/depguard/depguard.go
I am so sorry guys. My next few things on `depguard` will be to add test because that should not have been an issue.
=> Path Prefix was broken on depguard

README.md, pkg/lint/lintersdb/lintersdb.go
=> Close #196: disable GAS (gosec) by default

README.md, README.tmpl.md
=> Update REAMDE for ale-vim support

README.md, README.tmpl.md
=> docs: write about supported go versions

pkg/commands/linters.go, pkg/commands/run.go, pkg/lint/lintersdb/enabled_set.go
=> fix #355: don't merge megacheck on linters cmd

pkg/golinters/errcheck.go
We were having an issue where we had to have uncommitted changes to our `.golangci.yml` file so that our errcheck exclude file could work properly in different environments. We had to use absolute paths to ensure that the linter could be run from anywhere. However, having different home directories and GOPATHs made this challenging.
This patch adds support for a few things:
1. `~` expansion of home directories
2. If the exclude name from the config is not absolute, then use the same logic as finding the `.golangci.yml` file to work up the path looking for it.
=> Add support for searching for errcheck exclude file

Dockerfile
=> Dockerfile: move binary to /bin/

.gitignore, README.md, README.tmpl.md, pkg/commands/root.go, pkg/commands/run.go, pkg/result/processors/skip_dirs.go
=> dev: improve memory tracking

.pre-commit-hooks.yaml
=> Enable auto-fixing when running via pre-commit

install.sh
Closes #472.
See https://github.com/client9/shlib/issues/13 and https://github.com/goreleaser/godownloader/issues/98 for background and other links.
=> Make install script work on Windows.

.goreleaser.yml
=> Provide pre-built binary for ARM arch

go.mod, go.sum, vendor/modules.txt
Minor dep update to latest mvdan.cc/unparam.
=> Update to latest mvdan.cc/unparam.

go.mod, go.sum, vendor/github.com/spf13/pflag/.travis.yml, vendor/github.com/spf13/pflag/README.md, vendor/github.com/spf13/pflag/bool_slice.go, vendor/github.com/spf13/pflag/count.go, vendor/github.com/spf13/pflag/duration_slice.go, vendor/github.com/spf13/pflag/flag.go, vendor/github.com/spf13/pflag/float32_slice.go, vendor/github.com/spf13/pflag/float64_slice.go, vendor/github.com/spf13/pflag/go.mod, vendor/github.com/spf13/pflag/int32_slice.go, vendor/github.com/spf13/pflag/int64_slice.go, vendor/github.com/spf13/pflag/int_slice.go, vendor/github.com/spf13/pflag/ip_slice.go, vendor/github.com/spf13/pflag/string_array.go, vendor/github.com/spf13/pflag/string_slice.go, vendor/github.com/spf13/pflag/string_to_int64.go, vendor/github.com/spf13/pflag/uint_slice.go, vendor/modules.txt
Updates to latest https://github.com/spf13/pflag v1.0.5 to fix issues with upstream go.mod.
see:
#711 
https://github.com/spf13/pflag/issues/218
=> Update to spf13/pflag v1.0.5.

go.mod, go.sum, vendor/github.com/timakin/bodyclose/passes/bodyclose/bodyclose.go, vendor/modules.txt
Until timakin/bodyclose#20 merged use forked version.
=> Fix #608: use forked bodyclose

go.mod, go.sum, vendor/modules.txt
Updates to latest upstream [timakin/bodyclose](https://github.com/timakin/bodyclose) commit containing fix for #733.
=> Update to latest timakin/bodyclose

README.md, README.tmpl.md
Thank you for the great project golangci-lint which has been widely used in our company [caicloud](https://github.com/caicloud).
[caicloud/cyclone](https://github.com/caicloud/cyclone) is one of these projects, thank you for considering it to your list of projects using golangci-lint.
=> add cyclone to the list of great projects

README.md
Regenerate the README to include #776 changes.
=> Regenerate README

internal/cache/cache.go, internal/cache/cache_test.go, internal/cache/default.go
Scopes cache directory permissions to uid/gid running the linter.
=> Reduce cache directory permissions

.goreleaser.yml
Fixes goreleaser docker builds.
see: https://travis-ci.com/golangci/golangci-lint/jobs/243258551
=> Fix docker builds

pkg/golinters/goanalysis/linter.go
=> Save issues into cache in parallel

README.md, README.tmpl.md
Signed-off-by: wxdao <waxiadao@gmail.com>
=> Fix typo in README

README.md, README.tmpl.md
=> Add mattermost to Trusted By

README.md, README.tmpl.md
Misc. README updates:
* Add license, release, and docker badges.
* Fix install instructions/table of contents.
* Fix misc. typos.
=> Misc. README Updates

go.mod, go.sum, vendor/github.com/uudashr/gocognit/gocognit.go, vendor/modules.txt
=> Update the gocognit linter due to bug fix

README.md, README.tmpl.md
`README.md` is generated by changing `README.tmpl.md` and running `make README.md`.
=> Update Trusted By section in README

pkg/commands/completion.go
Adds zsh completion support. Fixes #862.
=> Add zsh completion

.travis.yml
=> dev: use go1.14

build/Dockerfile, build/Dockerfile.alpine
=> Build docker images using Go 1.14

README.md, README.tmpl.md
=> Update bench_test url

pkg/golinters/goanalysis/runner.go
Print actual error along with dep name.
Ref: #827
=> goanalysis: make `failed prerequisites` error detailed

go.mod, go.sum, pkg/golinters/asciicheck.go, pkg/lint/lintersdb/manager.go, test/testdata/asciicheck.go
Adds https://github.com/tdakkota/asciicheck linter support
=> Add asciicheck linter support

pkg/golinters/unused.go, pkg/result/processors/fixer.go, test/testdata/fix/in/unused.go, test/testdata/fix/out/unused.go
=> Fix unused in "fix" mode

go.mod, go.sum
Fix checking `#gosec` in comments
=> Update godot linter

tools/package-lock.json
Fix js security issues by:
cd tools && npm install && npm audit fix
=> dev: update js deps

.golangci.example.yml, README.md
=> docs: add exclude-case-sensitive to .golangci.example.yml

.travis.yml
Also, update node.js version for CI
=> dev: don't run CI on go.12

.github/workflows/pr.yml
* Update actions/setup-go
* Remove go1.12
=> dev: add mod cache in gh actions

pkg/printers/codeclimate.go
Some issues don't have any source lines
=> Fix nil pointer in codeclimate.go

pkg/golinters/godot.go
Fix https://github.com/golangci/golangci-lint/issues/1082
=> godot: fix issue with `--fix` flag

Makefile, docs/package.json
=> dev: expand website templates during build

.gitignore, go.mod, go.sum, pkg/golinters/godot.go, pkg/lint/lintersdb/manager.go, test/testdata/fix/in/godot.go, test/testdata/fix/out/godot.go
Now a period can be added automatically.
=> Add autofix for godot linter

docs/src/docs/usage/install/index.mdx
=> docs: recommend binary installation for windows and linux

docs/src/docs/usage/faq.mdx
=> Fixed docs link: points at contributing section

assets/github-action-config.json, docs/template_data.state
Signed-off-by: denis-tingajkin <denis.tingajkin@xored.com>
Update github-action.json and README.md by running below make target.
```
make assets/github-action-config.json
make update_contributors_list
```
=> To enable v1.28.1 in github action

pkg/lint/lintersdb/manager.go
=> Gci: support auto fix

go.mod, go.sum
=> Gci: fix panic

.github/workflows/pr-extra.yml
This is suggested by nancy team to avoid coming breaking change
Relates: #1320
=> Tag nancy version to v0.3

go.sum
=> cleanup go.sum

go.mod, go.sum
Pull in commit https://github.com/nishanths/exhaustive/commit/6cf413ae40e03e979d4c7371f75bcaa37c736618
This should be ready to review.
=> update exhaustive linter

.github/workflows/pr-extra.yml
This commit is to update version to 1.0.1
Closes #1320
=> ci(nancy): Bump nancy version to 1.0.1

scripts/expand_website_templates/main.go
closes #1348 
I think sorted linters are good for navigation
=> docs: Added func to sort linters

README.md, docs/template_data.state
This commit is to prepare for Oct 2020 release. No code changes were
done, only run some predefined target:
- make update_contributors_list
- make update_netlify_state
Relates #1456
=> build(release): Prepare for release 1.32.0

go.mod, go.sum
https://github.com/mvdan/gofumpt/compare/ab5a8192947d...5c11c50e94755be9865286cab4a4432843fcaa64
Fixes #1547
=> Update gofumpt to HEAD.

go.mod, go.sum, pkg/lint/runner.go
Related to:
- https://github.com/golangci/golangci-lint/issues/1537#issuecomment-739614904
- https://github.com/golangci/golangci-lint/issues/1537#issuecomment-739617883
=> fix: throw an error on panic.

.golangci.example.yml
Add gocritic settings in the example file.
=> Add settings examples for gocritic

pkg/golinters/forbidigo.go
Fix cut-and-paste error.
Fixes #1589
=> Fix forbidigo linter name in reports

go.mod, go.sum
=> bump github.com/daixiang0/gci from 0.2.7 to 0.2.8

.golangci.example.yml
Note: The test `TestSourcesFromTestdataWithIssuesDir/go-header_bad.go` is failing on `master` and was before I made any changes.
=> Add issues.fix config to example configuration

go.mod, go.sum, pkg/golinters/gomnd.go
https://github.com/tommy-muehle/go-mnd/compare/16041ac3fe65...v2.3.1
Fixes #1653
Related to https://github.com/tommy-muehle/go-mnd/pull/21
=> fix: bump github.com/tommy-muehle/go-mnd/v2 to v2.3.1

go.mod, go.sum
=> fix: new-from-rev for large repository.

go.mod, go.sum, pkg/golinters/durationcheck.go, pkg/lint/lintersdb/manager.go, test/testdata/durationcheck.go
https://github.com/charithe/durationcheck
Closes #461
=> Add 'durationcheck' linter

README.md, assets/github-action-config.json, docs/template_data.state
=> docs: Update for v1.37.1

.golangci.example.yml, go.mod, go.sum, pkg/config/config.go, pkg/golinters/wsl.go, test/testdata/wsl.go
=> Bump wsl to v3.2.0

go.mod, go.sum
https://github.com/charithe/durationcheck/compare/v0.0.4...v0.0.6
=> bump durationcheck from 0.0.4 to 0.0.6

go.mod, go.sum
https://github.com/timakin/bodyclose/compare/f7f2e9bca95e9160b6ee3160a1ef03a366765b56...cb6215831a94c8f045805eae1d9782ebf907ced9
=> Bump github.com/timakin/bodyclose to HEAD

go.mod, go.sum, test/bench/bench_test.go
https://github.com/shirou/gopsutil/compare/v2.19.8...v3.21.1
=> test: Bump github.com/shirou/gopsutil to v3.21.1

docs/src/docs/usage/configuration.mdx
A little PR to document the command-line arguments for profiling.
=> add doc for the profiling arguments

pkg/golinters/revive.go, test/testdata/revive.go
=> revive: add rule name in message.

pkg/golinters/gocritic.go
=> docs: improve gocritic description

.github/ISSUE_TEMPLATE/bug_report.md
This PR improves the bug issue template:
- ask for a description of the problem
- ask for a code example
=> docs: improve the bug issue template.

go.mod, go.sum
https://github.com/mvdan/gofumpt/compare/v0.1.0...v0.1.1
fixes #1818
=> bump gofumpt from v0.1.0 to v0.1.1

pkg/golinters/errorlint.go, pkg/lint/lintersdb/manager.go, scripts/expand_website_templates/main.go
Improve the linters page:
<details>
<summary>Render</summary>
</details>
https://golangci-lint.run/usage/linters/
=> docs: improve linters page

go.mod, go.sum
Fixes #1005
https://github.com/jingyugao/rowserrcheck/compare/c6a0c12dd98d...d907ca737bb1
=> Bump rowserrcheck to HEAD

go.mod, go.sum
https://github.com/tomarrell/wrapcheck/compare/1683564d9756...v1.0.0
=> Bump wrapcheck to v1.0.0

go.mod, go.sum
https://github.com/ashanbrown/makezero/compare/7b7cdbb3025a...4155955488a0
=> Bump makezero to HEAD

go.mod, go.sum
https://github.com/julz/importas/compare/60b4fa260dd0...d0bf5cb4e1db
=> Bump importas to HEAD

docs/src/docs/usage/configuration.mdx
=> docs: add cache directory information.

.github/contributors/package-lock.json, .github/contributors/rewrite_readme.ts, .nancy-ignore, CHANGELOG.md, README.md, assets/github-action-config.json, docs/template_data.state
=> docs: update for v1.39.0

go.mod, go.sum
Fixes #1973
https://github.com/golang/tools/compare/7a6108e9b210...8287d5da45e4
=> govet: fix sigchanyzer.

CHANGELOG.md, README.md, assets/github-action-config.json, docs/template_data.state
=> docs: update for v1.40.1

go.mod, go.sum
https://github.com/ashanbrown/makezero/compare/4155955488a0...b6261585ddde
Related to https://github.com/golangci/golangci-lint/issues/431#issuecomment-826168245
=> Update makezero to HEAD

go.mod, go.sum
Fix for https://github.com/tetafro/godot/issues/19
=> Update godot to 1.4.7

docs/src/docs/index.mdx
=> doc: add all integrations to docs introduction page

pkg/commands/run.go, pkg/config/output.go, pkg/printers/html.go
=> output: generate HTML report

pkg/golinters/goimports.go
=> Improve goimports description

.golangci.example.yml, go.mod, go.sum, pkg/config/linters_settings.go, pkg/golinters/wrapcheck.go
Update `ignoreSigs` default, add `ignorePackageGlobs`
https://github.com/tomarrell/wrapcheck/compare/v2.2.0...v2.3.0
=> Update Wrapcheck to v2.3

go.sum
https://github.com/golangci/golangci-lint/runs/3726492283?check_suite_focus=true
=> fix: go.sum

pkg/commands/run.go
https://github.com/golangci/golangci-lint/issues/2337#issuecomment-957223053
Linked to #2039
=> cli: don't hide enable-all option

go.mod, go.sum
https://github.com/mvdan/unparam/compare/aac4ce9116a7...d0ef000c54e5
=> unparam: bump to HEAD

go.mod, go.sum
This reverts commit 181c61f8c561451658744f878817f83dd7785e85.
Revert of #2534
Related to #2525
=> Revert "build(deps): bump github.com/sylvia7788/contextcheck from 1.0.4 to 1.0.5"

.goreleaser.yml
=> fix: completion for fish-shell

go.mod, go.sum
https://github.com/blizzy78/varnamelen/compare/v0.6.0...v0.6.1
=> bump varnamelen from v0.6.0 to v0.6.1

build/Dockerfile, build/Dockerfile.alpine
https://github.com/golangci/golangci-lint/issues/2649#issuecomment-1073274033
=> fix: update base images to go1.18

docs/src/docs/index.mdx
=> docs: fix GitHub Releases Stats badge link.

go.mod, go.sum
https://github.com/golangci/go-misc/compare/927a3d87b613...d24fe342adfe
Fixes #2650
=> bump deadcode to HEAD

pkg/golinters/unused.go
=> unused: fix false-positive

.nancy-ignore
<details>
```
pkg:golang/github.com/hashicorp/consul/api@v1.12.0
2 known vulnerabilities affecting installed version 
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ [CVE-2022-29153] CWE-918: Server-Side Request Forgery (SSRF)                                                                                                                                                                 ┃
┣━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫
┃ …
```
=> fix: codeQL scanning

.golangci.reference.yml, go.mod, go.sum, test/testdata/fix/out/gci.go, test/testdata/gci.go
Upgrade the version and make the document clear to avoid making users think they can config the order of sections.
https://github.com/daixiang0/gci/compare/v0.4.0...v0.4.1
=> build(deps): bump github.com/daixiang0/gci from 0.4.0 to 0.4.1

.github/contributors/generate.ts
=> dev: remove kortschak from generated team

go.mod, go.sum
https://github.com/sivchari/tenv/compare/v1.6.0...v1.7.0
Fixes #2986
=>  build(deps): bump github.com/sivchari/tenv from 1.6.0 to 1.7.0

pkg/golinters/gci.go
=> gci: fix panic with invalid configuration option

.golangci.reference.yml, go.mod, go.sum
https://github.com/daixiang0/gci/compare/v0.5.0...v0.6.0
=> build(deps): bump github.com/daixiang0/gci from 0.5.0 to 0.6.0

pkg/config/linters_settings.go, pkg/golinters/gci.go
add missing `custom-order` setting
=> gci: add missing `custom-order` setting

pkg/lint/lintersdb/manager.go
=> contextcheck: disable linter

pkg/config/linters_settings.go, pkg/golinters/interfacebloat.go
=> interfacebloat: fix configuration loading

pkg/golinters/depguard.go, pkg/result/processors/fixer.go, test/testdata/depguard_ignore_file_rules.go
Windows has a very bad file system, so we have to retry some operations...
=> dev: improve tests on Windows

docs/src/docs/usage/configuration.mdx
I adjusted the phrasing to make the use case of the cli command more understandable.
=> doc: improved wording

pkg/golinters/nolintlint/README.md
=> docs: fix typo in nolint

go.mod, go.sum
https://github.com/leonklingele/grouper/compare/v1.1.0...v1.1.1
=> build(deps): bump github.com/leonklingele/grouper from 1.1.0 to 1.1.1

.goreleaser.yml, install.sh
=> Build NetBSD binaries

.goreleaser.yml
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
> https://goreleaser.com/customization/source/
PTAL @jirfag
=> dev: add new source archive

docs/src/docs/usage/install/index.mdx
- rename and move a section
- add a note about the Go version used by brew.
=> doc: improve installation section

pkg/config/linters_settings.go, pkg/lint/lintersdb/manager.go
Closes #3555
without extra changes opposite #3703
Closes #3703
=> docs: remove unused from config.LintersSettings

pkg/golinters/importas.go
=> importas: fix typo in logs

docs/src/docs/index.mdx
This PR improves `Features` documentation section in `index.mdx`.
Changes:
- `Yaml` -> `YAML`;
- `integrations`, `nice` -> `Integrations`, `nice`;
- add whitespace.
=> docs: improve features section

.golangci.yml, internal/errorutil/errors.go, internal/pkgcache/pkgcache.go
=> dev: add gofmt rewrite rule to ensure 'any' is always used

go.mod, go.sum
https://github.com/timakin/bodyclose/compare/e39cf3fc478e...574207250966
=> bodyclose: bump to HEAD

.github/ISSUE_TEMPLATE/bug_report.yml
Clarify the code example section.
=> dev: improve issue form

.goreleaser.yml
Include section, group, soft dependency on (packaged) Go, and LICENSE and README.md in docs.
=> dev: packaging improvements

pkg/logutils/logutils.go
This PR fixes a typo in the comment.
=> docs: fix a typo

pkg/printers/github.go
=> docs: update link

docs/src/docs/contributing/website.mdx
The PR expands the installation instructions for running the website locally by adding info about Node.js and ` --legacy-peer-deps`.
=> docs: expand install manual for running website locally

go.mod, go.sum, pkg/commands/run.go
=> feat: automatically adjust the maximum concurrency to the container CPU quota

docs/src/config/sidebar.yml, docs/src/docs/plugins/module-plugins.mdx, scripts/website/expand_templates/linters.go, scripts/website/expand_templates/main.go, scripts/website/expand_templates/plugins.go
- fix sidebar items
- add reference file to the doc
- add JSON Schema link for `.custom-gcl.yml`.
=> docs: improve plugins page

docs/src/docs/plugins/module-plugins.mdx
The settings of the repo are not the repo :smile:
=> docs: fix plugin example URL

README.md
=> docs: fix installation link in the readme

pkg/printers/printer.go
=> feat: create output directory

SECURITY.md
This PR improves `SECURITY.md`.
=> chore: improve grammar in the security policy

docs/src/docs/contributing/workflow.mdx
=> docs: fix broken link

pkg/golinters/mnd/mnd.go
=> fix: gomnd deprecated configuration compatibility

pkg/lint/lintersdb/builder_linter.go
I assigned intrange to the style preset because it looked ok there, but I don't have any strong opinion about it.
Fixes #4795
=> intrange: add style preset

.github/workflows/post-release.yml, .github/workflows/pr.yml, install.sh
Fixes #4813
It's not a "perfect" script but at least it works.
=> dev: fix installation script for curl v8.8.0

docs/src/docs/welcome/install.mdx
[![Packaging status](https://repology.org/badge/vertical-allrepos/golangci-lint.svg)](https://repology.org/project/golangci-lint/versions)
=> docs: add repology package summary

.golangci.next.reference.yml, .golangci.reference.yml
- add defaults
- add links to options
=> docs: update wsl documentation

test/bench/bench_test.go
This file is not used but I think it's better if it's working :wink: 
I have had those changes locally for years, so it's time to add them.
I'm working on a [better benchmark system](https://github.com/ldez/golangci-lint-bench), I think we may remove this in the future.
=> dev: rewrite benchmarks

pkg/lint/runner.go
=> dev: add comment to clarify using empty issues slice

go.mod, go.sum
https://github.com/golangci/gofmt/compare/f50ced29576e...d8596aa466a9
=> chore: update gofmt

.golangci.next.reference.yml, .golangci.reference.yml
=> docs: fix URL for revive.ignore-generated-header

.github/workflows/tag.yml
=> dev: add missing AUR_KEY secret

.github/workflows/tag.yml
Adds missing snapcraft tooling inside the release workflow.
=> dev: fix release workflow

.golangci.reference.yml, jsonschema/golangci.jsonschema.json
PR #5155 was merged during the v1.60.1/v1.60.2 releases, I was focused on the release and I missed those unwanted changes.
=> docs: revert unwanted JSONSchema/doc changes

.goreleaser.yml
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=golangci-lint
=> dev: fix aur sources

build/buildx-alpine.Dockerfile, build/buildx.Dockerfile
=> dev: update Docker base images

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml
Related to https://github.com/golangci/golangci-lint/pull/5424#discussion_r1958775451
=> dev: add editor/IDE inside issue template

pkg/lint/lintersdb/builder_linter.go
=> dev: improve deprecation warning for tenv linter

docs/gatsby-config.js, docs/package-lock.json, docs/package.json
I'm not 100% sure, but based on what I found, removal of `gatsby-plugin-offline` package should fix the cache problem.
Fixes #4947
=> docs: fix cache problem

pkg/commands/migrate.go
Related to https://github.com/golangci/golangci-lint/pull/5506#discussion_r1984079897
=> dev: log a link to the migration guide

go.mod, go.sum
https://github.com/timakin/bodyclose/compare/ed6a65f985e3...1db5c5ca4d67
=> build(deps): bump github.com/timakin/bodyclose from ed6a65f985e3 to 1db5c5ca4d67

docs/src/docs/product/migration-guide.mdx
Adds a migration guide for VSCode integration
=> docs: add a migration guide for VSCode integration

.golangci.next.reference.yml
v1 `linters-settings` changed to v2 `linters.settings`.
=> docs: update reference comment for errchkjson

pkg/result/processors/base_rule.go
=> fix: use absolute filepath inside base rule source

docs/src/docs/welcome/integrations.mdx
https://github.com/golang/vscode-go/issues/3732#issuecomment-2772569680
=> docs: add link to issues related to some integrations

.pre-commit-hooks.yaml
Adds hook for `golangci-lint fmt`
=> feat: add golangci-lint-fmt pre-commit hook

go.mod, go.sum, pkg/golinters/unconvert/unconvert.go
**This update is done by hand because dependabot is not allowed to update dependencies from golangci org.**
=> build(deps): bump github.com/golangci/unconvert to HEAD

.golangci.next.reference.yml, pkg/golinters/govet/govet.go
https://pkg.go.dev/golang.org/x/tools/go/analysis/passes/httpmux
=> govet: add `httpmux` analyzer

pkg/commands/internal/migrate/cloner/cloner.go, pkg/commands/internal/migrate/testdata/yaml/linters-settings_nakedret_zero.golden.yml, pkg/commands/internal/migrate/testdata/yaml/linters-settings_nakedret_zero.yml, pkg/commands/internal/migrate/versionone/linters_settings.go, pkg/commands/internal/migrate/versiontwo/formatters.go, pkg/commands/internal/migrate/versiontwo/linters_settings.go, pkg/commands/internal/migrate/versiontwo/output.go
=> fix: convert uint as pointer of uint for the migration

.goreleaser.yml
https://aur.archlinux.org/packages/golangci-lint-bin
Related to https://github.com/golangci/golangci-lint/pull/5799#issuecomment-2881007251
=> dev: restore aur-bin

pkg/goanalysis/pkgerrors/parse.go
=> dev: improve comments

pkg/goanalysis/runner_checker.go
=> fix: typecheck memory leak

docs/layouts/_shortcodes/starcharts.html
Adds missing `target` attributes.
=> dev: open starcharts in a new tab

docs/layouts/_shortcodes/item-settings.html
Same problem as #5990, but with badges inside linter/formatter setting pages
=> dev: fix item setting badges
