- README.md
```toml
required = [
"github.com/golangci/golangci-lint/cmd/golangci-lint",
]
```
[The section on vendoring `golangci-lint`](https://github.com/golangci/golangci-lint/tree/61463e305fc23e1246e17b54db2b8daec3220ad4#faq) fails to mention that it needs to be added to the `required` section in `Gopkg.toml`. Without `required`, the vendored `golangci-lint` would be deleted on the next `dep ensure -update`. Also, some of the wording was a bit hard to understand.
> Improve FAQ instructions for vendoring golangci-lint

- pkg/golinters/deadcode.go
- pkg/golinters/dupl.go
- pkg/golinters/errcheck.go
- pkg/golinters/gas.go
- pkg/golinters/goconst.go
- pkg/golinters/gocyclo.go
- pkg/golinters/golint.go
- pkg/golinters/govet.go
- pkg/golinters/ineffassign.go
- pkg/golinters/interfacer.go
- pkg/golinters/maligned.go
- pkg/golinters/megacheck.go
- pkg/golinters/structcheck.go
- pkg/golinters/unconvert.go
- pkg/golinters/varcheck.go
I know this does not save that many memory allocations compared to other areas but every little bit helps in my opinion. 
Also, think I fixed a bug that was not reported in GoCyclo on line 25. It was iterating through the files but only kept the latest stats instead of appending.
> Allocate memory for known size slices

- pkg/lint/lintersdb/lintersdb.go
- test/run_test.go
This is useful to first enable all linters (including fast ones), then
only enable fast linters, then add extra linters. eg.
```
golangci-lint run --no-config --enable-all --fast --print-issued-lines=false \
--exclude-use-default=false --tests --enable typecheck .
```
> Allow --enable, --enable-all and --fast to coexist.

- pkg/commands/run.go
- pkg/golinters/gofmt.go
- pkg/lint/load.go
- pkg/logutils/logutils.go
Don't typecheck func bodies for non-local packages.
Works only if megacheck and interfacer are disabled: they require all
func bodies to build SSA repr.
Export GL_DEBUG=load to get logs for this feature.
> Speedup program loading on 20%.

- README.md
- pkg/commands/run.go
- pkg/config/config.go
- pkg/printers/checkstyle.go
- pkg/result/issue.go
Adds checkstyle output format #93
> Checkstyle support

- README.md
This just removes the extra back in the `go install` step. Helps people (like me) that just copy paste blindly into a Makefile or into the cmdline!
> Remove extra backtick in install step

- README.md
- pkg/commands/root.go
- pkg/commands/run.go
- pkg/config/config.go
- pkg/printers/tab.go
- pkg/printers/text.go
- test/run_test.go
There is now an extra switch '-s' to disable the congrats message when
there are no issues detected
Fixes: #110
> disable the congrats message

- Gopkg.lock
- vendor/github.com/golangci/govet/types.go
Do it in compatible with old go versions object files way:
use golang.org/x/tools/go/gcexportdata instead of importer.Default
> Fix #94: load object files for govet for old go

- .golangci.example.yml
- README.md
Hi,
There is a mistake in the `README` and `.golangci.example.yml`.
Default value is actually `true`
Proof: https://github.com/golangci/golangci-lint/blob/master/pkg/commands/run.go#L141
```go
fs.BoolVar(&ic.UseDefaultExcludes, "exclude-use-default", true, getDefaultExcludeHelp())
```
> Fixed example for 'exclude-use-default'

- README.md
- README.tmpl.md
- pkg/commands/run.go
Although the FAQ does eventually mention that
--new-from-rev=origin/master is the right way, --help does not and
using --new in CI is a terrible pitfall.
Make --help point users to -new-from-rev=HEAD~ for CI setups.
Also use HEAD~ instead of origin/master, since HEAD~ is more
universally applicable, e.g. if golangci-lint is ran against a release
branch.
> point users to --new-from-rev=HEAD~ for CI setups in --help

- README.md
- README.tmpl.md
> Fix nolint comment in readme

- go.mod
- go.sum
Needed to update `errcheck` module because I was getting:
```
% go build ./cmd/golangci-lint
go: downloading github.com/fatih/color v1.6.0
go: downloading github.com/pkg/errors v0.8.0
go: downloading github.com/mattn/go-colorable v0.0.9
go: downloading github.com/spf13/viper v1.0.2
go: downloading github.com/sirupsen/logrus v1.0.5
go: downloading github.com/spf13/cobra v0.0.2
go: downloading github.com/OpenPeeDeeP/depguard v0.0.0-20180806142446-a69c782687b2
go: downloading github.com/golangci/govet v0.0.0-20180818181408-44ddbe260190
go: downloading github.com/golangci/errcheck v0.0.0-20180902071612-f726ab79eeeb
go: downloading github.com/golangci/unconvert v0.0.0-20180507085042-28b1c447d1f4
go: downloading github.com/golangci/gocyclo v0.0.0-20180528134321-2becd97e67ee
go: downloading …
```
> Fix compilation with go1.11

- Dockerfile
This replaces `Dockerfile`'s `ENTRYPOINT` to `CMD` which is more convenient for debugging and playing around with the linter, when `ENTRYPOINT` is more for scripts that set the env and do `exec $@`.
It also fixes #190
> Use CMD in Dockerfile

- README.md
- pkg/config/config.go
Updates the strings to reflect the linter rename.
> config: gas => gosec defaults.

- README.md
- README.tmpl.md
- go.sum
Building from source gave some problems with for example `--version` see #229 . This pull request updates the documentation so that building from source includes the needed ldfags.
> Improve readme with extended installation instruction when building from source.

- pkg/lint/load.go
Motivation: Make it clear that the message is indicating packages
*which do not compile*, rather than packages which *won't be
compiled*.
> Tweak log entry for "not compiling" packages.

- pkg/lint/load.go
> Fix #261: build-tags fix for package loader

- pkg/goutil/env.go
- pkg/packages/skip.go
- pkg/packages/skip_test.go
Fix skip-dirs regexps and 'go env' on Windows.
> fix #264: fix Windows compatibility

- README.md
- README.tmpl.md
From `git help describe`:
> The command finds the most recent tag that is reachable from a commit. If the tag points to the commit, then only the tag is shown. Otherwise, it suffixes
the tag name with the number of additional commits on top of the tagged object and the abbreviated object name of the most recent commit.
Example:
```bash
$ git checkout v1.11.3
HEAD is now at ccac35a Fix false positives with unused identifiers
$ git describe --tags
v1.11.3
$ git checkout HEAD^
Previous HEAD position was ccac35a Fix false positives with unused identifiers
HEAD is now at 3345c71 fix #264: fix Windows compatibility
$ git describe --tags
v1.11.2-6-g3345c71
$ 
```
> Use `git describe --tags` to get most recent tag reachable from HEAD

- pkg/golinters/megacheck.go
- pkg/golinters/typecheck.go
- pkg/lint/load.go
- pkg/packages/util.go
- pkg/result/processors/cgo.go
- pkg/result/processors/skip_dirs.go
1. Fix crash if deps of analyzed packages weren't compiled.
2. Print deps typechecking errors
3. Fix all issues filtering because of empty go env GOCACHE for go < 1.10
> On of cases for #260: fix crash in staticcheck

- .golangci.yml
- README.md
- pkg/golinters/gochecknoglobals.go
- pkg/golinters/gochecknoinits.go
- pkg/lint/lintersdb/manager.go
- test/testdata/gochecknoglobals.go
- test/testdata/gochecknoinits.go
- third_party/gochecknoglobals/LICENSE
- third_party/gochecknoinits/LICENSE
> fix #199: support gochecknoinits, gochecknoglobals

- go.mod
- go.sum
- pkg/config/reader.go
- vendor/github.com/mitchellh/go-homedir/LICENSE
- vendor/github.com/mitchellh/go-homedir/README.md
- vendor/github.com/mitchellh/go-homedir/go.mod
- vendor/github.com/mitchellh/go-homedir/homedir.go
- vendor/modules.txt
This change introduces the ability to use the tilde (`~`) character in your
`-c/--config` flag value to expand your home directory. If invoking this via the
command line with `--config ~/.golangci-lint.yaml`, the user's shell expands the
`~` to the home directory. However, if something is invoking the program for
you (like an editor) it may not do the expansion.
Fixes #289
Signed-off-by: Tim Heckman <t@heckman.io>
> Add support for home directory expansion for -c/--config flag

- pkg/golinters/megacheck.go
even if the main package does not compile, analyze a program by megacheck
> don't stop megacheck on main packages

- README.md
- README.tmpl.md
Fix typo in gometalinter comparison example.
> Fix typo in gometalinter comparison example

- README.md
- README.tmpl.md
People these days tend to use default GOPATH, so environment variable will be empty.
go env GOPATH will work for all cases
> Use go env GOPATH for installation

- README.md
- README.tmpl.md
Thank you for considering segmentio/terraform-docs for your list of projects using golangci-lint. `make readme` also added the `--version` option into `README.md` (seems like the README was outdated in this regard). Let me know if this is an issue and I'll resubmit. Thanks!
---
> Add 'segmentio/terraform-docs' to list of great projects.

- .golangci.example.yml
- README.md
- pkg/commands/run.go
- pkg/config/config.go
- pkg/printers/codeclimate.go
Just the minimum of the format, to support GitLab CI Code Quality - https://docs.gitlab.com/ee/user/project/merge_requests/code_quality.html
You can then add it as a job to `.gitlab-ci.yml`
```yaml
lint:
script:
- golangci-lint run --out-format code-climate --issues-exit-code 0 > code-quality-report.json
artifacts:
reports:
codequality: code-quality-report.json
```
And the new/resolved issues will be displayed in merge requests
> Add code-climate output format

- README.md
- README.tmpl.md
- cmd/golangci-lint/mod_version.go
With upcoming `go1.12` we can now embed some version information without `LDFLAGS`. This PR uses [`debug.ReadBuildInfo()`](https://godoc.org/github.com/golang/go/src/runtime/debug#ReadBuildInfo) to simplify versioning with `go get`.
Here is a working example
```
GO111MODULE=on go1.12rc1 get github.com/vearutop/go-versioning-example@v0.0.1
```
```
go-versioning-example
Build info: &{Path:github.com/vearutop/go-versioning-example Main:{Path:github.com/vearutop/go-versioning-example Version:v0.0.1 Sum:h1:RtKk8SiukO2jrjtkz+0mYQ6bQjUcom3UUqTdBpGAk5o= Replace:<nil>} Deps:[0xc0000a02c0 0xc0000a0300]}
2019-02-12T11:11:20.447+0100	INFO	go-versioning-example@v0.0.1/main.go:9	App Version: v0.0.1
```
> Add version information to built artifact when go get with go1.12

- pkg/lint/astcache/astcache.go
After upgrading to v1.15.0 I started seeing some strange AST cache resolution errors.
```
Can't run linter golint: no AST for file /path/to/foo.go in cache: {...}
Can't process result by autogenerated_exclude processor: can't filter issue result.Issue{...}: can't parse file /path/to/foo.go: <nil>"
Can't process result by nolint processor: can't filter issue result.Issue{...}: can't parse file /path/to/foo.go: <nil>, astcache is [...]
```
I've narrowed it down to commit 96af9582052f62722593d4085f2357df508a6310 which changed the symlink resolution behavior. This change fixes a key consistency issue by ensuring all loads/stores accessing the AST cache use the normalized file path.
> Fix AST cache key consistency

- README.md
- pkg/commands/executor.go
- pkg/commands/root.go
- pkg/config/config.go
fatih/color disables color output automatically if the output is not a tty, and expects applications to override this if required. In Jenkins the output is not a tty, but it does understand color codes.
> Add --color flag to force colored output on/off

- README.md
- README.tmpl.md
- pkg/logutils/stderr_log.go
It provides support to user define a custom log level to avoid warnings or debug options.
The usage will be something like this:
```bash
LOG_LEVEL=error golangci-lint run
```
Close #432
> Include log level option

- Dockerfile
Hi! I always use golangci-lint with the docker image.
I edited Dockerfile to update go version to 1.12
I would be glad if you reviewed and merged this request.
Thanks!
> Update go version to 1.12 in Dockerfile

- Makefile
kata-containers's ci will re-build and re-install golangci-lint every
time it did the staic check.
So run test of golangci-lint with build will make it slow.
Add target build to make golangci-lint just build but not test.
Fixes: #458
Signed-off-by: Hui Zhu <teawater@hyper.sh>
> Makefile: Add target build

- pkg/lint/load.go
LoadAllSyntax in the latest version is equal to the LoadSyntax (https://github.com/golang/tools/blob/master/go/packages/packages.go#L104) and thus can not be used in a switch with LoadSyntax because it duplicates a value.
https://github.com/golangci/golangci-lint/issues/479
> [#479] make use of LoadAllSyntax compatible with the latest x/tools version

- .golangci.example.yml
- README.md
`.golangci.example.yml` has wrong name for `max-issues-per-linter` variable. 
So I've fixed it
> Fix max-issues-per-linter variable name in example

- pkg/exitcodes/exitcodes.go
- pkg/golinters/megacheck.go
- pkg/lint/load.go
- test/run_test.go
The bug was introduced in golangci-lint when migrating staticcheck to go/packages.
Also, thanks to pkg.IllTyped we can analyze as max as we can by
staticcheck.
Relates: #418, #369, #429, #489
> Fix staticcheck panic on packages that do not compile

- README.md
- go.mod
- go.sum
- pkg/golinters/bodyclose.go
- pkg/lint/lintersdb/manager.go
- test/testdata/bodyclose.go
- vendor/github.com/gostaticanalysis/analysisutil/LICENSE
- vendor/github.com/gostaticanalysis/analysisutil/README.md
- vendor/github.com/gostaticanalysis/analysisutil/file.go
- vendor/github.com/gostaticanalysis/analysisutil/go.mod
- vendor/github.com/gostaticanalysis/analysisutil/go.sum
- vendor/github.com/gostaticanalysis/analysisutil/pkg.go
- vendor/github.com/gostaticanalysis/analysisutil/ssa.go
- vendor/github.com/timakin/bodyclose/LICENSE
- vendor/github.com/timakin/bodyclose/passes/bodyclose/bodyclose.go
- vendor/modules.txt
This commit adds full support for bodyclose linter
(https://github.com/timakin/bodyclose), which checks if an `http.Body`
element is correctly closed after usage.
Since it can be used via `go/analysis`, I followed the `govet` example
as suggested by https://github.com/golangci/golangci-lint/wiki/How-to-add-a-custom-linter.
This commit is fully tested, and contains a (flawed) test program which
calls `http.Get()` on `https://google.com` and does not closes its
corresponding `http.Body`.
>  Added "bodyclose" support

- README.md
- README.tmpl.md
Currently go garbage collector variable is written as GOCC in a link where it should be GOGC. Fixed the typo.
> Typo GOCC to GOGC

- README.md
- pkg/commands/run.go
- pkg/config/config.go
- pkg/printers/junitxml.go
Squashing commits and doing PR off master not dev branch (versus https://github.com/golangci/golangci-lint/pull/540)
> junit-xml output

- .travis.yml
- Makefile
- pkg/golinters/gofmt.go
- test/errchk.go
- test/testdata/gofmt_no_simplify.go
- test/testshared/testshared.go
- vendor/modules.txt
Output
File is not `gofmt`-ed
insted of
File is not `gofmt`-ed  with `-s`
when gofmt.simplify == false
> fix #513: don't add gofmt "with -s" if not needed

- README.md
- README.tmpl.md
- pkg/result/processors/nolint_test.go
- pkg/result/processors/testdata/nolint.go
- pkg/result/processors/testdata/nolint_whole_file.go
Also, add more tests for block-wise
usage of //nolint.
> fix #521: explain //nolint usage in README

- README.md
- pkg/golinters/structcheck.go
Fixes a minor grammatical typo as reported in #556.
> Fix minor grammatical typo

- go.mod
- go.sum
- vendor/github.com/OpenPeeDeeP/depguard/README.md
- vendor/github.com/OpenPeeDeeP/depguard/depguard.go
- vendor/github.com/OpenPeeDeeP/depguard/rootchecker.go
- vendor/modules.txt
depguard was patched to improve performance on large projects, by caching checks for root packages from the import paths.
This PR merely updates depguard to version 1.0.0, and then `make vendor` was run.
/edit
`make test` was also run without issues
> Update depguard version to 1.0.0 (Performance improvements)

- pkg/fsutils/filecache.go
- pkg/fsutils/linecache.go
Hi!
We've got panic happened while liniting our repository with golangci-lint. The reason is concurrent writes in filecache map. I tried to fix it via using sync.Map instead of map, so there must be no concurrent [read/]writes. Also there might be possible race in linecache because there is no any mutex either. 
<details>
<summary>Panic</summary>
```
if [ "Darwin" = "Darwin" ]; then export PKG_CONFIG_PATH=/opt/X11/lib/pkgconfig/; else export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/; fi && \
golangci-lint run -c golangci_extended.yml -v  ./src/mail/...
level=info msg="[config_reader] Used config file golangci_extended.yml"
level=info msg="[lintersdb] Active 29 linters: [bodyclose deadcode depguard dupl errcheck goconst gocritic gocyclo gofmt goimports golint gosec gosimple govet …
```
> Fix panic in filecache

- pkg/golinters/gochecknoglobals.go
See https://github.com/leighmcculloch/gochecknoglobals/commit/7c3491d2b6ec7491e3fe40b42c6e436aea88bacd
> Update `gochecknoglobals` to support version exception

- pkg/golinters/megacheck.go
- pkg/lint/linter/context.go
- pkg/lint/load.go
Use deduplicated packages for all linters except megacheck.
See https://github.com/golangci/golangci-lint/pull/585 for details.
> Speed up linting: use deduplicated packages

- .goreleaser.yml
```
% uname -v
FreeBSD 12.0-RELEASE-p7 GENERIC
% uname -m
amd64
% ./golangci-lint-SNAPSHOT-d2b1eea2c6171a1a1141a448a745335ce2e928a1-freebsd-amd64/golangci-lint -h
Smart, fast linters runner. Run it in cloud for every GitHub pull request on https://golangci.com
Usage:
golangci-lint [flags]
golangci-lint [command]
Available Commands:
config      Config
help        Help
linters     List current linters configuration
run         Run this tool in cloud on every github pull request in https://golangci.com for free (public repos)
Flags:
--color string              Use color when printing; can be 'always', 'auto', or 'never' (default "auto")
-j, --concurrency int           Concurrency (default NumCPU) (default 8)
--cpu-profile-path string   Path to CPU profile output file
-h, --help …
```
> Build FreeBSD binaries

- README.md
- README.tmpl.md
> Updates README with additional nolint notes

- .golangci.yml
- README.md
- pkg/config/config.go
- pkg/golinters/depguard.go
- test/testdata/configs/depguard.yml
- test/testdata/depguard.go
This adds the ability for a user to add an error message for specific packages when encountered in depguard issues.  This is really useful to point users to use another package. 
An example of what the new output looks like when a user supplies an error message
I have made an upstream PR to add similar functionality to depguard in https://github.com/OpenPeeDeeP/depguard/pull/12
> Add user supplied error messages in depguard issues

- install.sh
`adjust_format()` should use OS and not ARCH. In Windows, `$OS` will be calculated to be `"windows"` while `$ARCH` will be `"386"` or `"amd64"` (most of the time). `$ARCH` will surely never be `"windows"`.
> Fix install script on Windows

- pkg/commands/run.go
- pkg/config/config.go
- pkg/lint/runner.go
Hopefully this is ok @jirfag!
This will make big difference for Pion. The more we crank up the linter the easier it gets to be a maintainer :) thanks again for golangci-lint, it has made a huge difference.
> fix #416: Add skip-dirs-use-default

- pkg/printers/junitxml.go
As noted in https://github.com/golangci/golangci-lint/pull/557#issuecomment-518152477 - the current Junit xml output treats each lint issue as a passing test.
This PR expands the details and shuffles things around so that it shows up as a failing test instead.
There didn't seem to be any automated tests for this functionality, so I haven't added any new ones.
Here's a sample of what that looks like with CircleCI's junit parsing
https://circleci.com/gh/glenjamin/golangci-lint/5
I don't know which other popular tools do junit parsing like this - I based this implementation loosely off https://github.com/eslint/eslint/blob/master/lib/cli-engine/formatters/junit.js
> Update format of junit xml output to mark failures as such

- README.md
- README.tmpl.md
Thanks for the great project golangci-lint which we have used and thank you for considering CNCF project kubeedge/kubeedge to your list of projects using golangci-lint. 
I have changed the `README.tmpl.md` and running `make README.md`.
> Add kubeedge to list of projects using golangci-lint

- pkg/commands/completion.go
- pkg/commands/executor.go
Cobra has built in support for bash completions. Expose these via a command.
These can be used with `source <(./golangci-lint completion)`
> Add support for bash completions

- README.md
- go.mod
- go.sum
- pkg/golinters/whitespace.go
- pkg/lint/lintersdb/manager.go
- test/testdata/whitespace.go
- vendor/github.com/ultraware/whitespace/LICENSE
- vendor/github.com/ultraware/whitespace/README.md
- vendor/github.com/ultraware/whitespace/main.go
Support for yet another linter I made. I already included the fix for cgo in this linter.
> Add whitespace linter

- .goreleaser.yml
Based on https://goreleaser.com/customization/#Homebrew, update the brew tap configuration with the bash completions added in https://github.com/golangci/golangci-lint/pull/640
> Add bash completion to homebrew formula

- Dockerfile
Updates Dockerfile to Go 1.13. Fixes #683.
> Update Dockerfile to Go 1.13.

- .golangci.example.yml
- README.md
- pkg/config/config.go
- pkg/config/reader.go
- pkg/golinters/govet.go
- pkg/golinters/govet_test.go
- pkg/lint/runner.go
- vendor/golang.org/x/tools/go/analysis/passes/atomicalign/atomicalign.go
- vendor/modules.txt
Fix #696, #446
Please feel free to request any changes.
> govet: implement analyzers config

- .travis.yml
- go.mod
- go.sum
- vendor/github.com/valyala/quicktemplate/README.md
- vendor/modules.txt
Updates Update to valyala/quicktemplate v1.2.0. to latest version and cleanup some obsolete `go get` commands that were bypassing go.mod dependency management in CI.
> Update to valyala/quicktemplate v1.2.0

- .golangci.example.yml
- .golangci.yml
- README.md
- pkg/config/config.go
- pkg/golinters/dogsled.go
- pkg/lint/lintersdb/manager.go
- test/testdata/dogsled.go
- third_party/dogsled/LICENSE
Adds https://github.com/alexkohler/dogsled linter to detect assignments with too many blank identifiers.
e.g. `x, _, _, _, := f()`
The logic was ported similar to what was done for `nakedret` and `prealloc` since the upstream source cannot be integrated directly.
> Add dogsled linter

- test/run_test.go
- test/testdata/govet.go
- test/testdata/staticcheck.go
Fixes spurious test failures caused by overlapping printf format checks in `staticcheck` and `go vet`. In general, this is a concurrency issue which can happen with any linters that detect similar issues with different reporting formats.
see:
https://travis-ci.com/golangci/golangci-lint/jobs/236978712
https://travis-ci.com/golangci/golangci-lint/jobs/237582672
> Fix flaky cgo test failures

- Makefile
Misc. cleanup to dedupe GO111MODULE configurations and enable Go modules across all make targets.
> Enable Go module support across all commands

- pkg/golinters/goanalysis/runner.go
Set analysis pass results to nil early to garbage collect them
soon.
Memory can be reduced for the following linters:
- staticcheck
- stylecheck
- gosimple
- govet
- bodyclose
- any future go/analysis linter
Relates: #712, #634, #628, #598, #509, #483, #337
> Drop memory usage of go/analysis linters 5x

- Makefile
Explicitly set GOPROXY to enable consistent module behavior between Go 1.12 and 1.13. Fixes spurious Go 1.12.x build failures due to temporarily offline repos.
see:
https://travis-ci.com/golangci/golangci-lint/jobs/238269611
> Enable consistent GOPROXY Go 1.12/1.13 behavior

- README.md
- README.tmpl.md
- go.mod
Updates go.mod and project docs to require Go 1.12 or higher.
> Update minimum Go version to 1.12

- Makefile
Cleanup go.mod/go.sum diff check which is now unnecessary since Go 1.11 is no longer supported.
> Cleanup obsolete go.mod/go.sum diff

- .gitignore
- Makefile
Fixes release issues by building the godownloader/goreleaser binaries before using them from the project root.
> Build godownloader/goreleaser tools before use

- README.md
- pkg/lint/lintersdb/manager.go
Fixes some broken dominikh/go-tools linter URLs.
> Fix broken dominikh/go-tools URLs

- pkg/golinters/govet.go
Following the comments in #759
Some analyzers are not intended for direct usage and are
just build blocks for other analyzers.
Seems like we can distinguish them by ResultType nillness.
Note that there is a `TestGovet` that checks that all default analyzers are in `getAllAnalyzers` result, so we are safe from accidentally disabling them.
> govet: skip internal analyzers

- README.md
- pkg/golinters/gochecknoglobals.go
Fixes incorrect description from accidental copy/paste in https://github.com/golangci/golangci-lint/pull/758.
> Fix incorrect description

- pkg/commands/executor.go
- pkg/commands/version.go
This PR implements the `version` command as discussed in the linked issue.
It follows the same structure as the `golangci-lint --version` flag.
```console
➜ golangci-lint git:(implement-version-command) ✗ golangci-lint --version
golangci-lint has version (devel) built from (unknown, mod sum: "") on (unknown)
➜ golangci-lint git:(implement-version-command) ✗ golangci-lint version
golangci-lint has version (devel) built from (unknown, mod sum: "") on (unknown)
```
Fixes #675
> Add version command to print golangci-lint version

- tools/go.mod
- tools/go.sum
Updates to latest goreleaser tools that include a workaround for extremely large tar `uid`/`gid` (#752).
> Update to latest godownloader/goreleaser versions

- .golangci.example.yml
> fix misplaced backtick in example config in readme

- pkg/golinters/gofmt_common.go
This causes goimports to provide additional information if the
"local-prefixes" option has been set.
Fixes https://github.com/golangci/golangci-lint/issues/773. See the new proposed output with this change:
```
$ golangci-lint run -c .golangci.yaml                               
main.go:6: File is not `goimports`-ed with -local github.com/ian-howell/foo (goimports)
"github.com/ian-howell/foo/pkg"
```
> Improve the error output from goimports

- .golangci.yml
- README.md
Enables all gocritic tags to run against the golangci-lint codebase.
> Enable all gocritic tags

- .golangci.yml
- README.md
- internal/cache/cache.go
- pkg/config/config.go
- pkg/config/config_gocritic.go
- pkg/golinters/goanalysis/runner.go
- pkg/lint/lintersdb/enabled_set.go
- pkg/lint/load.go
- pkg/packages/util.go
- pkg/printers/codeclimate.go
- pkg/result/processors/fixer.go
Misc. cleanup of obsolete `nolint` directives.
> Cleanup nolint directives

- .golangci.example.yml
- README.md
- go.mod
- go.sum
- pkg/config/config.go
- pkg/golinters/whitespace.go
- test/testdata/fix/in/whitespace.go
- test/testdata/fix/out/whitespace.go
- vendor/github.com/ultraware/whitespace/README.md
- vendor/github.com/ultraware/whitespace/main.go
- vendor/modules.txt
I added another setting to whitespace. I also added comments for the settings as requested after the last PR was merged.
> Update whitespace to v0.0.4

- test/testdata/gocognit.go
Adds a few more gocognit tests taken from the upstream [README](https://github.com/uudashr/gocognit).
/cc @uudashr
> Add more gocognit tests

- .golangci.example.yml
- README.md
- go.mod
- go.sum
- pkg/config/config.go
- pkg/golinters/wsl.go
- test/testdata/wsl.go
- vendor/github.com/bombsimon/wsl/README.md
- vendor/github.com/bombsimon/wsl/go.mod
- vendor/github.com/bombsimon/wsl/go.sum
- vendor/github.com/bombsimon/wsl/wsl.go
- vendor/modules.txt
After WSL v1.0.1 got merged last week I found a few false positives which is resolved in this version. I've also added support for some configuration which is bundled in this commit.
I aimed to use non-negative configuration names so defaulting them to `true` required me to create a config struct, hope this is OK.
I sent an email to Denis yesterday with a few questions regarding this linter but decided to create this PR even though I haven't gotten any response yet since I don't want to risk miss this update if a new release of `golangci-lint` is being created.
> Update WSL to v1.2.1

- .goreleaser.yml
Adds `ppc64le` as a goreleaser architecture.
> Add ppc64le release

- .golangci.example.yml
- Makefile
- README.md
- README.tmpl.md
- pkg/commands/run.go
- pkg/config/config.go
- test/run_test.go
> Rename deadline option to timeout and mark deadline as deprecated

- .goreleaser.yml
Adds `s390x` as a goreleaser architecture.
> Add s390x release

- go.mod
- go.sum
- internal/pkgcache/pkgcache.go
- pkg/exitcodes/exitcodes.go
- pkg/golinters/goanalysis/linter.go
- pkg/golinters/goanalysis/runner.go
- pkg/golinters/golint.go
- pkg/lint/lintersdb/manager.go
- pkg/timeutils/stopwatch.go
- vendor/github.com/golangci/lint-1/lint.go
- vendor/modules.txt
Speed up golint: don't typecheck packages twice.
Relates: #805
> Make fine-grained hashing.

- .golangci.example.yml
- README.md
- go.mod
- go.sum
- pkg/config/config.go
- pkg/golinters/wsl.go
- test/linters_test.go
- test/testdata/wsl.go
- vendor/github.com/bombsimon/wsl/wsl.go
- vendor/modules.txt
* Fix false positive multiline case (test added)
* Fix false positive slice expression (test added)
* Fix false positive index expression (test added)
* Support to configure/allow cuddle declarations (example config added)
* Support to configure/allow case blocks to end with whitespace (example config added)
* Support cuddle defer http body close
Note: Had to update the test runner with `--max-same-issues=10` to allow my tests to cover added false-positives which yields the same error.
> Update WSL to v1.2.5

- .golangci.yml
- README.md
- pkg/commands/run.go
- test/run_test.go
Hi,
I'm afraid the PR https://github.com/golangci/golangci-lint/pull/793 generated a side effect: while deadline still works and becomes the effective timeout setting when supplying it as a flag/cmdline arg, we've realized deadline in the configuration file is no longer being honored (ok, its deprecated, but probably we wanted this to become a breaking change, forcing all consumers to immediately change their config): see the test we are incorporating, that clearly reproduces the situation.
Proposing a fix (but not prod of it), so deadline is still considered (no matter where it comes from) if its value is different of the default timeout (that becomes a constant). There may be alternative implementations or better places to put this logic, but I didnt want to make the config package …
> deadline is now deprecated, but should be taking its value from the configuration if set

- test/run_test.go
Fixes https://github.com/golangci/golangci-lint/issues/847
Recent commit https://github.com/golangci/golangci-lint/commit/df279922f66c65ed1ba0f7407977ab26f5d3c8b0 hides the flag and not showing depreciated message. However, the related test case is still expecting `depreciated message`
Also fixed one test case in which `check-exported` is true, but the unused public function message is not expected.
> Fixed unit test cases (build failed in master branch)

- README.md
- README.tmpl.md
[The Mercure project](https://github.com/dunglas/mercure) is now a proud user of `golangci-lint`! Thanks for this tool.
> Add Mercure in the list of projects using golangci-lint

- pkg/golinters/gomnd.go
- pkg/lint/lintersdb/manager.go
Address naming convention mentioned in https://github.com/golangci/golangci-lint/pull/842
> Addressed naming convention

- go.mod
- go.sum
Update to semantic version for go-mnd.
Related issues:
https://github.com/golangci/golangci-lint/pull/842
https://github.com/tommy-muehle/go-mnd/issues/1
> Use the semantic version for go-mnd

- README.md
- pkg/golinters/gomnd.go
The previous description was a bit confusing. Because there is not "the" magic number. So I changed it to a more clearer version in my opinion.
> Update description of gomnd

- .github/ISSUE_TEMPLATE.md
`bash` means bash-script.
`console` means shell script, prompt and response.
> chore: we can use a "console" for syntax

- pkg/commands/run.go
- pkg/lint/runner.go
We now return an error if any linter is unable to run to
not exit on 0 in that case.
Closes #451
> Propagate error when linter cannot be run

- .golangci.example.yml
- .golangci.yml
- README.md
This PR fixes the following issues:
* `packages-with-error-messages` should be `packages-with-error-message` based on the `mapstructure` tag from https://github.com/golangci/golangci-lint/blob/master/pkg/config/config.go#L165
* Due to https://github.com/spf13/viper/issues/348, after fixing above typo, it'll fail with
```
* 'linters-settings.Depguard.packages-with-error-message[github]' expected type 'string', got unconvertible type 'map[string]interface {}'
```
since alot of package names will have dots in them. A workaround is to specify as a list of maps, which will get merged by `mapstructure` (see [config](https://github.com/mitchellh/mapstructure/blob/master/mapstructure.go#L76)). Viper does have `WeaklyTypedInput` [enabled by …
> Fix depguard config in yml

- .golangci.yml
- Makefile
- README.md
- install.sh
Misc. build, config, and script cleanup.
> Misc. build cleanup

- README.md
- README.tmpl.md
GoLand now has a File Watcher `golangcli-lint` template.
_Tested in version 2019.3.1, but could be in earlier versions ([2019.1.1?](https://youtrack.jetbrains.com/issue/GO-4574))_
The builtin `golangcli-lint` template has `Arguments:` set to `run --disable=typecheck $FileDir$`
> Update GoLand instructions in README.md

- .goreleaser.yml
zsh completion has been implemented at https://github.com/golangci/golangci-lint/pull/903 .
So this PR installs it in homebrew.
> Add zsh completion to homebrew

- .golangci.example.yml
- README.md
- pkg/commands/run.go
- pkg/config/config.go
- pkg/result/processors/uniq_by_line.go
- pkg/result/processors/uniq_by_line_test.go
hi,
sometimes it's usefull to see all linters, that was triggered by the line
so i have added new param for this
> make uniq-by-line configurable

- .goreleaser.yml
Add release for android. Some of use Termux on Android as alternative development machine.
> Add release for android OS

- .golangci.yml
- README.md
Updates to latest 1.22.x release to fix failing checks.
> Update golangci.com config to latest 1.22.x release

- .golangci.yml
- README.md
- test/testdata/govet_custom_formatter/main.go
> Re-enable `gomnd` linter with release > v1.23.0

- README.md
- README.tmpl.md
Fixed a reference in `README` using the `tmpl`
> fix golangci.yml reference

- README.md
- README.tmpl.md
Note that we Open Source code under the argoproj org as well as intuit org.
> Add Intuit to README.md

- pkg/lint/linter/context.go
- pkg/lint/runner.go
Hi,
I investigated some similar issues - #827, #840, #885, #824, #888, ... - and I found:
- unused linter is not combined into goanalysis_metalinter
because unused linter's load mode is LoadModeWholeProgram,
so two linters are executed by default.
- in this situation, unused linter and goanalysis_metalinter shares the package information.
- when unused linter is executed, packages in the linter context seems to change.
- goanalysis_metalinter uses the changed packages in part of the analysis,
while "typecheck" linter in goanalysis_metalinter parses files by itself,
which results in error of type checking for dependent packages
by their inconsistency.
- the execution order of the linters randomly change because it is
determined by `range` of `map`, this is why we do not always encounter …
> Fix failed_prerequisites error

- pkg/config/config_gocritic.go
Improve `gocritic` disabled check warning message as per https://github.com/golangci/golangci-lint/issues/950.
> gocritic: update disabled check warning message

- pkg/result/processors/autogenerated_exclude.go
Some lines can be very long, so increase scanner
buffer to mitigate this.
Fix #954
> autogenerated_exclude: increase scanner buffer

- pkg/commands/executor.go
> fix #869 by removing lock file after unlocking

- .goreleaser.yml
- install.sh
Signed-off-by: Xiang Dai <764524258@qq.com>
Fix #935
Refer to [prometheus release](https://github.com/prometheus/prometheus/releases), support `mips64` and `mips64le`.
> Add MIPS arch support

- build/Dockerfile.alpine
> Dockerfile.alpine: add Git & Mercurial

- pkg/commands/run.go
- test/run_test.go
The current error message is `"Timeout exceeded: try increase it by passing --timeout option"`. I think it reads a little better as `"Timeout exceeded: try increasing it by passing --timeout option"`.
> Change Increase to Increasing in Timeout Exceeded Error Message

- pkg/result/processors/autogenerated_exclude.go
> autogenerated_exclude: increase scanner max buffer size

- pkg/golinters/govet.go
- pkg/golinters/govet_test.go
Similar to the behavior of command line flags:
enable-all to enable existing linters then disable unwanted ones.
But for vet rules.
For example
```yaml
govet:
enable-all: true
disable:
- nilfunc
```
> vet: Support disable rule when enable-all is true

- pkg/result/processors/fixer.go
The function assumed, previously, that issue.Line always equals
issue.LineRange.From.  But this needn't be true, and the code needn't
assume it.  Now we actually replace the specified line-range.
> Change writeFixedFile to replace the right line-range.

- README.md
- pkg/commands/run.go
- pkg/config/config.go
- pkg/printers/github.go
- pkg/printers/github_test.go
Github actions will annotate build failures in a special way if build errors are logged using their special format described in https://help.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-error-message . This allows easier inspection of linter failures inside github UI.
> Adding github actions output format

- README.md
- README.tmpl.md
Please take a look.
Closes #1006.
> doc: provide instructions for from-source installation

- .golangci.example.yml
- README.md
- pkg/config/config_gocritic.go
- pkg/config/config_gocritic_test.go
Linter Gocritic:
Features:
- support disabled-tags
using tag set-operation instead of disabled-checks inputs 
```yaml
...
enabled-tags:
- performance
disabled-tags:
- experimental 
...
```
> feat: [gocritic] support disabled-tags

- .golangci.example.yml
- README.md
- go.mod
- go.sum
- pkg/config/config.go
- pkg/golinters/testpackage.go
- pkg/lint/lintersdb/manager.go
- test/testdata/testpackage_internal_test.go
- test/testdata/testpackage_test.go
Add linter [testpackage](https://github.com/maratori/testpackage)
> Add linter testpackage

- README.md
- pkg/commands/run.go
- pkg/config/config.go
- pkg/lint/runner.go
- test/bench/bench_test.go
Adds IDs to default exclusions so they can be re-included on a case-by-case basis.
Backward-compatible part of https://github.com/golangci/golangci-lint/issues/456
> Re-enable default excludes by ID

- go.mod
- go.sum
- pkg/golinters/goerr113.go
- pkg/lint/lintersdb/manager.go
- test/testdata/goerr113.go
Adds https://github.com/Djarvur/go-err113 linter support
> Add go-err113 linter support

- .gitignore
- go.mod
- go.sum
- pkg/golinters/gosec.go
This change updates the `gosec` linter to its v2 version. It seems like v2
maintained API compatibility for the functionality we use, so we only needed to
update the dependency and imports.
Please note, this does not use a tagged version of `gosec` and instead is the
latest `master` commit due to this issue: https://github.com/securego/gosec/issues/470.
Once this issue is resolved we should update `gosec` to a tagged release.
This also adds a line to the `.gitignore` file, to ignore the `.test` output
files that get generated by `go test`. This could accidentally get left behind,
so no use committing binary files.
Fixes #1052
> Update gosec linter to v2; add .test files to .gitignore

- README.md
- README.tmpl.md
This project is shutting down on the 15th April. See the blog below:
https://medium.com/golangci/golangci-com-is-closing-d1fc1bd30e0e
> Remove reference to golangci.com in README

- pkg/golinters/dupl.go
- pkg/golinters/gofmt.go
- pkg/golinters/goimports.go
- pkg/golinters/gomodguard.go
- pkg/golinters/ineffassign.go
- pkg/golinters/lll.go
- pkg/golinters/misspell.go
- pkg/golinters/wsl.go
- test/run_test.go
- test/testdata/linedirective/dupl.yml
- test/testdata/linedirective/gomodguard.yml
- test/testdata/linedirective/hello.go
- test/testdata/linedirective/hello.tmpl
- test/testdata/linedirective/lll.yml
This will fix #998.
If the target files contains `//line` directive and it indicates a non-go file, the linter is going to handle it as a go file, which results in failure.
The cause of this issue is that the linters (`Analyzer`s) are using `pass.Fset.Position()`.
This func returns the adjusted position using `//line` directive.
The example project reported in #998 has `//line` directive that indicates other non-go file.
According to the description of [Compiler Directives](https://golang.org/cmd/compile/#hdr-Compiler_Directives), line directives is mainly used for reporting original positions to the generators or something.
On linters of golangci-lint, `pass.Fset.Position()` is used just to aggregate file names; we don't have to adjust positions.
This pull request changes `Analyzer`s …
> Fix lint errors on files with //line directive

- pkg/printers/junitxml.go
The Junit output format doesn't validate the Jenkins XSD:
https://github.com/jenkinsci/xunit-plugin/blob/master/src/main/resources/org/jenkinsci/plugins/xunit/types/model/xsd/junit-10.xsd
So, I have added tests, failures and errors attributes on testsuite elements.
> Add tests, failures and errors attributes on testsuites

- go.mod
- go.sum
When raising #1062 I noted that the gosec dependency had been upgraded to v2,
but needed to be pulled from `master` due to some issues with the v2.2.0 tagged
release. That was tracked in https://github.com/securego/gosec/issues/470.
They've since cut v2.3.0, so let's update to that tagged release before we
release a new version of golangci-lint.
> Update gosec2 dependency to a tagged version (v2.3.0)

- README.md
- pkg/config/config.go
- test/testdata/errcheck/ignore_config.yml
Exception EXC0001 ignores errors on functions like Sprint and Sprintf, but not Sprintln. Update the exception to include *println as well. This matches the default behavior of errcheck for `fmt.*print*`.
> Add *println to exception EXC0001

- .golangci.example.yml
- docs/src/docs/contributing/workflow.mdx
- go.mod
- go.sum
- pkg/config/config.go
- pkg/golinters/gomodguard.go
adds a new feature to allow blocking modules based on version constraints
> bump gomodguard version

- pkg/lint/load.go
In case of timeouts of go/packages loading
we could return such error.
Relates: #825
> fix invalid error message "no go files to analyze"

- .golangci.example.yml
- pkg/lint/lintersdb/manager.go
- pkg/result/processors/nolint_test.go
Fix descriptions and comments for nolintlint and link to README
Fixes #1086
> Fix up nolintlint comments and urls

- internal/cache/cache.go
Fix warning about not existing cache file.
Fixes: #925
> cache: fix warning

- docs/src/docs/contributing/new-linters.mdx
This updates the new-linters doc. I've fixed a filename (`lintersdb.go` -> `manager.go`), and remove outdated line numbers from the links. 
If preferred, I can add correct line numbers using a GitHub link at a fixed commit instead of master — to avoid the line numbers being outdated again.
> update new-linters doc

- docs/src/docs/contributing/new-linters.mdx
I just encountered not found page after I clicked the URL link.
I updated to correct URL link by following other URLs in this page.
> Update not found url in new-linters.mdx

- CHANGELOG.md
- go.mod
- go.sum
- pkg/golinters/gofumpt.go
- pkg/lint/lintersdb/manager.go
- test/testdata/gofumpt.go
Hey!
I was also interested in https://github.com/golangci/golangci-lint/issues/490 (adding gofumpt).
Here is a PR for it.
> Adding gofumpt

- pkg/result/processors/filename_unadjuster.go
As signalled in #612 there has been another occurrence of concurrent map writes.
This should address the issue by passing a mutex alongside the map and locking it when writing. Given that the concurrent writes are only occurring while the map is being filled we do not need to pass the mutex back as part of the `FilenameUnadjuster` struct. Consumers of this type should protect against concurrency issues themselves when operating on the enclosed map field.
> Protect NewFilenameUnadjuster from concurrent map writes

- .goreleaser.yml
Relates to #988 where we with this commit build `rpm` and `deb` packages.
> Build rpm and deb packages with goreleaser

- .golangci.example.yml
- README.md
- go.mod
- go.sum
- pkg/config/config.go
- pkg/golinters/goheader.go
- pkg/lint/lintersdb/manager.go
- test/linters_test.go
- test/testdata/configs/go-header.yml
- test/testdata/go-header.go
Signed-off-by: denis-tingajkin <denis.tingajkin@xored.com>
https://github.com/golangci/golangci-lint/issues/1180
> Add go-header linter

- go.mod
- go.sum
- pkg/config/config_gocritic.go
- pkg/golinters/gocritic.go
- test/errchk.go
> Upgrading to go-critic v0.5.0

- .github/workflows/pr.yml
> Use golangci-lint 1.28 to lint golangci-lint codebase

- pkg/golinters/goheader.go
- test/linters_test.go
- test/testdata/go-header_bad.go
- test/testdata/go-header_good.go
During local testing latest golangci, we've found that go-header linter can throw nil pointer exception in case of a source file is valid.
1. Use next go-header config
```
goheader:
template: "test"
```
2. Run golangci linter on file with valid header, for example
```
//test
//Package mypkg ...
package mypkg
```
Actual: nil pointer exception
Expected: Template has matched no issues should be found
> Fix: goheader linter can throw nil pointer exception in case of a source file has not issues

- .github/workflows/tag.yml
- assets/github-action-config.json
Fix a failing release workflow
> Explicitly pass GITHUB_TOKEN env to goreleaser action

- .goreleaser.yml
DEPRECATED: `brews.github` should not be used anymore, check https://goreleaser.com/deprecations#brewsgithub for more info.
> Fix deprecation warning in goreleaser

- .golangci.example.yml
- pkg/commands/run.go
- pkg/config/config.go
- pkg/lint/runner.go
- pkg/result/processors/path_prefixer.go
- pkg/result/processors/path_prefixer_test.go
- test/run_test.go
- test/testshared/testshared.go
Meant as an alternative to https://github.com/golangci/golangci-lint/pull/1225 which uses the standard processor abstraction
It's often convenient in monorepos to run a tool from a different directory but still report issues relative to the root of the repository.
This is exactly the problem in the github action https://github.com/golangci/golangci-lint-action/issues/31
Add a flag for specifying a path prefix in output. Default behavior remains the same.
---
Thanks for a great tool!
> Configure path prefix via processor abstraction

- test/run_test.go
https://github.com/golangci/golangci-lint/pull/1226 appears to have introduced a test failure into master via a combination of factors.
My current theory:
1. A test refers to a test data directory in camel-case, but the directory isn't actually camel-case
2. This camel-case test passed locally for me because MacOS's fs is case-insensitive
3. This test somehow did not run on the PR build
4. It finally ran against master where the fs was not case-insensitive
[Success in PR](https://github.com/golangci/golangci-lint/runs/858079330) -- **TestPathPrefix** is nowhere present
[Failure in master](https://github.com/golangci/golangci-lint/runs/859880992?check_suite_focus=true#step:5:881)
> Use lowercase directories to fix test

- docs/src/docs/contributing/workflow.mdx
Related to https://github.com/golangci/golangci-lint/pull/1234
Signed-off-by: sayboras <sayboras@yahoo.com>
> Update the post release steps

- pkg/commands/run.go
- pkg/config/config.go
- pkg/lint/runner.go
- pkg/result/processors/sort_results.go
- pkg/result/processors/sort_results_test.go
- test/run_test.go
- test/testdata/sort_results/main.go
Implements https://github.com/golangci/golangci-lint/issues/1217
> Sorting result.Issues implementation (golangci/golangci-lint#1217)

- go.mod
- go.sum
This pulls in a fix for handling of blank identifiers by the exhaustive
package.
Patch obtained by running:
go get github.com/nishanths/exhaustive
> upgrade github.com/nishanths/exhaustive

- pkg/lint/lintersdb/validator.go
Signed-off-by: denis-tingajkin <denis.tingajkin@xored.com>
1. Use new golangci-linter config file
2. Use old linter version (for example 1.26)
**Actual**: Printed err msg 'no such linter %v' for all new linters which was added since 1.26. The error message looks is not clear for new users. The message can confuse the user like 'Should I download missed linter?'. 
I think we need to point that the user can run  `golangci-lint linters` to see supported linter list of his `golangci-linter` tool.
> Improve 'no such linter' error message

- go.mod
- go.sum
- pkg/golinters/gofmt.go
- pkg/golinters/gofmt_common.go
- pkg/golinters/gofumpt.go
- pkg/golinters/goimports.go
- test/testdata/fix/in/gofumpt.go
- test/testdata/fix/out/gofumpt.go
- test/testdata/gofumpt.go
- test/testdata/gofumpt_with_extra.go
Add autofix functionality (`-w`)
Add fix and linter tests.
Closes: #490
Since the `gofumpt/format.Source` returns already formatted body of a file, but `golangci-lint` expects a diff to support auto-fixing, so I use `github.com/shazow/go-diff/difflib` library to make a diff of input and output. I expect, that it can be slower than `gofmt` linter.
> Support --fix for gofumpt

- CHANGELOG.md
- README.md
- go.sum
I order to prepare the `v1.29.0` release
* auto update `README.md` using `make update_contributors_list` command
* manual update of `CHANGELOG.md`
> Update README and CHANGELOG files

- .golangci.example.yml
- .golangci.yml
- go.mod
- go.sum
- pkg/config/config.go
- pkg/golinters/gci.go
- pkg/golinters/gofmt_common.go
- pkg/lint/lintersdb/manager.go
- test/linters_test.go
- test/testdata/gci.go
- test/testdata/gci/gci.go
> Introduce gci as new linter

- .github/workflows/pr.yml
IMO we need to run the tests on macOS in same way we do for windows, so I added tests-on-macos as a parallel job with the go v1.14, so only ubuntu job will use different go version for testing.
> Add tests-on-macos

- go.mod
Here is the output with v0.2.1 and v0.2.2:
```v0.2.1
$ gci -d galley/pkg/config/source/kube/interfaces.go
diff -u galley/pkg/config/source/kube/interfaces.go.orig galley/pkg/config/source/kube/interfaces.go
--- galley/pkg/config/source/kube/interfaces.go.orig	2020-08-17 10:32:06.048341665 +0800
+++ galley/pkg/config/source/kube/interfaces.go	2020-08-17 10:32:06.048341665 +0800
@@ -18,7 +18,9 @@
"k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset"
"k8s.io/client-go/dynamic"
"k8s.io/client-go/kubernetes"
-	_ "k8s.io/client-go/plugin/pkg/client/auth/gcp" // import GKE cluster authentication plugin
+
+	//  import GKE cluster authentication plugin   <===
+	_ "k8s.io/client-go/plugin/pkg/client/auth/gcp"
"k8s.io/client-go/rest"
"k8s.io/client-go/tools/clientcmd"
)
```
```v0.2.2
$ gci …
```
> Bump up gci to v0.2.2

- .github/workflows/pr.yml
- .github/workflows/tag.yml
- build/Dockerfile
- build/Dockerfile.alpine
- test/enabled_linters_test.go
- test/testdata/nolintlint_unused.go
The binary is much smaller from 37MB to 31MB
```
-rwxrwxr-x  1 tammach tammach 38016216 Aug 12 22:36 golangci-lint.1.14
-rwxrwxr-x  1 tammach tammach 32142632 Aug 12 22:44 golangci-lint
```
Performance test
```
$ golangci-lint cache clean
$ time golangci-lint run ./...
golangci-lint run ./...  100.29s user 2.16s system 382% cpu 26.753 total
$ golangci-lint-1.15 cache clean
$ time golangci-lint-1.15 run ./...
golangci-lint-1.15 run ./...  98.14s user 2.21s system 380% cpu 26.389 total
$ golangci-lint cache clean
$ time golangci-lint run --timeout 30m ./...
golangci-lint run --timeout 30m ./...  996.16s user 15.05s system 1333% cpu 1:15.85 total
$ golangci-lint-1.15 cache clean
$ time golangci-lint-1.15 run --timeout 30m ./...
golangci-lint-1.15 run --timeout 30m ./...  989.70s user 15.09s …
```
> Upgrade go 1.15 for smaller binary

- pkg/commands/run.go
- pkg/commands/version.go
- pkg/config/config.go
Closes #1314 
Support printing the version I different formats:
* short: prints only version
* json: prints in json format
> Support short and json formats for version cmd

- docs/src/docs/usage/configuration.mdx
- pkg/config/reader.go
See #1324 
**Guidance required:** tests don't pass if you have a configuration file in your home directory. This is because some tests check that config is not found. I need assistance on how to update tests properly.
> Add home directory to config file search paths

- pkg/commands/executor.go
- pkg/commands/run.go
- pkg/config/config.go
By default, golangci-lint fails after five seconds if another instance
is running. It is possible to disable that, but the discussion around
whether the cache is safe to use concurrently is not exactly full of
confidence. Add a flag that allows golangci-lint to wait forever
instead of failing.
see #1301
> Allow for serializing multiple golangci-lint invocations

- go.mod
- go.sum
- pkg/golinters/gci.go
- test/linters_test.go
Fix [issue](https://github.com/daixiang0/gci/issues/8).
It is helpful to run in a small os without `diff` cmd.
> Gci: update the way to call Run()

- docs/src/docs/usage/performance.mdx
> Fix typo in performance docs

- CHANGELOG.md
- README.md
- go.sum
* Update CHANGELOG
* Clean up the go.sum
* Update contributors list
> Prepare v1.31.0

- go.mod
- go.sum
This PR is to update the unparam/gofumpt to latest hash
Fixes #1375
PS: Another reason to use tag version when possible as dependent bot might not be able to handle hash update.
> chore(dep): Update unparam/gofumpt to latest commit hash

- .gitattributes
- .github/workflows/pr.yml
This commit is to add job to check if go.mod and go.sum are up to
date.
Also add go.sum into .gitattributes so that it will be considered
as generated file in PR review.
> build(go): Check if go.mod and go.sum are up to date

- .goreleaser.yml
- go.mod
- go.sum
- pkg/commands/completion.go
Add completion support for fish shell
> Add support for fish completion

- .github/workflows/pr-extra.yml
- .nancy-ignore
Currently nancy is always failed, and we seem to ignore it completely.
This reduces the value of having security scanning significantly.
Ideally, the underlying issue should be fixed, however it will require
long time for external collaboration.
This commit is to ignore two known dependency failures.
Note: ignoring any dependency must be consious choice.
> build(dep): Ignore known dependency failure in nancy

- .github/workflows/pr.yml
Our tests for macOS and Windows are using the `continue-on-error` option, making them always showing up as passing even when they fail. [Here's an example of a failing job being marked as passing](https://github.com/golangci/golangci-lint/pull/1380/checks?check_run_id=1141753724). This PR removes this option for macos because [Windows is broken](https://github.com/golangci/golangci-lint/pull/1381/checks?check_run_id=1141826954).
> ci: prevent macos to be marked as passing upon failure

- .github/workflows/pr-extra.yml
Nancy's Github action renamed their master branch to `main`, which broke everything. This PR fixes that.
> fix Nancy's branch name

- .github/workflows/pr.yml
- go.sum
This commit is to update go-mod github action step to check for only
go.mod file. Ideally, both go.mod and go.sum should be checked, however,
the current behavior of `go mod tidy` command will not clean up old
entries in go.sum.
Additionally, dependentbot is currently failing as there is dirty change
in go.sum file.
> ci(dep): Check only for go.mod file

- .github/workflows/codeql.yaml
This commit is to add codeQL scanning, which is newly introduced feature
from github.
The scan will be run per PR, and periodically as well.
**Note**: Autobuild seems to be troublesome, so I just run with manual build. Javascript can be enabled later once I have more understanding how codeQL works.
> ci(scan): Add codeQL scanning

- go.mod
- go.sum
- pkg/golinters/tparallel.go
- pkg/lint/lintersdb/manager.go
- test/linters_test.go
- test/testdata/tparallel/happy_path_test.go
- test/testdata/tparallel/missing_subtest_test.go
- test/testdata/tparallel/missing_toplevel_test.go
- test/testdata/tparallel/tparallel_test.go
This PR adds the [tparallel](https://github.com/moricho/tparallel) linter. This linter checks for inefficient usage of `t.Parallel()` in the tests.
Closes #1371 (cc @moricho)
~The Nancy failure is being taken care of in #1378 and #1293~ Merged
~Note: After doing more manual tests with the linter, I found a false positive: https://github.com/moricho/tparallel/issues/8. That shouldn't prevent reviewing though, I'll update the linter's version once it's been fixed.~ Done
> Add tparallel linter

- .goreleaser.yml
After installing the `deb` package many `dpkg` tools started to complain about the missing `Maintainer` field for this package in the system installed package database. This causes spam from cron.
Example:
```
$ LANG=C dpkg-query -s > /dev/null 
dpkg-query: warning: parsing file '/var/lib/dpkg/status' near line 14485 package 'golangci-lint:i386':
missing 'Maintainer' field
```
> Add dummy maintainer to keep `dpkg` happy

- pkg/commands/completion.go
This commit is to add support for powershell completion script.
Note: PowerShell v5.0+ is required
For reviewers: please find below the completion script output for powershell.
<details>
<summary>Completion script powershell</summary>
```
using namespace System.Management.Automation
using namespace System.Management.Automation.Language
Register-ArgumentCompleter -Native -CommandName 'golangci-lint' -ScriptBlock {
param($wordToComplete, $commandAst, $cursorPosition)
$commandElements = $commandAst.CommandElements
$command = @(
'golangci-lint'
for ($i = 1; $i -lt $commandElements.Count; $i++) {
$element = $commandElements[$i]
if ($element -isnot [StringConstantExpressionAst] -or
$element.StringConstantType -ne [StringConstantType]::BareWord -or
$element.Value.StartsWith('-')) {
break
} …
```
> feat(completion): Add support for powershell completion

- .github/dependabot.yml
npm packages are used for website only in this repo. Consider that
golangci-lint normally releases once a month, this commit is to change
interval for npm dependabot from weekly to monthly.
Main benefits could be:
- Reduce the noise for maintainers.
- Improve generated CHANGELOG. These changes are not useful for 
end users.
> ci(dependabot): Change interval for npm to monthly

- docs/src/docs/usage/install/index.mdx
The version of `golangci-lint` has been updated to the v1.30 version in macports. https://github.com/macports/macports-ports/commit/3703aa3bcc8fd46f8425947ca578e627936e2a30
> Mention macports installation procedure on macOS

- .github/workflows/tag.yml
- .goreleaser.yml
- build/Dockerfile
- build/Dockerfile.alpine
**Updated below files:**
1. Updated **.github/workflows/tag.yml** file to release the image for amd64 and arm64 using https://github.com/docker/build-push-action.
2. Updated **build/Dockerfile** and **build/Dockerfile.alpine** files to build the golangci-lint binary from the source code and copy that binary to /usr/bin/ using multi-stage docker build.
3. Removed the docker file section from **.goreleaser.yml** as goreleaser does not support multi-arch builds currently.
> Releasing docker image for arm64

- docs/src/docs/usage/configuration.mdx
Just a very minor documentation change.
Noted that `.golangci.yaml` is also searched for on startup as a config file - which is great, as I prefer to use `.yaml` over `.yml` as a file extension - as suggested here: https://yaml.org/faq.html
> Added `.golangci.yaml` to list of configuration files searched

- pkg/result/processors/severity_rules.go
- pkg/result/processors/severity_rules_test.go
Default severity is only used when rules are not empty
Make sure the rules transformations for modifying severity are skipped if there are not rules AND no default severity specified
> Added support for only specifying default severity

- go.mod
- go.sum
This commit is to use tag version for cobra (e.g. 1.1.1). The main
benefit is that this can be managed and upgraded by dependabot later.
This is follow-up item from PR #1201.
> chore(dep): Use tag version for cobra

- assets/github-action-config.json
This commit is to update metadata for golangci-lint-action after 1.32.0
release.
NOTE: Once #1208 is resolved, this step will be automated
Relates #1208
> feat(release): Update metadata for golangci-lint-action

- .github/workflows/tag.yml
- build/Dockerfile
- build/Dockerfile.alpine
As part of #1383, multi-arch docker build was supported. However,
ldflags for version details and CGO_ENABLED=0 were missing.
This commit is to add -ldflags as part of Docker build.
Fixes #1468
Testing was done with my docker hub and tag v1.32.1
<details>
<summary>Testing with arm64</summary>
```shell script
$ docker run --rm sayboras/golangci-lint:v1.32.1 golangci-lint version
golangci-lint has version v1.32.1 built from 89647eba on 2020-10-26T10:16:00Z
$ docker run --rm sayboras/golangci-lint:v1.32.1 golangci-lint --version 
golangci-lint has version v1.32.1 built from 89647eba on 2020-10-26T10:16:00Z
$ docker run --rm -w /src -v $PWD:/src sayboras/golangci-lint:v1.32.1 golangci-lint run ./...
$ uname -a
Linux ubuntu 5.4.0-1021-raspi …
```
> build(docker): Fix version details in docker image

- pkg/lint/lintersdb/validator.go
Otherwise, if one configures multiple invalid linters, or jumps between
the versions, it is annoying to get same error with different value N
times.
Signed-off-by: Mateusz Gozdek <mgozdekof@gmail.com>
> pkg/lint/lintersdb: report all unknown linters at once

- .github/workflows/tag.yml
This commit is to avoid tag overriding due to parallel build for
multiple base images (e.g. debian and alpine).
Closes #1483 
Closes #1486
Testing was done for forked docker hub (e.g. sayboras/golangci-lint).
```shell script
$ docker run -it --entrypoint /bin/sh sayboras/golangci-lint:v1.32.2 -c 'cat /etc/os-release'
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
```shell script
$ docker run -it --entrypoint /bin/sh sayboras/golangci-lint:latest -c 'cat /etc/os-release'
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian …
```
> fix(docker): Fix docker tag for alpine build

- pkg/result/processors/nolint.go
- pkg/result/processors/nolint_test.go
- pkg/result/processors/testdata/nolint_apply_to_unknown.go
- test/testdata/nolint_apply_to_unknown.go
Fixes #1450 by applying `//nolint` directive to a non-existent linter only.
> Unknown linter breaks //nolint

- .golangci.example.yml
- go.mod
- go.sum
- pkg/config/config.go
- pkg/golinters/godot.go
- test/testdata/godot.go
Update for godot linter. Now it can check any comment, not only top-level comments. Also it can check capital letter at the beginning of sentences.
There is a breaking change in config. I'm not sure what's the right way to introduce it. I removed old setting `check-all` from config example, but didn't remove it from `GodotSettings` struct to avoid breaking existing configs. Old setting `check-all` is silently translated to new `scope`.
> Update godot to 1.3.0

- pkg/config/config.go
- pkg/config/config_test.go
- pkg/golinters/goanalysis/runner.go
- pkg/lint/runner.go
- pkg/printers/github.go
- test/testdata/configs/default_exclude.yml
- test/testdata/default_exclude.go
Fixes https://github.com/golangci/golangci-lint/issues/1474
~This PR add "EXC0011", because most of package in golangci-lint does not having a package comment~. `make test` passed.
---------------------------
updated, for now, "EXC0011" same with "EXC0002" but with different linter field for keeping backward compatible.
> DefaultExcludePatterns should only be used for specified linter

- .golangci.example.yml
Fixes #1513. Flag was missing from the docs, apparently.
> Missing sort-results in the docs

- go.mod
- go.sum
Fixes #1535
Related to:
- https://github.com/tetafro/godot/issues/13
- https://github.com/tetafro/godot/releases/tag/v1.3.2
> fix: update github.com/tetafro/godot to v1.3.2

- pkg/commands/run.go
> Removing reference to no-longer-existing linter-in-the-cloud

- pkg/commands/run.go
We should remove a call to deprecated function.
> Cobra.Command.SetOutput is deprecated

- .golangci.example.yml
- go.mod
- go.sum
Closes #1557
Upstream project does not support Go Modules to reference @v2.2.0 directly, so used commit at that tag.
Updated via:
```console
$ go get github.com/tommy-muehle/go-mnd@16041ac3fe65b98fbbf4c3c9b88c346196211614
$ go mod tidy
```
> deps: Bump github.com/tommy-muehle/go-mnd@v2.2.0

- pkg/golinters/nolintlint/nolintlint.go
- pkg/golinters/nolintlint/nolintlint_test.go
- test/errchk.go
> fix: nolintlint comment analysis.

- .golangci.example.yml
- go.mod
- go.sum
- pkg/config/config.go
- pkg/golinters/forbidigo.go
- pkg/lint/lintersdb/manager.go
- test/testdata/configs/forbidigo.yml
- test/testdata/forbidigo.go
Forbidigo forbids identifiers.  It can be used to forbid code that is useful for debugging but should not be merged to the master branch.  I've found it particularly useful to make sure I don't commit `fmt.Print.*` statements or `ginkgo.F.*` commands that I've introduced during local debugging.
Not sure if there is another linter that already does this.  Please let me know if there is.
Base linter is at https://github.com/ashanbrown/forbidigo
> Add forbidigo linter

- pkg/lint/lintersdb/manager.go
Resolves #1085 by interpreting non-absolute plugin paths relative to the config file's directory (or the current working directory if no config file is used).
> Resolve custom linters' path relative to config file directory

- pkg/golinters/nolintlint.go
- pkg/golinters/nolintlint/nolintlint.go
- pkg/golinters/nolintlint/nolintlint_test.go
- pkg/result/issue.go
- pkg/result/processors/nolint.go
- test/testdata/fix/in/nolintlint.go
- test/testdata/fix/out/nolintlint.go
- test/testdata/nolintlint.go
This PR adds a fixing capability to `nolintlint`.  It doesn't try to fix everything. 
What it does (when --fix is enabled):
1) Removes non-specific `//nolint` directives that are not used.
2) Removes a linter from a linter-dispecific `//nolint` directive if that linter is not used for that line.
3) Removes all leading whitespace from `//. nolint` directives for any violations on the number of spaces.
What it does not do:
1)  Offer explanations when explanations for `nolint` are required but not provided.  I suppose it could add a placeholder that the user could replace but that doesn't seem really in the spirit of how the fix option is supposed to work (since the user might check in that placeholder).
2) Make non-specific linter directives specific.  This could be done but there is a risk …
> Update nolintlint to fix nolint formatting and remove unused nolint statements

- go.mod
- go.sum
- pkg/golinters/goheader.go
This PR updates dependency on the go-header linter to [v0.4.1](https://github.com/denis-tingajkin/go-header/releases/tag/v0.4.1)
https://github.com/denis-tingajkin/go-header/compare/v0.3.1...v0.4.1
Signed-off-by: Denis Tingajkin <denis.tingajkin@xored.com>
> Bump go-header to v0.4.1

- .golangci.example.yml
- go.mod
- go.sum
Signed-off-by: Denis Tingajkin <denis.tingajkin@xored.com>
This PR updates dependency on the go-header linter to [v0.4.2](https://github.com/denis-tingajkin/go-header/releases/tag/v0.4.2)
https://github.com/denis-tingajkin/go-header/compare/v0.4.1...v0.4.2
> Bump go-header to v0.4.2

- pkg/config/config_gocritic.go
This PR performs additional gocritic settings validation. The `settings` attribute is supposed to be a map where each key is the name of a supported gocritic checker. 
The existing validation already warns if the config data contains a settings for a disabled checker. But it does not validate the checker is supported. There is also an existing validation that the specific parameter is supported or not.
For example, as shown in the yaml config data below, `ruleguard` is a supported gocritic checker, but `rangeValueCopy` is not (the actual checker is `rangeValCopy`).
```
gocritic:
settings:
rangeValueCopy:
sizeThreshold: 32
ruleguard:
rules: myrules.go
```
> Validate gocritic settings. Return error if settings includes a unsupported gocritic checker

- .golangci.example.yml
- .golangci.yml
- go.mod
- go.sum
- pkg/config/config.go
- pkg/golinters/predeclared.go
- pkg/lint/lintersdb/manager.go
- test/testdata/configs/predeclared.yml
- test/testdata/predeclared.go
- test/testdata/predeclared_custom.go
https://github.com/nishanths/predeclared
This adds the `predeclared` linter, which reports code that shadows one of [Go's predeclared identifiers](https://golang.org/ref/spec#Predeclared_identifiers).
> add 'predeclared' linter

- .golangci.example.yml
- go.mod
- go.sum
- pkg/lint/load.go
related to https://github.com/golang/go/issues/43418
Fixes #1502
Fixes #1633
Closes #1635 
related to #1592
> fix: modules-download-mode support

- go.mod
- go.sum
- test/linters_test.go
- test/testdata/fix/out/gofumpt.go
- test/testdata/gofumpt.go
- test/testdata/gofumpt_with_extra.go
diff: https://github.com/mvdan/gofumpt/compare/5c11c50e9475...v0.1.0
Because of https://github.com/mvdan/gofumpt/commit/bf2e7be4e31bb014f34658cc46df5e33e9b2870f, whitespace must be added between `//` and `args: ` for the gofumpt tests.
> Update mvdan.cc/gofumpt to v0.1.0 

- .golangci.example.yml
- pkg/config/config.go
- pkg/golinters/godot.go
This option already exists in godot linter. I just made it available in golangci-lint config.
> Add "exclude" option for godot linter

- go.mod
- go.sum
- test/testdata/rowserrcheck.go
Fixes #943
This PR fix that rowserrcheck reports false positive when handling `phi instruction`.
For example
```go
func badcase() {
var db *sql.DB
var rows *sql.Rows
if rand.Float64() < 0.5 {
rows, _ = db.Query("select 1")
}
if err := rows.Err(); err != nil {
panic(err)
}
}
```
which ssa is as below:
```
func badcase():
0:                                                                entry P:0 S:2
t0 = math/rand.Float64()                                        float64
t1 = t0 < 0.5:float64                                              bool
if t1 goto 1 else 2
1:                                                              if.then P:1 S:1
t2 = (*database/sql.DB).Query(nil:*database/sql.DB, "select 1":string, nil:[]interface{}...) (*database/sql.Rows, error)
t3 = extract t2 #0 …
```
> fix rowserrcheck reports false positive

- go.mod
- go.sum
- pkg/golinters/gocritic.go
This PR ensures that parsing errors of `ruleguard` input rules are caught; in that case, golangci-lint will print a human-friendly error message (include file name and line number) and exit with non-zero status. Without this PR, a verbose stack trace is printed.
The ruleguard checker makes it possible to write dynamic rules, which means the rules files may have syntax errors that need to be caught. When a ruleguard parsing error occurs, golangci-lint will print the following message and exit.
```bash
ERRO Running error: gocritic: gocritic checker 'ruleguard' initialization failed:
ruleguard init error: parse file error: rules.go:18:1: expected declaration, found FOO 
```
The actual error is raised when the `failOnError` flag is set to true in the golangci.yaml file, as explained in …
> Print error message and exit with non-zero status when ruleguard parse error occurs

- pkg/config/config.go
- pkg/golinters/ifshort.go
- pkg/lint/lintersdb/manager.go
the configuration is not linked to the linter flags.
> ifshort: add missing configuration.

- go.mod
- go.sum
- pkg/golinters/prealloc.go
The forked version of prealloc at github.com/golangci/prealloc has not
been kept up to date with the latest changes from the upstream
repository, github.com/alexkohler/prealloc. This takes advantage of a
recent refactor in the upstream to allow importing the logic directly as
a package, which allows golangci to remove the overhead of maintaining a
fork while effectively bumping the version of prealloc used.
Fixes #991
> Use upstream version of prealloc

- .goreleaser.yml
- build/Dockerfile
- build/Dockerfile.alpine
Hi there,
This just slightly improves builds reproducibility, the short description of the flag is bellow:
```
-trimpath
remove all file system paths from the resulting executable.
Instead of absolute file system paths, the recorded file names
will begin with either "go" (for the standard library),
or a module path@version (when using modules),
or a plain import path (when using GOPATH).
```
> Compile binaries with -trimpath enabled

- pkg/commands/help.go
For any linters that have a multiline description, displaying such as part of the `golangci-lint linters` output can be confusing, especially without colourised output on your terminal.
Fixes #1594.
> fix(cmd/linters): truncate multiline descriptions

- docs/src/docs/contributing/new-linters.mdx
This PR fix the reference to `govet` in contributing docs as linter that has one option. Not critical, just cleaning.
> Documentation on contributing

- docs/src/docs/usage/integrations.mdx
I'm writing a plugin for Goland to support `golangci-lint` inline, also providing possible quick fixes: https://github.com/xxpxxxxp/intellij-plugin-golangci-lint
Should be stable now, I'd like to suggest it as an option for Goland users.
Thank you all authors, `golangci-lint` is widely used in my org and improved code quality significantly.
> Add plugin option for Goland

- pkg/golinters/asciicheck.go
- pkg/lint/lintersdb/manager.go
- test/testdata/asciicheck.go
- test/testdata/exhaustivestruct.go
- test/testdata/exportloopref.go
- test/testdata/makezero.go
- test/testdata/makezero_always.go
Fixes #1515
I tested all the linters.
To avoid that in the future, every testdata for a linter must contain at least one import.
Before the fix:
```console
$ go run ./cmd/golangci-lint/ run --no-config --disable-all --enable=asciicheck ./test/testdata/depguard.go 
WARN [runner] Can't run linter asciicheck: asciicheck: analysis skipped: errors in package: [/home/ldez/sources/go/src/github.com/golangci/golangci-lint/test/testdata/depguard.go:6:2: could not import compress/gzip (Config.Importer.Import(compress/gzip) returned nil but no error) /home/ldez/sources/go/src/github.com/golangci/golangci-lint/test/testdata/depguard.go:7:2: could not import log (Config.Importer.Import(log) returned nil but no error)] 
ERRO Running error: asciicheck: analysis skipped: errors in package: …
```
> fix: wrong load mode

- .github/workflows/pr.yml
- .github/workflows/tag.yml
- Makefile
- build/Dockerfile
- build/Dockerfile.alpine
- go.sum
- test/testdata/govet.go
- test/testdata/sqlclosecheck.go
- drop go1.13
- add go1.16
We have to wait for the new alpine Docker image for go1.16 before merging the PR.
https://github.com/docker-library/official-images/pull/9639
Also, we will have to update the CI check requirements settings in GitHub
Fixes #1725
> Add go1.16 support

- .golangci.example.yml
- go.mod
- go.sum
- pkg/config/config.go
- pkg/golinters/cyclop.go
- pkg/lint/lintersdb/manager.go
- test/testdata/cyclop.go
https://github.com/bkielbasa/cyclop
> Add 'cyclop' linter 

- go.mod
- go.sum
- pkg/golinters/gocognit.go
- pkg/golinters/gocyclo.go
Gocyclo has been updated https://github.com/fzipp/gocyclo/commits/main
we don't need  a fork anymore https://github.com/golangci/gocyclo
> Use upstream gocyclo.

- pkg/config/config.go
- pkg/golinters/cyclop.go
- pkg/lint/lintersdb/manager.go
- test/testdata/cyclop.go
- test/testdata/gocyclo.go
> cyclop: add missing settings

- go.mod
- pkg/golinters/revive.go
- test/testdata/configs/revive.yml
Fixes #1745
The types are hardcoded, example: https://github.com/mgechev/revive/blob/389ba853b0b3587f0c3b71b5f0c61ea4e23928ec/rule/cognitive-complexity.go#L23
So to be able to get the expected types, the configuration will be marshaled to TOML and then the TOML will be unmarshaled to the expected configuration object.
> revive: fix types and default configuration.

- .golangci.example.yml
- pkg/config/config.go
- pkg/golinters/exhaustivestruct.go
- pkg/lint/lintersdb/manager.go
- test/testdata/exhaustivestruct_custom.go
related to https://github.com/golangci/golangci-lint/pull/1411#issuecomment-781308804
cc @sudo-suhas
> exhaustivestruct: add missing settings

- go.mod
- go.sum
- test/testdata/durationcheck.go
Related to https://github.com/charithe/durationcheck/issues/7
> durationcheck: False positive when multiplying with int type struct field

- .goreleaser.yml
Exclude PRs about doc dependencies from release changelog.
Example of the previous changelog: https://github.com/golangci/golangci-lint/releases/tag/v1.37.0
> Exclude PRs about doc dependencies from release changelog.

- docs/src/docs/usage/install/index.mdx
While use of the tap is discouraged, there are times that homebrew core doesn't immediately update the formula to the latest version. This provides docs on using the tap to help get the latest released quicker through brew.
An example of this is recently as brew install only installs v1.33 at the moment.
> Add docs on using homebrew tap

- go.mod
- go.sum
- test/testdata/goerr113.go
https://github.com/Djarvur/go-err113/compare/5174e21577d5...aea10b59be24
> Bump github.com/Djarvur/go-err113 to HEAD

- .golangci.example.yml
- pkg/golinters/govet.go
- pkg/lint/lintersdb/manager.go
- test/testdata/govet_fieldalignment.go
- test/testdata/maligned.go
Last week, [maligned has been deprecated](https://github.com/mdempsky/maligned).
The recommendation is to switch to https://pkg.go.dev/golang.org/x/tools/go/analysis/passes/fieldalignment
Related to #1555
Currently, we don't support `SuggestedFixes` but it's a more global topic.
> Deprecate maligned, add govet `fieldalignment` as replacement

- pkg/golinters/goanalysis/linter.go
Closes #1189
`RelatedInformation` is an experimental field from analysis `Diagnostic` structure.
https://github.com/golang/tools/blob/b4639ccb830b1c9602f1c96eba624bbbe20650ea/go/analysis/diagnostic.go#L30-L31
The implementation adds this information as a new issue.
According to my research, only Staticcheck uses this field.
```go
package example
func fn(x *byte) {
println(*x)
if x != nil {
return
}
}
```
Before:
```console
$ golangci-lint run
main.go:3:6: `fn` is unused (deadcode)
func fn(x *byte) {
^
main.go:4:10: SA5011: possible nil pointer dereference (staticcheck)
println(*x)
^
```
After:
```console
$ ./golangci-lint run
main.go:3:6: `fn` is unused (deadcode)
func fn(x *byte) {
^
main.go:4:10: SA5011: possible nil pointer dereference (staticcheck)
println(*x)
^
main.go:5:5: …
```
> Support RelatedInformation for analysis Diagnostic.

- docs/src/docs/usage/integrations.mdx
Updated existing `DEPRECATED` Sublime Text [plugin](https://github.com/alecthomas/SublimeLinter-contrib-golang-cilint) hyperlink  to new [SublimeLinter repo](https://github.com/SublimeLinter/SublimeLinter-golangcilint) location.
> Update deprecated hyperlink for Sublime Text plugin.

- go.mod
- go.sum
- pkg/golinters/ineffassign.go
- pkg/lint/lintersdb/manager.go
- test/run_test.go
- test/testdata/ineffassign.go
Use https://github.com/gordonklaus/ineffassign
Seems the author actively maintains the tool, the last change was committed today.
https://github.com/golangci/ineffassign
> Use upstream ineffassign instead of golangci fork

- .golangci.example.yml
There's a known behavior of YAML template blocks using `|` that they insert a trailing newline.
To remove it add `-` a.k.a block chomping indicator.
This would address some of the "weird" copyright header linting offenses that happen by following the example golangci-lint config by heart.
```
pkg/base64/service.go:13:34: Missed string: (goheader)
// limitations under the License.
^
pkg/hcl/test/testing.go:13:34: Missed string: (goheader)
// limitations under the License.
^
pkg/ini/service.go:13:34: Missed string: (goheader)
// limitations under the License.
^
```
> Fix go-header usage

- go.mod
- go.sum
Just an updating a reference in the go, mod file, the version is same.
There was a mistake in the tag names (no `v` prefix), that was fixed: https://github.com/jgautheron/goconst/issues/16
> Using a version instead of commit id for goconst

- .golangci.example.yml
- go.mod
- go.sum
- pkg/config/config.go
- pkg/golinters/importas.go
- pkg/lint/lintersdb/manager.go
- test/testdata/configs/importas.yml
- test/testdata/importas.go
https://github.com/julz/importas
Closes #1782
> Integrate ImportAs linter

- go.mod
- go.sum
- pkg/golinters/nilerr.go
- pkg/lint/lintersdb/manager.go
- test/testdata/nilerr.go
Finds the code that returns nil even if it checks that the error is not nil.
https://github.com/gostaticanalysis/nilerr
Related to  #1787
> Add nilerr linter.

- go.mod
- go.sum
- pkg/golinters/forcetypeassert.go
- pkg/lint/lintersdb/manager.go
- test/testdata/forcetypeassert.go
Finds forced type assertions.
https://github.com/gostaticanalysis/forcetypeassert
Related to  #1787
> Add ForceTypeAssert linter

- go.mod
- go.sum
* Use a tagged version of `prealloc` instead of commit ID. Version is same.
* Use a tagged version of `misspell` instead of commit ID. Version is same.
* Update `go-printf-func-name` to `v0.0.0-20200119135958-7558a9eaa5af`. Added license.
* Update `godox` to `v0.0.0-20210227103229-6504466cf951`. Changed error message by trimming a comment to 40 symbols only.
* Update `asciicheck` to `v0.0.0-20200416200610-e657995f937b`. Updated documentation.
* Update `wrapcheck` to `v0.0.0-20201130113247-1683564d9756`. Updated readme.
* Update `unparam` to `v0.0.0-20210104141923-aac4ce9116a7`. Updated dependencies.
> Update dependencies that dependabot cannot

- pkg/lint/lintersdb/manager.go
👋 As I saw, the correct link is https://github.com/fzipp/gocyclo, not https://github.com/alecthomas/gocyclo, but maybe I wrong.
https://github.com/golangci/golangci-lint/blob/5dcc3eafd1beece80cbab940b1130225e1cf6c68/go.mod#L20
https://github.com/golangci/golangci-lint/blob/5dcc3eafd1beece80cbab940b1130225e1cf6c68/pkg/golinters/gocyclo.go#L7
> docs: update url of gocyclo linter

- pkg/golinters/govet.go
https://github.com/golang/go/blob/5ff7ec98b7727b3641df25200345b1aa50b6ff35/src/cmd/vet/main.go#L39-L66
also add missing `framepointer`
> Use same default linter as go vet.

- go.mod
Change the go version in `go.mod` from `v1.13` to `v1.14`, since the tests for go `v1.13` were dropped in CI
> Use go v1.14 in go.mod file

- CHANGELOG.md
- README.md
- assets/github-action-config.json
- docs/template_data.state
> docs: Update for v1.38.0

- go.mod
- go.sum
https://github.com/dominikh/go-tools/compare/v0.1.2...2020.2.3
> Bump staticcheck to 2020.2.3 (v0.1.3)

- .golangci.yml
- go.sum
- pkg/golinters/gofmt_common.go
- pkg/lint/lintersdb/manager.go
- pkg/result/processors/fixer.go
- pkg/result/processors/path_prefixer_test.go
- test/run_test.go
- test/testdata/scopelint.go
https://github.com/kyoh86/scopelint#obsoleted
related to #1041
> Deprecate 'scopelint' linter

- .golangci.yml
- pkg/config/config_gocritic.go
- pkg/config/config_gocritic_test.go
- pkg/golinters/depguard.go
- pkg/golinters/goanalysis/adapters.go
- pkg/golinters/gochecknoglobals.go
- pkg/golinters/unparam.go
- pkg/result/processors/max_from_linter_test.go
- pkg/result/processors/processor_test.go
- scripts/expand_website_templates/main.go
- test/testdata/fix/in/gofumpt.go
- test/testdata/fix/out/gofumpt.go
- clean imports
- clean test imports
- clean configuration
> Clean configuration and code

- test/fix_test.go
- test/linters_test.go
Handle old TODO:
```go
// TODO: uncomment after deprecating go1.11
// assert.Equal(t, exitcodes.IssuesFound, exitErr.ExitCode())
```
Remove `assert` import alias on `github.com/stretchr/testify/require`:
```go
import (
assert "github.com/stretchr/testify/require"
)
```
> dev: remove old TODO and remove assert import alias on require.

- .golangci.example.yml
Adds two missing for mat options to the example config
> docs: adding missing format options

- pkg/golinters/nolintlint.go
- pkg/golinters/nolintlint/nolintlint.go
- pkg/golinters/nolintlint/nolintlint_test.go
- pkg/result/issue.go
- pkg/result/processors/nolint.go
- pkg/result/processors/nolint_test.go
- pkg/result/processors/testdata/nolint_unused.go
- test/testdata/fix/in/nolintlint.go
- test/testdata/fix/out/nolintlint.go
- test/testdata/nolintlint.go
This PR adds a fixing capability to nolintlint. It doesn't try to fix everything.
What it does (when --fix is enabled):
* Removes non-specific //nolint directives that are not used.
* Removes a linter from a linter-dispecific //nolint directive if that linter is not used for that line.
* Removes extra leading whitespace from //. nolint directives for any violations on the number of spaces.  We assume the intent was to have a single leading space unless `allow-leading-whitespace` is set to `false`, in which case we assume no leading spaces (i.e. `//nolint`).
What it does not do:
* Offer explanations when explanations for nolint are required but not provided. I suppose it could add a placeholder that the user could replace but that doesn't seem really in the spirit of how the fix option is …
> nolintlint: allow to fix //nolint lines

- pkg/lint/linter/config.go
- pkg/lint/lintersdb/manager.go
fixes #1810
It's not perfectly accurate but it feels like the best approach for me.
More details:
- https://github.com/golangci/golangci-lint/issues/1810#issuecomment-798887932
- https://github.com/golangci/golangci-lint/issues/1810#issuecomment-798944404
> Restore fast linters meaning

- pkg/golinters/revive.go
- test/testdata/configs/revive.yml
- test/testdata/revive_default.go
Fix #1770
https://github.com/golangci/golangci-lint/issues/1770#issuecomment-794887358
The code from revive:
```go
// GetConfig yields the configuration
func GetConfig(configPath string) (*lint.Config, error) {
config := defaultConfig()
if configPath != "" {
var err error
config, err = parseConfig(configPath)
if err != nil {
return nil, err
}
}
normalizeConfig(config)
return config, nil
}
```
The same thing in this PR:
```go
func getReviveConfig(cfg *config.ReviveSettings) (*lint.Config, error) {
conf := defaultConfig()
if !reflect.DeepEqual(cfg, &config.ReviveSettings{}) {
rawRoot := createConfigMap(cfg)
buf := bytes.NewBuffer(nil)
err := toml.NewEncoder(buf).Encode(rawRoot)
if err != nil {
return nil, err
}
conf = &lint.Config{}
_, err = toml.DecodeReader(buf, conf)
if err != nil { …
```
> revive: the default config is only applied when no dedicated config

- pkg/lint/linter/config.go
- pkg/lint/lintersdb/manager.go
I would like to add new presets:
- `import`
- `module`
- `comment`
- `metalinter`
- `test`
- `error`
- `sql`
<details>
|                    | `format` | `complexity` | `style` | `bugs` | `unused` | `performance` | PROPOSAL             |
|--------------------|:--------:|:------------:|:-------:|:------:|:--------:|:-------------:|----------------------|
| `deadcode`         |          |              |         |        |     ✔    |               |                      |
| `errcheck`         |          |              |         |    ✔   |          |               | `error`              |
| `gosimple`         |          |              |    ✔    |        |          |               |                      |
| `govet`            |          |              |         |    ✔   |          | …
> Add new presets

- pkg/golinters/forcetypeassert.go
- pkg/golinters/ineffassign.go
- pkg/golinters/makezero.go
- pkg/golinters/paralleltest.go
- pkg/golinters/unused.go
- pkg/lint/lintersdb/manager.go
- test/testdata/asciicheck.go
The `LoadMode` `LoadModeTypesInfo` in the `goanalysis.Linter` says that the linter needs to resolve all the types.
The `LoadMode` `WithLoadForGoAnalysis` in the `linter.Config` says that the linter needs more information about dependencies and sizes.
Each of these loading modes has an impact on how the linter can be executed, how the cache is used, and on the speed.
For example, if a linter uses the `LoadMode` `LoadModeTypesInfo` in the `goanalysis.Linter`, this linter will no be able to analyze a single file with elements not defined in that file.
Another example, the impact of the wrong load mode on the speed of `ineffassign`:
|        | real | user  | sys  |
|--------|------|-------|------|
| before | 2.88 | 12.71 | 1.28 |
| after  | 1.53 | 4.39  | 0.64 |
**The loading mode depends on …
> fix: wrong linters load mode

- pkg/commands/version.go
Default command output was set to Stderr, now set to Stdout.
Fixes #1868
> Set version command output to Stdout

- .github/workflows/pr.yml
- pkg/packages/util.go
- pkg/packages/util_test.go
> typecheck: improve error stack parsing.

- .golangci.example.yml
- go.mod
- go.sum
* Update importas version
* Diff: https://github.com/julz/importas/compare/d0bf5cb4e1db...a22c8f743dc9
* Add new feature's example to .golangci.example.yml
* importas supports regular expression now.
> Bump importas to HEAD

- README.md
This updates the GitHub release stats badge to point to a working link. https://somsubhra.com now hosts a very sketchy looking crypto blog. The original application is available at https://somsubhra.github.io/github-release-stats/.
> Fix release stats badge

- .golangci.example.yml
- go.mod
- go.sum
- pkg/config/config.go
- pkg/golinters/tagliatelle.go
- pkg/lint/lintersdb/manager.go
- test/testdata/tagliatelle.go
tagliatelle is a linter that handles struct tags.
for now, it only handle the string casing.
https://github.com/ldez/tagliatelle
> Add tagliatelle linter

- pkg/commands/run.go
- pkg/config/reader.go
- pkg/lint/runner.go
Fixes #665
to check the PR:
<details>
<summary>main.go</summary>
```go
package main
import (
"fmt"
)
func main() {
foo := "get"
bar := "get"
more := "get"
again := "get"
fmt.Println(foo+bar+more, again)
goo()
}
func goo() {
foo := "example"
bar := "example"
more := "example"
again := "example"
fmt.Println(foo+bar+more, again)
}
```
</details>
<details>
<summary>.golangci.yml</summary>
```yml
linters:
enable:
- goconst
issues:
exclude:
- string .get. has \d+ occurrences, make it a constant
```
</details>
before the PR:
```console
$ golangci-lint run
```
after the PR:
```console
$ ./golangci-lint run
main.go:19:9: string `example` has 4 occurrences, make it a constant (goconst)
foo := "example"
^
```
> fix: comma in exclude pattern leads to unexpected results

- .golangci.example.yml
- .nancy-ignore
- go.mod
- go.sum
- pkg/config/config.go
- pkg/golinters/wsl.go
* Allow forcing short declarations to cuddle only with themselves
* Allow a blank line after each comment group at the start of a block (not just between groups)
> Update wsl to 3.3.0, sort config in example config

- go.mod
- go.sum
Updates the wrapcheck linter to v1.2.0.
Changelog:
- Added `.Error` to the list of default ignore sigs due to tomarrell/wrapcheck#8
> Update wrapcheck to v1.2.0

- .golangci.example.yml
- go.sum
- pkg/config/linters_settings.go
- pkg/golinters/gosec.go
- pkg/lint/lintersdb/manager.go
- test/testdata/configs/gosec.yml
- test/testdata/gosec_rules_config.go
> gosec: add configuration

- .golangci.example.yml
- go.mod
- go.sum
- pkg/config/linters_settings.go
- pkg/golinters/wrapcheck.go
- pkg/lint/lintersdb/manager.go
Another wrapcheck update, this time with some configuration.
Recently added support to specify custom signatures to ignore when checking for wrapped errors making it more useful to people who want to use non-stdlib error wrapping.
Have given it a whirl, all looks good.
> Update Wrapcheck to v2, add configuration

- .github/workflows/pr.yml
- go.mod
- scripts/gen_github_action_config/go.mod
We will try to support only the latest two versions of Go to following the [release policy of Go](https://golang.org/doc/devel/release.html#policy)
Since the recommended way to install `golangci-lint` is to download and/or install a pre-built binary we see don't see a major problem with this.
Linked to #1925
> Set the minimum Go version to build the binary to go1.15

- go.mod
- go.sum
- pkg/golinters/govet.go
Default enabled: sigchanyzer
Default disabled: reflectvaluecompare, unusedwrite
https://github.com/golang/tools/compare/v0.1.0...master
> govet: Update vet passes

- pkg/config/issues.go
- pkg/golinters/revive.go
- test/testdata/configs/revive.yml
- test/testdata/revive.go
Fix #1937
The default behavior is still the same, but the PR allows users to use `exported` and `package-comments` rules.
> revive: convert hard coded excludes into default exclude patterns

- .golangci.example.yml
- go.mod
- go.sum
- pkg/config/linters_settings.go
- pkg/golinters/errorlint.go
- test/testdata/configs/errorlint_asserts.yml
- test/testdata/configs/errorlint_comparison.yml
- test/testdata/configs/errorlint_errorf.yml
- test/testdata/errorlint.go
- test/testdata/errorlint_asserts.go
- test/testdata/errorlint_comparison.go
- test/testdata/errorlint_errorf.go
https://github.com/polyfloyd/go-errorlint/compare/19bd8db6546f...74da32850375
This update is done by hand because dependabot is not able to update non-semver dependency.
> Update errorlint to HEAD

- .golangci.example.yml
- go.mod
- go.sum
- pkg/config/linters_settings.go
- pkg/golinters/importas.go
- test/testdata/configs/importas_strict.yml
- test/testdata/importas.go
- test/testdata/importas_strict.go
https://github.com/julz/importas/compare/a22c8f743dc9...841f0c0fe66d
Contains a breaking change in the importAs configuration.
This update is done by hand because dependabot is not able to update non-semver dependency.
> Update importAs to HEAD

- go.mod
- go.sum
- test/testdata/wastedassign.go
Hello.
This PR bump wastedassign to v1.0.0. 
The wording of the report has changed slightly in v1.0.0.
So, modified the test cases.
https://github.com/sanposhiho/wastedassign/compare/v0.2.0...v1.0.0
> Bump wastedassign to v1.0.0

- pkg/golinters/importas.go
- test/testdata/configs/importas_noalias.yml
- test/testdata/importas_noalias.go
I wanted to use the strict feature of importas, but forgot to also move my aliases under the `alias:` key, and couldn't figure out why they weren't being applied. This message would have saved me a couple hours debugging the code to find out I should have just read the docs more closely.
Initially I had it as a warning so it would show when running normally, but the tests (with --no-config) still created a default config for ImportAs, and so the output was flagged. An info message will be shown with --verbose, and should be sufficient, as that was the first thing I did to try to figure out if importas was getting filtered out for some reason.
> importas: add message if settings contain no aliases

- .golangci.example.yml
- pkg/config/linters_settings.go
- pkg/golinters/importas.go
- test/testdata/configs/importas.yml
- test/testdata/configs/importas_strict.yml
- test/testdata/importas.go
- test/testdata/importas_strict.go
As described in #1959, the standalone [importas](https://github.com/julz/importas) tool does not restrict an alias to a single package. This aligns our configuration with the standalone tool.
It is a breaking change, but another breaking change to this linter's configuration is waiting to be released in ffe80615b079a2cfe9b28e2d8323d58061b795d6.
> importas: allow repeated aliases

- CHANGELOG.md
- README.md
- assets/github-action-config.json
- docs/template_data.state
> docs: update for v1.40.0

- .golangci.example.yml
Minor fix, remove one tab character in the `.golangci.example.yaml` which breaks yaml parsing (in the case if .golangci.example.yaml used to automate `golangci-lint` testing).
> fix: example config yaml

- pkg/lint/runner.go
> runner: non-zero exit code when a linter produces a panic

- .golangci.example.yml
Comment add context on `struct-patterns` patterns, so it's not unexpected for users that patterns behave in next way:
1. e.g. `*.Text` can match struct Test if golangci-lint launched against the file
`golangcli-lint run example/example.go`
1. e.g. `*.Text` do not match struct Test if golangci-lint launched against package
`golangcli-lint run example`
> docs: exhaustivestruct example explanation

- .golangci.example.yml
The pattern of forbidigo in `.golangci.example.yaml` was not the correct pattern so I fixed.
It has been modified with reference to the original [usage](https://github.com/ashanbrown/forbidigo#usage).
`ginkgo\\.F.*` in the pattern before modification does not behave as expected.
> docs: fix pattern of forbidigo in example config yaml 

- .golangci.example.yml
- pkg/commands/executor.go
- pkg/golinters/revive.go
Fixes #2002
The root problem is the difference between the JSON parser and the YAML parser.
The YAML parser produces `map[interface{}]interface{}` but the JSON is not able to marshall `map` with a struct as a key.
And there is a second problem, the difference between the TOML parser and the YAML parser.
Revive uses "raw" map based on TOML parser, but it's not the same "raw" map as the YAML parser.
> revive: fix add-constant rule support.

- go.mod
- go.sum
https://github.com/jingyugao/rowserrcheck/releases/tag/v1.1.0
`d907ca737bb1` is hash of the tag `v1.1.0`
context: https://github.com/jingyugao/rowserrcheck/issues/22
This update is done by hand because dependabot is not able to update non-semver dependency.
> Update rowserrcheck to v1.1.0

- pkg/golinters/revive.go
Fixes #1993
<details>
<summary>example.go</summary>
```go
package main
import "fmt"
var HorribleGlobalVar = map[int]string{
1:    "s1",
2:    "s2",
3:    "s3",
2000: "s2000",
}
var (
GroupOfHorribleGlobalVar = map[int]string{
1:    "s1",
2:    "s2",
3:    "s3",
2000: "s2000",
}
)
type Foo struct {
S1 string
S2 string
S3 string
S4 string
S5 string
}
func Goo() {
to := "test"
fmt.Println(to)
}
```
</details>
<details>
<summary>.golangci.yml</summary>
```yml
linters:
enable:
- revive
issues:
exclude-use-default: false
```
</details>
<details>
<summary>before the PR</summary>
```console
$ golangci-lint run --disable-all -Erevive
main.go:5:5: exported: exported var HorribleGlobalVar should have comment or be unexported (revive)
var HorribleGlobalVar = map[int]string{
1: …
```
> revive: improve 'exported' rule output.

- pkg/config/issues.go
> revive: fix excludes

- .golangci.example.yml
- pkg/config/linters_settings.go
- pkg/golinters/gosimple.go
- pkg/golinters/staticcheck.go
- pkg/golinters/staticcheck_common.go
- pkg/golinters/stylecheck.go
- pkg/golinters/unused.go
Fixes #1275
Staticcheck is split into 4 linters in golangci-lint `staticcheck`, `gosimple`, `stylecheck` and `unused`.
(more information: https://github.com/golangci/golangci-lint/discussions/1989#discussioncomment-745004)
|                                       | `staticcheck` | `stylecheck` | `gosimple` | `unused` |
|---------------------------------------|---|---|---|---|
| `go`                                  | x | x | x | x |
| `checks` (*)                          | x | x | x | - |
| `dot-import-whitelist`  (ST1003)      | - | x | - | - |
| `initialisms` (ST1001)                | - | x | - | - |
| `http-status-code-whitelist` (ST1013) | - | x | - | - |
_(*)_: each `checks` section can only filter the rules related to this section:
- `checks` on `staticcheck` only filter `SAxxxx` …
> staticcheck: configuration for `staticcheck`, `gosimple`, `stylecheck`

- go.mod
- go.sum
- pkg/golinters/gomodguard.go
Gomodguard was saving issues to a global variable and when it was the process issues functioned returned results it would end up returning duplicates. This issue solves that by the process function returning only new issues found.
Also ensure we only configure and initialize gomodguard once by removing those steps from the `Run` func.
https://github.com/ryancurrah/gomodguard/compare/v1.2.0...v1.2.1
> gomodguard: fix problem where duplicate issues were being reported

- go.mod
- go.sum
- pkg/golinters/wastedassign.go
- test/testdata/wastedassign.go
Hello, team.
This PR bump wastedassign to v2.0.6. 
wastedassign supports the feature that reports with variable's name in v2. So, fixed test cases.
> Update wastedassign to v2.0.6

- go.mod
- go.sum
- pkg/golinters/staticcheck_common.go
- pkg/golinters/unused.go
https://staticcheck.io/changes/2021.1
https://github.com/dominikh/go-tools/compare/v0.1.4...v0.2.0
> build(deps): bump honnef.co/go/tools from v0.1.4 to v0.2.0

- pkg/golinters/nolintlint/nolintlint.go
- pkg/result/processors/nolint.go
- test/testdata_etc/unused_exported/main.go
the comments:
> // nolintlint generates potential issues for every nolint directive and they are filtered out here
> // nolintlint provides a linter to ensure that all //nolint directives are followed by explanations
produce false positives: `nolintlint`  is seen as `nolint` directive.
> nolintlint: fix false positive.

- .golangci.example.yml
- .golangci.yml
- docs/src/docs/usage/install/index.mdx
- pkg/commands/run.go
Fixes #1888
Closes #1686
Closes #1754
> doc: Un-deprecate enable-all option.

- go.mod
- go.sum
- pkg/config/linters_settings.go
- pkg/golinters/goconst.go
- test/testdata/goconst_dont_ignore_test.go
- test/testdata/goconst_ignore_test.go
- Updates goconst to v1.5.1.
- Plumbs IgnoreTests through from the backend, and tests new configuration.
https://github.com/jgautheron/goconst/compare/v1.4.0...v1.5.1
> Add IgnoreTests to goconst configuration.

- go.mod
- go.sum
Bump gomodguard because of bad checksum release, see ryancurrah/gomodguard#15
https://github.com/ryancurrah/gomodguard/compare/v1.2.1...v1.2.2
> Bump github.com/ryancurrah/gomodguard from 1.2.1 to 1.2.2

- pkg/config/issues.go
related to https://github.com/golangci/golangci-lint/pull/2005#discussion_r654075262
Details:
https://github.com/mgechev/revive/blob/8586baacbfaed0d70b319f1cdf2df91997b5fcdc/rule/exported.go#L196-L205
> revive: fix exclude comment rule for const block.

- pkg/config/linters_settings.go
- pkg/golinters/revive.go
> revive: add enable-all-rules.

- .golangci.example.yml
- pkg/config/linters_settings.go
- pkg/golinters/gofumpt.go
Without the Go language version input, `gofumpt` cannot apply some rules
which are version dependent.
Defaulting `lang-version` to the Go version of the running environment
if not specified.
Signed-off-by: Kailun Qin <kailun.qin@intel.com>
> gofumpt: Add lang-version option

- .goreleaser.yml
- go.mod
- go.sum
- update github.com/prometheus/procfs to v0.6.0
Closes  #2079
> Support RISV64

- pkg/result/processors/skip_dirs.go
- pkg/result/processors/skip_files.go
For every processor, there's a compile-time check for processors to check if they implement the `Processor` interface:
```
type Processor interface {
Process(issues []result.Issue) ([]result.Issue, error)
Name() string
Finish()
}
```
But there's a typo: `SkipFiles` is getting checked instead of `SkipDirs` 
Fix:
```
var _ Processor = (*SkipDirs)(nil)
```
(or)
```
var _ Processor = &SkipDirs
```
The former is more idiomatic; so I did that.
> dev: fix interface implement check for "SkipDirs"

- docs/src/docs/index.mdx
Currently more than 48 linter can be used with golangci-lint, so, the number of linters on docs is wrong.
It would be hard to change this number every time, maybe 🤔 
This PR changed to not show the number of linters.
> docs: not show the number of linters

- .golangci.example.yml
- .golangci.yml
- pkg/commands/run.go
- pkg/config/linters_settings.go
- pkg/golinters/errcheck.go
- test/testdata/errcheck/exclude_functions.yml
- test/testdata/errcheck_exclude_functions.go
One of the challenges in standardizing on a golangci-lint configuration is that if we want to configure `errcheck`, it requires two separate files to configure: the golangci config file, plus a separate errcheck excludes file.
In particular, copying golangci-lint configs across projects often fails, as a reference to an exclude file at a particular file will not resolve.
While this config does not add any new functionality, it allows the entirety of the errcheck configuration to be done inside the
golangci-lint config file itself.
https://github.com/kisielk/errcheck#excluding-functions
> errcheck: allow exclude config without extra file

- .golangci.example.yml
- pkg/golinters/goconst.go
> docs: improve goconst documentation.

- go.mod
- go.sum
- pkg/golinters/nilassign.go
- pkg/lint/lintersdb/manager.go
- test/testdata/nilassign.go
nilassign finds that assigning to invalid memory address or nil pointer dereference.
https://github.com/sivchari/nilassign
> add nilassign linter

- pkg/lint/lintersdb/validator.go
`golangci-lint linters` wont run when you have an unknown linter. `golangci-lint help linters` works.
> suggest golangci-lint help linters

- go.mod
- go.sum
https://github.com/dominikh/go-tools/compare/v0.2.0...v0.2.1
https://github.com/dominikh/go-tools/releases/tag/2021.1.1
> Bump staticcheck to 2021.1.1 (v0.2.1)

- .github/workflows/post-release.yml
- .github/workflows/pr.yml
- .github/workflows/tag.yml
The binaries for the releases should be built with Go1.17.
For now, the min Go version will stay on go1.15 but we will upgrade to go1.16 in few weeks.
> Update Go versions used by the CI

- docs/src/docs/usage/integrations.mdx
Noted the format of the target project `README.org` had changed - link within page was no longer valid. Have corrected.
> docs: fix link to `Spacemacs`

- Makefile
- build/Dockerfile
- build/Dockerfile.alpine
Move docker images onto go1.17 base images.
All base images were released https://github.com/docker-library/golang/pull/381
> Build docker images with go1.17

- pkg/golinters/gocritic.go
Fixes #2185
go-critic asserts that `CheckerParam.Value` has some specific types, but the file parsers (TOML, YAML, JSON) don't create the same and expected representation for raw type.
Then we have to convert value types into the expected value types.
Maybe in the future, this kind of conversion will be done in go-critic itself.
> go-critic: fix invalid type conversions.

- go.mod
- go.sum
This update removes some false positives wrt direct io.EOF comparison (https://github.com/polyfloyd/go-errorlint/pull/12, https://github.com/polyfloyd/go-errorlint/issues/13)
Changes: https://github.com/polyfloyd/go-errorlint/compare/ab96adb96fea..910bb7978349
> errcheck: update to HEAD

- pkg/golinters/gci.go
The gci command line parses the -local flag using the `gci.ParseLocalFlag` helper function,
which is different than `strings.Split` (which golangci-lint uses) in that it handles the empty string (which golangci-lint separately handles)
and that it handles empty entries in the list (which golangci-lint does not handle).
For example, the gci command line parses `"-local foo,,bar"` as the list `["foo", "bar"]`, but golangci-lint parses the YAML `"local-prefixes: foo,,bar"` as the list `["foo", "", "bar"]`.
This is a silly discrepancy to have; just use the `gci.ParseLocalFlag` helper function!
> gci: Parse the settings more similarly to the cli

- docs/src/docs/usage/install/index.mdx
> installing executables with 'go get' in module mode is deprecated.
So, we have to use `go install` on golang v1.16+
```
$ go get -u github.com/golangci/golangci-lint/cmd/golangci-lint@v1.42.1
go get: installing executables with 'go get' in module mode is deprecated.
Use 'go install pkg@version' instead.
For more information, see https://golang.org/doc/go-get-install-deprecation
or run 'go help get' or 'go help install'.
```
> docs: Update docs of installation with go

- .golangci.example.yml
- go.mod
- go.sum
- pkg/config/linters_settings.go
- pkg/golinters/ireturn.go
- pkg/lint/lintersdb/manager.go
- test/testdata/configs/ireturn.yml
- test/testdata/configs/ireturn_stdlib_reject.yml
- test/testdata/ireturn_allow.go
- test/testdata/ireturn_default.go
- test/testdata/ireturn_reject_stdlib.go
This PR introduces a new linter `ireturn` that checks for function's returned types and adds the possibility to reject or allow specific types of interfaces.
https://github.com/butuzov/ireturn
TL/DR
_Accept Interfaces, Return Concrete Types_
> new-linter: ireturn (checks for function return type)

- .golangci.example.yml
- go.mod
- go.sum
- pkg/config/linters_settings.go
- pkg/golinters/nilnil.go
- pkg/lint/lintersdb/manager.go
- test/testdata/nilnil.go
https://github.com/Antonboom/nilnil
> Add nilnil linter

- go.mod
- go.sum
- pkg/commands/run.go
- pkg/config/issues.go
- pkg/lint/runner.go
- pkg/result/processors/diff.go
This implements #2261 
It adds a flag called "whole-files" which changes the behavior of new-from-rev and new-from-patch so they report all issues in a file that has been changed, not just on the exact lines that have been updated.
Requires https://github.com/golangci/revgrep/pull/6. (and I'll need to update that import version after that PR is merged)
> add support for finding issues in entire files in a diff

- go.mod
- go.sum
As it's the first tagged version, we have to update the linter manually.
Fixes #1727
> Bump gochecknoglobals to v0.1.0

- .golangci.example.yml
nolintlint's allow-usued option comment is misleading: use of "enable" suggests that setting the value to true will ensure all directives are used. Further, it's unclear what "used" means in this context (it could be misread that every possible linter must be specified in at least one nolint directive).
> .golangci.example.yml: clarify nolintlint.allow-unused

- pkg/config/linters_settings_gocritic.go
Before this change, the message said "However, as this checkis disabled by default".
> fix: Add missing space in "disabled by config" warning

- .github/workflows/codeql.yaml
Remove executing build and test, there is a special workflow for this and CodeQL does not require running any go code or building the app
Remove `git checkout HEAD^2`, not needed anymore: Warning: 1 issue was detected with this workflow: git checkout HEAD^2 is no longer necessary. Please remove this step as Code Scanning recommends analyzing the merge commit for best results.
Add permission to write the security events
> codeql: Remove unneeded steps

- pkg/commands/help.go
- pkg/golinters/wsl.go
- pkg/printers/codeclimate.go
- pkg/result/processors/nolint.go
- pkg/timeutils/stopwatch.go
This PR refactors some slice declarations. It's better to preallocate memory when declaring a slice.
> preallocate slices

- .golangci.example.yml
- README.md
- docs/src/docs/index.mdx
- pkg/printers/github.go
The official spelling for "GitHub" is [GitHub](https://github.com/about) (with "H" uppercased).
The PR changes  "Github" to "GitHub" in the comments, README, docs, and example.yml.
> Change Github to GitHub in comments and docs

- .golangci.example.yml
Add examples for `gocritic` and `ruleguard` settings.
This documents the settings for `go-critic` which has been upgraded to `0.6.1`.
Depends on #2308
> Add documentation for go-critic and ruleguard settings

- go.mod
- go.sum
- pkg/golinters/bidichk.go
- pkg/lint/lintersdb/manager.go
- test/testdata/bidichk.go
[bidichk](https://github.com/breml/bidichk) checks for dangerous unicode character sequences
The following unicode characters are considered dangerous:
* U+202A: LEFT-TO-RIGHT-EMBEDDING
* U+202B: RIGHT-TO-LEFT-EMBEDDING
* U+202C: POP-DIRECTIONAL-FORMATTING
* U+202D: LEFT-TO-RIGHT-OVERRIDE
* U+202E: RIGHT-TO-LEFT-OVERRIDE
* U+2066: LEFT-TO-RIGHT-ISOLATE
* U+2067: RIGHT-TO-LEFT-ISOLATE
* U+2068: FIRST-STRONG-ISOLATE
* U+2069: POP-DIRECTIONAL-ISOLATE
See following links for background:
* ['Trojan Source' Bug Threatens the Security of All Code](https://krebsonsecurity.com/2021/11/trojan-source-bug-threatens-the-security-of-all-code/)
* [Trojan Source - Proofs-of-Concept](https://github.com/nickboucher/trojan-source)
* [Go proposal: disallow LTR/RTL characters in string …
> Add github.com/breml/bidichk linter

- .golangci.example.yml
- go.mod
- go.sum
- pkg/config/linters_settings.go
- pkg/golinters/exhaustive.go
- test/testdata/configs/exhaustive_checking_strategy_name.yml
- test/testdata/configs/exhaustive_checking_strategy_value.yml
- test/testdata/configs/exhaustive_ignore_enum_members.yml
- test/testdata/exhaustive_checking_strategy_name.go
- test/testdata/exhaustive_checking_strategy_value.go
- test/testdata/exhaustive_default.go
- test/testdata/exhaustive_ignore_enum_members.go
This makes the following changes to the `exhaustive` analyzer.
- Upgrade `github.com/nishanths/exhaustive` to latest tag. 
- Add support for new flags: `ignore-enum-members` and `checking-strategy`.
- Add tests for new flags.
- Deprecate flag `ignore-pattern`, which no longer has any effect (use `ignore-enum-members` instead).
As a side note, the `exhaustive` analzyer no longer provides any `[]analysis.SuggestedFix` in the diagnostics that it reports.
> exhaustive: upgrade to latest tag; add new flags and deprecate old ones

- .golangci.example.yml
- go.mod
- go.sum
- pkg/config/linters_settings.go
- pkg/golinters/bidichk.go
- pkg/lint/lintersdb/manager.go
Address proposal in https://github.com/golangci/golangci-lint/pull/2330#issuecomment-956738417
Make disallowed unicode runes configurable.
https://github.com/breml/bidichk/compare/v0.1.1...v0.2.0
> bump bidichk from v0.1.1 to v0.2.0

- docs/src/docs/contributing/architecture.mdx
Firstly, fixed a typo. Changed "user a user" to "a user".
Secondly, fixed a syntax error. Changed "depending from ..." to "depending on ...".
> docs: fix a typo and a syntax error in architecture.mdx

- .golangci.yml
- pkg/commands/run.go
- pkg/config/config.go
- pkg/golinters/gocritic.go
- pkg/lint/lintersdb/validator.go
- pkg/packages/errors.go
- pkg/timeutils/stopwatch.go
- test/bench/bench_test.go
- transforms one`//nolint` comment to an `exclude-rules` (less flaky)
- clean `.golangci.yml` (remove obsolete stuff, and change `gomnd` config)
- minor changes (slice init and godoc comment)
Note: I think that `nolintlint` have a concurrency/cache problem, it needs to be fixed in another PR.
> fix: reduce flaky in the CI and clean the .golangci.yml of the project

- pkg/printers/json.go
This makes the data more consistent and easier to use with other tools. For example, a third-party tool can iterate over `Issues` without having to make a preliminary null check.
Before:
```console
$ golangci-lint run --out-format=json | jq
{
"Issues": null,
"Report": {
"Linters": [...]
}
}
```
After:
```console
$ golangci-lint run --out-format=json | jq
{
"Issues": [],
"Report": {
"Linters": [...]
}
}
```
> Ensure that the Issues key in JSON format is a list

- .golangci.example.yml
* The default value for `allow-unused` is false
* https://github.com/golangci/golangci-lint/blob/ecbb9c475ffb689c0d7d35ed84e385c5d9905f5f/pkg/config/linters_settings.go#L49
> chore: fix wrong default value in comment

- .golangci.example.yml
- go.mod
- go.sum
- pkg/golinters/gocritic.go
- pkg/golinters/godot.go
https://github.com/blizzy78/varnamelen/compare/v0.4.0...v0.5.0
> bump varnamelen from v0.4.0 to v0.5.0

- .golangci.example.yml
- go.mod
- go.sum
- pkg/config/linters_settings.go
- pkg/golinters/errchkjson.go
- pkg/lint/lintersdb/manager.go
- test/testdata/configs/errchkjson.yml
- test/testdata/configs/errchkjson_check_error_free_encoding.yml
- test/testdata/configs/errchkjson_no_exported.yml
- test/testdata/errchkjson.go
- test/testdata/errchkjson_check_error_free_encoding.go
- test/testdata/errchkjson_no_exported.go
After the discussion on #2349, in particular in comment https://github.com/golangci/golangci-lint/pull/2349#discussion_r748742253, I decided to submit an alternative PR for the inclusion of _errchkjson_.
In this implementation there is by default no overlap with other linters (in particular _errcheck_ and _staticcheck_). By setting the respective configuration for _errchkjson_, the user can opt-in for the check for "error free json encoding". If the user decides to do so, it is recommended to exclude some functions from being checked by _errcheck_. The necessary instructions are provided to the user as comment in `.golangci.example.yml`.
closes #2349
> Add errchkjson linter

- .golangci.example.yml
- pkg/config/linters_settings.go
- pkg/golinters/wrapcheck.go
This provides an update to the `wrapcheck` linter configuration to account for a change introduced here - https://github.com/tomarrell/wrapcheck/pull/21
cc: @tomarrell
> Update wrapcheck configuration to include ignoreSignRegexps

- pkg/golinters/revive.go
Was broken by commit [e5450981](https://github.com/mgechev/revive/commit/e5450981) not being reflected in golangci-lint's copy of normalizeConfig().
> revive: fix enableAllRules

- pkg/config/linters_settings.go
- pkg/lint/lintersdb/manager.go
This change will help to :
- keep linters db in the consistent view
- keep new unmerged linters in conflict-free mode until merge time comes
(assuming new linters will be placed in the correct position, instead
settings to the end of the list)
> dev: sorting linters by alphabet (ascending order)

- install.sh
`uname_os` function in install.sh, which is from [client9/shlib](https://github.com/client9/shlib), behaved incorrectly in certain Windows environment.
The issue was fixed in https://github.com/client9/shlib/pull/23, so opening PR to apply the updated function body.
Fixes #1944
> fix: update uname_os from shlib in install.sh

- Makefile
- pkg/golinters/gocritic.go
- test/ruleguard/rangeExprCopy.go
- test/testdata/configs/gocritic.yml
- test/testdata/fix/in/gocritic.go
- test/testdata/fix/out/gocritic.go
PR for: https://github.com/go-critic/go-critic/issues/1179
> gocritic: support autofix

- .golangci.example.yml
- adds missing revive global configuration 
- adds detailed rules configuration
> doc: improve revive documentation

- test/fix_test.go
- test/testdata/configs/gocritic-fix.yml
- test/testdata/fix/in/gocritic.go
- test/testdata/fix/in/unused.go
- test/testdata/fix/out/gocritic.go
- test/testdata/fix/out/unused.go
- allows `config_path`
- removes `unused.go` (because it doesn't support autofix)
- check the exit code of the running command
> dev: improve and clean fix_test

- .golangci.example.yml
> docs: more revive examples

- .golangci.example.yml
- pkg/commands/run.go
- pkg/printers/checkstyle.go
- pkg/printers/codeclimate.go
- pkg/printers/github.go
- pkg/printers/html.go
- pkg/printers/json.go
- pkg/printers/junitxml.go
- pkg/printers/tab.go
- pkg/printers/text.go
- test/linters_test.go
- test/testshared/testshared.go
Outputs can be specified using `--out-format` by separating them by comma.
Support providing file path by separating format name and path by colon symbol `:`.
Fixes  #481
> Add support for multiple outputs

- pkg/printers/junitxml.go
Just adds the actual lint error text that is currently only in the `message` attribute, into the content of the `<failure>` tag.
Fixes #2452
> Print error text in <failure> tag content for more readable junit report

- pkg/result/processors/nolint.go
`regexp.MatchString` compiles regexp for every invocation,
there is no pattern caching there.
This change introduces a precompiled regexp to save some time
while checking comments for nolint directives.
Found using go-perfguard with cpu profile collected while
running golangci-lint on itself.
> pkg/result/processors: compile nolint regexp only once

- pkg/printers/checkstyle.go
- pkg/printers/checkstyle_test.go
- pkg/printers/codeclimate_test.go
- pkg/printers/html_test.go
- pkg/printers/json_test.go
- pkg/printers/junitxml.go
- pkg/printers/junitxml_test.go
- pkg/printers/tab_test.go
- pkg/printers/text_test.go
Add unit tests for all the printers.
> dev: add printers unit tests.

- pkg/config/linters_settings.go
- pkg/golinters/exhaustive.go
Both settings are no more used by `exhaustive` linter:
- `ignore-pattern`
- `checking-strategy`
See https://github.com/nishanths/exhaustive/blob/v0.7.11/exhaustive.go#L203-L205
> exhaustive: drop deprecated/unused settings

- .golangci.example.yml
- pkg/config/linters_settings.go
- pkg/golinters/godot.go
+ added ability to customize `period` setting
+ added default value for period (`true`)
+ update `.golangci.example.yml`
> godot: add period option

- pkg/lint/runner.go
If a linter fails, store its name and use that to create a list of all linters that failed to run.
This will make `golangci-lint` exit with a non-zero exit code if one or more linters fails but still ensure all linters are run before exiting.
Fixes #2357
> Return error if any linter fails to run

- go.mod
- go.sum
- test/testdata/configs/forbidigo.yml
- test/testdata/forbidigo_example.go
Also add example of custom messages
https://github.com/ashanbrown/forbidigo/compare/v1.2.0...v1.3.0
> Bump github.com/ashanbrown/forbidigo from 1.2.0 to 1.3.0

- go.mod
- go.sum
- test/testdata/makezero.go
Now includes support for multiple makes per line.
https://github.com/ashanbrown/makezero/compare/b6261585ddde...v1.1.0
> Bump makezero to v1.1.0

- .golangci.example.yml
- go.mod
- go.sum
- pkg/config/linters_settings.go
- pkg/golinters/maintidx.go
- pkg/lint/lintersdb/manager.go
- test/testdata/configs/maintidx_under_100.yml
- test/testdata/maintidx.go
- test/testdata/maintidx_under_100.go
maintidx measures the maintainability index of each function.
https://github.com/yagipy/maintidx
closes #2434
> Add maintidx linter

- .golangci.example.yml
- pkg/config/linters_settings.go
adds explicit default values 
(defined in varnamelen linter)
- `MaxDistance` (int:5)
- `MinNameLength` (int:3)
> varnamelen: explicit default values

- .golangci.example.yml
- .golangci.yml
- pkg/config/linters_settings.go
- pkg/golinters/gomnd.go
- pkg/lint/lintersdb/manager.go
I rewrote the `gomnd` configuration to be like the other linters configuration.
I added a compatibility section, so no breaking changes.
The old configuration and the new configuration cannot be used at the same time: if the old configuration is defined, only this configuration will be used.
> gomnd: new configuration

- go.mod
- go.sum
- pkg/golinters/containedctx.go
- pkg/lint/lintersdb/manager.go
- test/testdata/containedctx.go
containedctx is a linter that detects struct contained context.Context field
in detail, please check following link.
https://github.com/sivchari/containedctx
> add containedctx linter

- .golangci.example.yml
- go.mod
- go.sum
- pkg/config/linters_settings.go
- pkg/golinters/importas.go
Adds `no-extra-aliases` option to `importas` linter. (added in (https://github.com/julz/importas/commit/27e0a5d4dee270c88e73ce808fce24fad723ed30))
> importas: new option `no-extra-aliases`

- go.mod
- go.sum
Fixes #2222
We are moving to a pseudo version because @yeya24 don't respond to my request to create a release.
https://github.com/golangci/golangci-lint/issues/2222#issuecomment-933849943
https://github.com/yeya24/promlinter/compare/v0.1.0...d757024714a1857e3667c2aeed4f308476f485f9
> bump github.com/yeya24/promlinter from v0.1.0 to HEAD

- .golangci.example.yml
- removed `unused` settings (non-existing)
- fixed `promlinter` linter name (UnitAbbreviations)
- small refactoring on `default` values
- reordering
- added `varcheck`'s setting `exported-fields`
tl/dr: mostly cosmetic change.
> docs: improve linters settings section

- .golangci.yml
- docs/package-lock.json
- docs/src/docs/usage/configuration.mdx
- scripts/expand_website_templates/main.go
- scripts/expand_website_templates/main_test.go
Split the integration of `.golangci.example.yml` into multiple sections.
Switch the CLI section and the file section: put the file section first because it's the main use case.
<details>
<summary>before the PR</summary>
There is a small bug at the end of the capture (the black background disappears), but it's just a capture artifact. (the real current render [configuration](https://golangci-lint.run/usage/configuration/))
</details>
<details>
<summary>with the PR</summary>
</details>
> docs: split configuration page into multiple sections

- docs/src/docs/usage/false-positives.mdx
Add more examples and more clear sections.
> docs: improve page about false-positive

- go.mod
- go.sum
https://github.com/polyfloyd/go-errorlint/compare/910bb7978349...6d6d39c5bb8b
> errorlint: bump to HEAD

- go.mod
- go.sum
https://github.com/gordonklaus/ineffassign/compare/2e10b2664254...4cc7213b9bc8
> ineffassign: bump to HEAD

- go.mod
- go.sum
https://github.com/tdakkota/asciicheck/compare/e657995f937b...v0.1.1
As it's the first tagged version, we have to update the linter manually.
> asciicheck: bump to v0.1.1

- go.mod
- go.sum
https://github.com/gostaticanalysis/forcetypeassert/compare/01d4955beaa5...v0.1.0
As it's the first tagged version, we have to update the linter manually.
> forcetypeassert: bump to v0.1.0

- .golangci.example.yml
Still not perfect, but it's another step :wink:
> docs: improve configuration file content

- .golangci.example.yml
- go.mod
- go.sum
- pkg/config/linters_settings.go
- pkg/golinters/grouper.go
- pkg/lint/lintersdb/manager.go
https://github.com/leonklingele/grouper
> Add "grouper" linter

- .golangci.example.yml
This PR corrects yaml setting examples for revive rules that allow to disable them.
> docs(revive): fix typo on the option `disabled`

- CHANGELOG.md
```
/opt/build/repo/docs/src/docs/product/roadmap.mdx: unknown: Expected corresponding JSX closing tag for <failure>. (143:109)
```
https://app.netlify.com/sites/unruffled-torvalds-a209db/deploys/61eff7621e74d50008ffa558
> docs: fix misinterpreted XML tag in changelog

- pkg/config/linters_settings_gocritic.go
PR related to: https://github.com/go-critic/go-critic/issues/1199
now if we use debug mode for gocritic like this:
```
GL_DEBUG=gocritic golangci-lint run --config=.golangci.yml -v ./...
```
we get over ~136 repeated messages like this:
```
DEBU [gocritic] Disabled by config tags [experimental] checks (136): [appendAssign appendAssign appendCombine argOrder argOrder assignOp assignOp badCall badCall badCond badCond badLock badRegexp badSorting boolExprSimplify builtinShadow builtinShadowDecl captLocal captLocal caseOrder caseOrder codegenComment codegenComment commentFormatting commentFormatting commentedOutCode commentedOutImport defaultCaseOrder defaultCaseOrder deferInLoop deferUnlambda deprecatedComment deprecatedComment docStub dupArg dupArg dupBranchBody dupBranchBody dupCase …
```
> gocritic: fix debug output

- .golangci.example.yml
- .golangci.yml
- go.mod
- go.sum
- pkg/config/linters_settings.go
- pkg/golinters/gci.go
- pkg/golinters/gofmt_common.go
- pkg/golinters/ireturn.go
- pkg/lint/lintersdb/manager.go
- test/linters_test.go
- test/testdata/configs/gci.yml
- test/testdata/gci.go
- test/testdata/gci/gci.go
This PR adds support for the configurable section functionality that has been introduced to gci in daixiang0/gci#43
> bump github.com/daixiang0/gci from 0.2.9 to 0.3.0

- .golangci.example.yml
- go.mod
- go.sum
- pkg/config/linters_settings.go
- pkg/golinters/revive.go
https://github.com/mgechev/revive/compare/8aab7c6...v1.1.4
Fixes #2575
related to https://github.com/mgechev/revive/issues/634#issuecomment-1040881748
This update is performed by hand because of the rewrite of v1.1.3 tag and the change related to that.
> bump github.com/mgechev/revive from v1.1.3 to v1.1.4

- scripts/expand_website_templates/main.go
Add a link (⚙️) to the linter configuration in the list of "Enabled By Default Linters" and "Disabled By Default Linters".
<details>
<summary>before the PR</summary>
</details>
It can be tested here: https://deploy-preview-2587--unruffled-torvalds-a209db.netlify.app/usage/linters/
> docs: add link to configuration in the linters list

- pkg/config/linters_settings.go
Fixes #2588
- :bug: restore default for sections setting of gci linter
> gci: restore defaults for sections

- go.mod
- go.sum
- pkg/lint/lintersdb/manager.go
https://github.com/daixiang0/gci/compare/v0.3.0...76d765e3ab48
Fixes #2592
> bump github.com/daixiang0/gci to HEAD

- .golangci.example.yml
Add an example of a recently-added forbidigo feature, comments (https://github.com/ashanbrown/forbidigo/pull/11).
Is the docs site (https://golangci-lint.run/usage/linters/#forbidigo) generated from this file?
> forbidigo: add example that uses comments

- .golangci.example.yml
- pkg/config/linters_settings.go
- pkg/golinters/errcheck.go
> errcheck: add an option to remove default exclusions

- go.mod
- go.sum
- pkg/golinters/revive.go
Since v1.44.1, the default values are not applied in the same way as before (#2576), so we have to enforce the default values.
Also `dots.ResolvePackages(files, []string{})` is useless and can produce bugs because we don't have patterns but absolute paths to files.
When you give absolutes paths to `dots.ResolvePackages`, each file is seen as a package, but revive expects files grouped by package.
Fixes #2610
> revive: fix default values

- go.mod
- go.sum
- pkg/golinters/goheader.go
- pkg/lint/lintersdb/manager.go
- test/testdata/go-header_bad.go
- test/testdata/go-header_good.go
https://github.com/denis-tingaikin/go-header/compare/v0.4.2...v0.4.3
**This update is done by hand because the module name has changed.**
Related to #2549
Changing directive style comments to simple comments seems to remove the flaky behavior on go-header tests.
Fixes #2613
> bump github.com/denis-tingaikin/go-header from 0.4.2 to 0.4.3

- .golangci.example.yml
- docs/src/docs/usage/linters.mdx
- add missing revive configuration
- use better section titles
> docs: improve linters page

- pkg/config/reader.go
With this, it is possible to use process substitution so that there's no need to frequently download new rules.
```bash
golangci-lint run -c <(curl https://some-site.com/golangci-rules.yaml)
```
> Default to YAML when config file has no extension

- .golangci.example.yml
- pkg/config/linters_settings.go
- pkg/golinters/gofumpt.go
`gofumpt` v0.3.0 changed how imports are arranged, and added a `ModulePath` configuration option to control that behavior. Imports with the defined module path are no longer grouped with the standard library (https://github.com/mvdan/gofumpt/commit/487b40bce0289dc24fad95233b57828a4cd56943)
When using the `gofumpt` binary, it will actually exec out to the `go` binary in an attempt to get the module path from the `go.mod` file: https://github.com/mvdan/gofumpt/blob/master/gofmt.go#L289
This causes a conflict between the two formatters as the `gofumpt` binary will be clever and find the module path, but `golangci-lint` (currently) has no way of specifying this value.
> Add module-path setting to gofumpt

- pkg/lint/lintersdb/manager.go
https://github.com/golangci/golangci-lint/issues/2649#issuecomment-1072903206
> fix: disable structcheck with go1.18

- pkg/golinters/depguard.go
- pkg/golinters/goanalysis/adapters.go
- pkg/lint/lintersdb/manager.go
> depguard: reduce requirements

- .golangci.example.yml
- .golangci.yml
- pkg/commands/executor.go
- pkg/commands/run.go
- pkg/config/config.go
- pkg/config/linters_settings.go
- pkg/golinters/govet.go
- pkg/lint/linter/config.go
- pkg/lint/linter/linter.go
- pkg/lint/lintersdb/manager.go
- test/fix_test.go
- test/linters_test.go
- test/testshared/testshared.go
The Go version will be detected from the `go.mod` file.
The autodetection can be overridden by defining the configuration option.
golangci-lint will use, in order:
- the Go version defined by the CLI flag, ex: `--go=1.18`
- then the Go version defined in the configuration file, ex:
```
run:
go: '1.18'
```
- the Go version defined in the `go.mod`, ex;
```
module github.com/org/my-project
go 1.18
```
- the Go version defined by the env var `GOVERSION`
- fallback on go1.17.
- The govet analyzers `nilness` and `unusedwrite` will be inactivated when using go1.18
- `interfacer` will be inactivated with go1.18
Related to #2649
> feat: automatic Go version detection

- go.mod
- go.sum
https://github.com/blizzy78/varnamelen/compare/v0.6.1...v0.6.2
This fixes #2683 and blizzy78/varnamelen#13 by retracting varnamelen v0.6.1. There were no changes in functionality.
> bump varnamelen from v0.6.1 to v0.6.2

- .golangci.example.yml
- go.mod
- go.sum
- pkg/config/linters_settings.go
- pkg/golinters/varnamelen.go
https://github.com/blizzy78/varnamelen/compare/v0.6.2...v0.8.0
This supersedes #2692. This PR also includes new configuration.
> bump varnamelen from v0.6.2 to v0.8.0

- docs/src/docs/usage/faq.mdx
Updates supported Go versions section.
> docs: update FAQ page.

- .github/workflows/pr.yml
- .golangci.yml
- use go1.18 to test the previous version of golangci-lint
- update gomnd configuration
> dev: remove some TODO

- pkg/lint/lintersdb/manager.go
As of honnef.co/go/tools@v0.3.0, `staticcheck` supports Go 1.18 and generics.
The dependency was bumped here by dependabot in golangci/golangci-lint#2738, but the no-op fallback configs needed to be removed.
See also golangci/golangci-lint#2649 for overall Go 1.18/generics support progress.
> staticcheck: re-enable for go1.18

- pkg/logutils/stderr_log.go
some CI runners does not support TTY, like gitlab runner.
related issue https://gitlab.com/gitlab-org/gitlab-runner/-/issues/2115
https://gitlab.com/gitlab-org/gitlab/-/issues/28598
even with `golangci-lint run -v --color always`, we can not make **the log level** support color.
with this option, one can set env var `CLICOLOR_FORCE=1` to skip the tty check and print colored log level.
and set env var `CLICOLOR_FORCE=0` and  `CLICOLOR=0` to disable colored log level.
see https://github.com/sirupsen/logrus/blob/85981c045988a3ebe607e2f5b8a6499d86e0ddac/text_formatter.go#L120
> feat: enable override coloring based on CLICOLOR and CLICOLOR_FORCE

- test/fix_test.go
- test/linters_test.go
- test/testdata/tenv_go118.go
Skip linter tests about go1.18 when using go1.17.
Allows using go1.17 and go1.18 in CI.
> dev: support build tags about go version in linter tests

- go.mod
- go.sum
- pkg/config/linters_settings.go
- pkg/golinters/thelper.go
- test/testdata/thelper_go118.go
In this release, I've added fuzzing test support.
https://github.com/kulti/thelper/compare/v0.5.1...v0.6.2
> bump github.com/kulti/thelper from 0.5.1 to 0.6.2

- .golangci.example.yml
- go.mod
- go.sum
- pkg/config/linters_settings.go
- pkg/golinters/commons.go
- pkg/golinters/exhaustruct.go
- pkg/lint/lintersdb/manager.go
- test/testdata/configs/exhaustivestruct.yml
- test/testdata/configs/exhaustruct.yml
- test/testdata/exhaustivestruct.go
- test/testdata/exhaustivestruct_custom.go
- test/testdata/exhaustruct.go
- test/testdata/exhaustruct_custom.go
[This linter](https://github.com/GaijinEntertainment/go-exhaustruct) can be called a successor of [exhaustivestruct](https://github.com/mbilski/exhaustivestruct), and:
- it is at least **2.5+ times faster**, due to better algorithm;
- can receive `include` and/or `exclude` patterns;
- expects received patterns to be RegExp, therefore this package is not api-compatible with `exhaustivestruct`.
Also: deprecate `exhaustivestruct` linter
> feat: add `exhaustruct` linter

- docs/src/docs/usage/integrations.mdx
When I tried to enable shell autocompletion reading the website, noticed the content on kubernetes.io had been moved. After some playing, I also noticed the `golangci-lint completion $SHELL --help` command exists and it has a straightforward instruction.
This replaces that link with the command above. I'm open to update the link to https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#enable-shell-autocompletion, which is the new location of kubectl's instruction, if you'd like.
(I haven't removed the macOS's instruction in case it's still useful.)
> docs: update "Shell Completion" instruction on Linux

- .golangci.example.yml
I forgot to add the linter to the list of available linters, so I added it.
> docs: add containedctx linter to the list of available linters

- .golangci.reference.yml
- docs/src/docs/contributing/faq.mdx
- docs/src/docs/contributing/new-linters.mdx
- docs/src/docs/contributing/workflow.mdx
- docs/src/docs/usage/configuration.mdx
- scripts/expand_website_templates/main.go
- scripts/expand_website_templates/main_test.go
The name of this file leads many people to think that this file is a configuration example.
This file is a configuration reference: it contains the exhaustive configuration with explanations of the options.
This is not a configuration example.
> docs: rename .golangci.example.yml to .golangci.reference.yml

- go.mod
- go.sum
https://github.com/polyfloyd/go-errorlint/compare/6d6d39c5bb8b...v1.0.0
As it's the first tagged version, we have to update the linter manually.
> bump github.com/polyfloyd/go-errorlint to v1.0.0

- pkg/config/linters_settings.go
- pkg/golinters/thelper.go
- test/testdata/configs/thelper.yml
- test/testdata/thelper_with_options.go
Fixes #2848
Note:
Currently, `thelper` doesn't work on projects that use go1.17 even if golangci-lint is compiled with go1.18.
To fix this behavior the PR https://github.com/kulti/thelper/pull/38 must be merged.
ping @kulti
> thelper: allow to disable one option

- .golangci.reference.yml
Add missing defaults for all linters to `.golangci.reference.yml`
> docs(linters): add defaults

- .golangci.reference.yml
Add missing settings for `govet`'s `shadow` and `unusedresult` to `.golangci.reference.yml`
See:
https://github.com/golang/tools/blob/0e859afa53b25f6b14b7c4cc7db2ac7ce9d29f06/go/analysis/passes/printf/printf.go#L32
https://github.com/golang/tools/blob/0e859afa53b25f6b14b7c4cc7db2ac7ce9d29f06/go/analysis/passes/shadow/shadow.go#L57
https://github.com/golang/tools/blob/0e859afa53b25f6b14b7c4cc7db2ac7ce9d29f06/go/analysis/passes/unusedresult/unusedresult.go#L48
> docs(govet): add settings for `shadow` and `unusedresult`

- .golangci.reference.yml
Add missing `fuzz` config of `thelper` to `.golangci.reference.yml`
See:
https://github.com/golangci/golangci-lint/blob/d92f144dffd4007253b4bbce4483da6178dd39db/pkg/config/linters_settings.go#L554
> docs(thelper): add `fuzz` config and description

- .golangci.reference.yml
Add configs for all existing `gosec` rules to `.golangci.reference.yml`.
See:
https://github.com/securego/gosec/blob/12be14859bc7d4b956b71bef0b443694aa519d8a/rules/hardcoded_credentials.go#L127
https://github.com/securego/gosec/blob/12be14859bc7d4b956b71bef0b443694aa519d8a/rules/hardcoded_credentials.go#L132
https://github.com/securego/gosec/blob/12be14859bc7d4b956b71bef0b443694aa519d8a/rules/hardcoded_credentials.go#L137
https://github.com/securego/gosec/blob/12be14859bc7d4b956b71bef0b443694aa519d8a/rules/hardcoded_credentials.go#L144
https://github.com/securego/gosec/blob/12be14859bc7d4b956b71bef0b443694aa519d8a/rules/hardcoded_credentials.go#L151
https://github.com/securego/gosec/blob/12be14859bc7d4b956b71bef0b443694aa519d8a/rules/errors.go#L93 …
> docs(gosec): add configs for all existing rules

- .golangci.reference.yml
Add missing `ignore-file-rules` config for `depguard` to `.golangci.reference.yml`.
> docs(depguard): add `ignore-file-rules`

- .golangci.reference.yml
Add missing `enable` and `disable` settings of `ruleguard` to `.golangci.reference.yml`.
See:
https://github.com/go-critic/go-critic/blob/498eef8a04d52f25a7f3718211a46a55e0ae73f0/checkers/ruleguard_checker.go#L45-L52
> docs(gocritic): add `enable` and `disable` ruleguard settings

- pkg/golinters/staticcheck.go
https://twitter.com/dominikhonnef/status/1531408515658547200
In the future, we will change the name to avoid confusion between the direct use of staticcheck and the integration inside golangci-lint.
> docs: have a clear explanation about the staticcheck integration.

- docs/src/config/sidebar.yml
- docs/src/docs/product/roadmap.mdx
- docs/src/docs/product/thanks.mdx
- scripts/expand_website_templates/main.go
Golangi-lint is a wrapper around linters, so I think it's a good idea to have a dedicated page to promote linter authors.
- move the Thanks section to a dedicated page
- add authors from Gitlab
- use the sponsor link (GitHub only)
<details>
</details>
> docs: add thanks page

- .golangci.reference.yml
See https://github.com/tommy-muehle/go-mnd/blob/10a50fc5abd6e8e49a713d0a96838d2d56eb54f2/config/config.go#L30
> docs(gomnd): fix typo

- .golangci.reference.yml
- pkg/golinters/gosec.go
> gosec: allow `global` config

- .golangci.reference.yml
- .golangci.yml
- pkg/config/linters_settings.go
- pkg/golinters/staticcheck.go
- pkg/golinters/staticcheck_common.go
- pkg/lint/lintersdb/manager.go
> config: spread go version on linter's configurations

- .golangci.yml
- pkg/golinters/depguard.go
- test/testdata/depguard.go
- test/testdata/depguard_additional_guards.go
Replaces `whitelist` and `blacklist` with `allowlist` and `blacklist` for depguard
> depguard: adjust phrasing

- go.mod
- go.sum
- pkg/golinters/nosnakecase.go
- pkg/lint/lintersdb/manager.go
- test/run_test.go
- test/testdata/nosnakecase.go
nosnakecase is a linter that detects snake case of variable naming and function name.
https://github.com/sivchari/nosnakecase
> add nosnakecase lint

- pkg/commands/cache.go
Added condition when err is nil and and file not dir instead of err handling, cuz err variable returned anyway. 
Changed operator for size variable. Because need assign only.
> dev: change err to nil

- pkg/golinters/goanalysis/runner_loadingpackage.go
- pkg/golinters/goanalysis/runner_loadingpackage_ti.go
- pkg/golinters/goanalysis/runner_loadingpackage_ti_go117.go
For staticcheck to work, `go/types.Info.Instances` must be populated. `go/types` will automatically populate the map as long as it's not nil, so the only change that has to be made is initializing that map.
Updates #2649
Closes #2859
> staticcheck: fix generics

- .golangci.reference.yml
- go.mod
- go.sum
- pkg/config/linters_settings.go
- pkg/golinters/asasalint.go
- pkg/lint/lintersdb/manager.go
- test/testdata/asasalint.go
the linter [asasalint](https://github.com/alingse/asasalint) aim to lint bug about `pass []any as any in variadic function` 
i have check some top go repos in github, and the found bugs list in the issues: https://github.com/alingse/asasalint/issues/1
and more failed in check on [github actions](https://github.com/alingse/asasalint/actions?query=is%3Afailure) (some is not the bug) 
the linter may wrong report some not bug lint,  
user can add `exclude` to avoid some wrong report
> Add linter `asasalint` to lint pass []any as any

- go.mod
- pkg/golinters/gci.go
`gci.DiffFormattedFilesToArray` uses `gci.processStdInAndGoFilesInPaths` that uses `io.StdInGenerator` but `stdin` is not active on CI.
https://github.com/daixiang0/gci/blob/6f5cb16718ba07f0342a58de9b830ec5a6d58790/pkg/gci/gci.go#L63-L75
https://github.com/daixiang0/gci/blob/6f5cb16718ba07f0342a58de9b830ec5a6d58790/pkg/gci/gci.go#L80
Fixes #2982
> gci: remove the use of stdin

- pkg/golinters/gci.go
- test/testdata/gci.go
While running the golangci-lint I got findings of the type: 
```
api/v1beta1/condition_types.go:93: File is not `gci`-ed with -skip-generated -s standard,default (gci)
```
However if you run `gci` with the provided output you will get the following error message:
```
./dist/gci write -skip-generated -s default main.go 
Error: invalid params: kip-generated
```
The correct format is `--skip-generated`. 
```
./dist/gci write --help
(...)
-s, --section strings   Sections define how inputs will be processed. Section names are case-insensitive and may contain parameters in (). The section order is standard > default > custom. The default value is [standard,default].
standard - standard section that Golang provides officially, like "fmt"
Prefix(github.com/daixiang0) - custom section, groups all …
```
> gci: fix options display

- .golangci.reference.yml
- go.mod
- go.sum
- pkg/lint/lintersdb/manager.go
Related to #2649 and #2976
- update `golang.org/x/tools`
- update `mvdan.cc/unparam`
- re-enable linters related to SSA
> fix: generics

- pkg/lint/lintersdb/manager.go
structcheck is still not able to manage generics
> fix: disable structcheck for go >= 1.18

- pkg/lint/lintersdb/manager.go
> Revert 'fix: generics (#2991)'

- CHANGELOG.md
- pkg/golinters/revive.go
Related to #2997
https://github.com/golangci/golangci-lint/issues/2997#issuecomment-1190681977
> revive: ignore slow rules

- pkg/golinters/govet.go
- pkg/lint/lintersdb/manager.go
Remove go1.18 limitations for:
- govet(nilness,unusedwrite)
- bodyclose
- contextcheck
- nilerr
- noctx
- tparallel
- unparam
Remove `structcheck` from the default linters.
Related to #2649
> feat: remove some go1.18 limitations

- .golangci.reference.yml
- go.mod
- go.sum
see this false positive issue https://github.com/alingse/asasalint/issues/17
https://github.com/alingse/asasalint/compare/v0.0.10...v0.0.11
> build(deps): bump github.com/alingse/asasalint from 0.0.10 to 0.0.11

- pkg/commands/cache.go
- pkg/commands/config.go
- pkg/commands/help.go
- pkg/commands/linters.go
- pkg/commands/root.go
- pkg/commands/run.go
- pkg/commands/version.go
For commands consistency.
EDIT(ldez): I rewrote some commands to be more idiomatic and consistent.
> dev: clean commands

- docs/src/docs/product/trusted-by.mdx
We at Bytebase are using golangci-lint extensively :smile::
https://github.com/bytebase/bytebase/blob/main/.golangci.yaml
We run golangci-lint for every commit in Github Actions:
https://github.com/bytebase/bytebase/blob/main/.github/workflows/tests.yml#L11-L31
We occasionally review the [linters page](https://golangci-lint.run/usage/linters/) to find new linters.
For example, in this PR we use all the revive linter checks by default and found a lot of warnings. So we split them up and will enable one linter at a time in a separate PR:
https://github.com/bytebase/bytebase/pull/1928
> doc: add Bytebase info the trusted-by page

- pkg/golinters/dupl.go
- pkg/golinters/gci.go
- pkg/golinters/gofmt.go
- pkg/golinters/gofumpt.go
- pkg/golinters/goimports.go
- pkg/golinters/gomodguard.go
- pkg/golinters/lll.go
- pkg/golinters/misspell.go
- pkg/golinters/revive.go
- pkg/golinters/util.go
- pkg/golinters/wsl.go
- test/run_test.go
- test/testdata/cgo_with_issues/main.go
This change fixes a bug that caused that many linters ignored all files that are using Cgo. It was introduced by PR #1065, which assumed that all files referenced by `//line` directives are non-Go files, which is not true. In the case of Cgo they point to the original Go files which are used by Cgo as templates to generate other Go files.
The fix replaces all calls of `Pass.Fset.PositionFor` with a function `getFileNames()` that first calls `Pass.Fset.PositionFor` with adjustment, and only if it results in a non-Go file it calls `Pass.Fset.PositionFor` again without adjustment.
Fixes #1392
Fixes #2449
Fixes #2612
Fixes #2788
Fixes #2910
Signed-off-by: Sven Anderson <sven@anderson.de>
> cgo: fix many linters ignoring Cgo files

- .golangci.yml
- docs/src/docs/usage/false-positives.mdx
- pkg/config/linters_settings.go
- pkg/golinters/godot.go
- pkg/golinters/importas.go
- pkg/golinters/nolintlint.go
- pkg/golinters/nolintlint/README.md
- pkg/golinters/nolintlint/nolintlint.go
- pkg/golinters/nolintlint/nolintlint_test.go
- pkg/golinters/staticcheck_common.go
- pkg/result/processors/base_rule.go
- pkg/result/processors/nolint.go
- pkg/result/processors/testdata/autogen_exclude_doc.go
- pkg/result/processors/testdata/nolint.go
- pkg/result/processors/testdata/nolint_bad_names.go
- pkg/result/processors/testdata/nolint_unused.go
- scripts/expand_website_templates/main.go
- test/testdata/default_exclude.go
- test/testdata/fix/in/nolintlint.go
- test/testdata/gomodguard.go
- test/testdata/nolintlint_unused.go
- tools/tools.go
It's a part of the road to go1.19.
https://github.com/golangci/golangci-lint/issues/1658#issuecomment-1183148066
Drop `allow-leading-space` option and add the support of `nolint:all`.
This PR doesn't break the previous syntaxes.
It will not be the real fix for issue #1658 but a fix for go1.19 gofmt.
In parallel, I started to work on a real fix for the issue with a new syntax.
> nolint: drop allow-leading-space option and add "nolint:all"

- docs/src/docs/usage/install/index.mdx
v1.47.3 no longer builds with 1.15 or 1.16, so remove related install instructions.
> docs(install): remove outdated info on source install

- .github/workflows/post-release.yml
- .github/workflows/pr-extra.yml
- .github/workflows/pr.yml
- .github/workflows/tag.yml
Since actions/setup-go v3 `stable` parameter is no longer required
(see https://github.com/actions/setup-go/releases/tag/v3.0.0).
> dev: remove stable from actions/setup-go

- go.mod
- go.sum
Fixes #972
https://github.com/golangci/revgrep/compare/c22e5001d4f2...745bb2f7c2e6
> build(deps): bump revgrep to HEAD

- go.mod
- go.sum
https://github.com/kisielk/errcheck/compare/v1.6.1...v1.6.2
**In order to be able to create a release quickly for go1.19, the update is done manually**
> build(deps): bump github.com/kisielk/errcheck from 1.6.1 to 1.6.2

- go.mod
- go.sum
https://github.com/daixiang0/gci/compare/v0.6.0...v0.6.2
**In order to be able to create a release quickly for go1.19, the update is done manually**
> build(deps): bump github.com/daixiang0/gci from 0.6.0 to 0.6.2

- pkg/commands/root.go
> fix: exit early on run --version

- .golangci.reference.yml
- .golangci.yml
- test/testdata/fix/in/nolintlint.go
- test/testdata/fix/out/nolintlint.go
- test/testdata/nolintlint.go
The option `allow-leading-space` has been removed in #3002
These changes were to be made after the v1.48.0 release.
> docs: remove allow-leading-space option

- .golangci.reference.yml
- docs/src/docs/contributing/workflow.mdx
- docs/src/docs/usage/false-positives.mdx
- pkg/config/issues.go
- scripts/expand_website_templates/main.go
- add a section about default exclusions
- add the list of exclusion codes to the reference 
<details>
<summary>preview</summary>
</details>
> docs: add a section about default exclusions

- test/output_test.go
When a new linter is added, the output changes, so we cannot match the full report.
We have to focus on the `Issues` section.
> dev: fix output tests

- .golangci.reference.yml
- go.mod
- go.sum
- pkg/config/linters_settings.go
- pkg/golinters/interfacebloat.go
- pkg/lint/lintersdb/manager.go
- test/testdata/interfacebloat.go
A linter that checks the number of methods on an interface.
https://github.com/sashamelentyev/interfacebloat
> feat: add interfacebloat

- .gitattributes
- .github/workflows/tag.yml
- build/Dockerfile
- build/alpine.Dockerfile
Related to https://github.com/golangci/golangci-lint/issues/2374#issuecomment-1217904492
Related to #3107
> fix: set an explicit GOROOT in the Docker image for go-critic

- test/linters_test.go
- test/testshared/analysis.go
- test/testshared/runner.go
Related to #3093 and https://github.com/golangci/golangci-lint/discussions/2969
Currently, we don't have any linter that required this approach, so I cannot add a test.
The test will look like that:
```go
func TestSourcesFromTestdataSubDir(t *testing.T) {
subDirs := []string{
"logrlint",
"ginkgolinter",
}
for _, dir := range subDirs {
t.Run(dir, func(t *testing.T) {
testSourcesFromDir(t, filepath.Join(testdataDir, dir))
})
}
}
```
> dev: improve runner to run dir with go.mod

- test/linters_test.go
- test/testshared/runner.go
I made a mistake here: https://github.com/golangci/golangci-lint/pull/3124/files#diff-2d27f13815d27a52a927014f02a8d7545106cf3db781eb5de69e1f89ec689376R52
I just forget to remove my dev constraint.
only one linter test was running instead of all linter tests.
> dev: fix: linter tests

- .golangci.reference.yml
- go.mod
- go.sum
- pkg/config/linters_settings.go
- pkg/golinters/reassign.go
- pkg/lint/lintersdb/manager.go
- test/testdata/configs/reassign.yml
- test/testdata/configs/reassign_patterns.yml
- test/testdata/reassign.go
- test/testdata/reassign_patterns.go
reassign is a linter to check when global variables in other packages are reassigned, for example `io.EOF = nil`
https://github.com/curioswitch/go-reassign
> feat: add reassign linter

- .golangci.reference.yml
- pkg/result/processors/exclude_rules.go
Minor change to normalize the paths in `exclude-rules`. This re-uses the same logic that is already in place for `skip-dirs`.
Fixes  #1398
> Normalize exclude-rules paths for Windows

- .gitattributes
- .github/workflows/pr.yml
- Makefile
- pkg/result/processors/issues.go
- pkg/result/processors/path_prefixer.go
- pkg/result/processors/path_prefixer_test.go
- pkg/result/processors/path_unix.go
- pkg/result/processors/path_windows.go
- pkg/result/processors/severity_rules.go
- pkg/result/processors/skip_files_test.go
- test/fix_test.go
- test/linters_test.go
- test/output_test.go
- test/run_test.go
- test/testdata/depguard_ignore_file_rules.go
- test/testdata/ifshort.go
- test/testdata/tenv_go118.go
- test/testdata/thelper_go118.go
- test/testshared/analysis.go
- test/testshared/directives.go
- test/testshared/directives_test.go
- test/testshared/runner.go
- test/testshared/runner_test.go
- test/testshared/runner_unix.go
- test/testshared/runner_windows.go
During the migration from Travis (Linux and macOS only) to GitHub Actions a job for Windows has been introduced.
`continue-on-error: true` has been added in the [CI migration PR](https://github.com/golangci/golangci-lint/pull/1056).
So our CI workflow has never worked with Windows.
After a lot of runs on a CI (because I use Linux), and thanks to my previous test framework rewrite, I finally got this job to work.
There are still a few tests that are skipped but these are just a few specific tests.
The side effect: a job on Linux or Darwin takes 4m but 10m on Windows...
Fixes https://github.com/golangci/golangci-lint/issues/1382
Previous tries:
- https://github.com/golangci/golangci-lint/pull/1395
- https://github.com/golangci/golangci-lint/pull/2825
> dev: fix CI workflow for Windows

- pkg/commands/root.go
golangci.com has been shut down since April 2020, so can no longer be
used to run golangci-lint in the cloud.
See https://medium.com/golangci/golangci-com-is-closing-d1fc1bd30e0e
> fix: remove reference to non-working service

- .golangci.reference.yml
- go.mod
- go.sum
- pkg/config/linters_settings.go
- pkg/golinters/gofmt.go
- pkg/golinters/gofmt_common.go
- pkg/golinters/goimports.go
- test/testdata/configs/gofmt_rewrite_rules.yml
- test/testdata/fix/in/gofmt_rewrite_rules.go
- test/testdata/fix/out/gofmt_rewrite_rules.go
- test/testdata/gofmt_rewrite_rules.go
Update gofmt and goimports.
Add the option `rewrite-rules`:
```yml
gofmt:
rewrite-rules:
- pattern: 'a[b:len(a)]'
replacement: 'a[b:]'
```
https://github.com/golangci/gofmt/compare/244bba706f1af52a02a156282f7473162611fba1...f2edd75033f2ca22191625f8286bf50bca0d45ae
Fixes #3171
> feat: update gofmt and goimports and add option "rewrite-rules"

- .golangci.reference.yml
- go.mod
- go.sum
- pkg/golinters/testableexamples.go
- pkg/lint/lintersdb/manager.go
- test/testdata/testableexamples_test.go
testableexamples is a linter that checks if examples are testable (have an expected output).
https://github.com/maratori/testableexamples
Author of idea is @jamietanna, see #3084
> feat: add testableexamples linter

- .golangci.reference.yml
- pkg/config/linters_settings.go
- pkg/golinters/exhaustive.go
Several issues were introduced in #3207 to `exhaustive` linter.
This PR fixes them:
- Add missing `check` config
- Pass `package-scope-only` config to linter
- Use `explicit-exhaustive-switch` config correctly
> exhaustive: add missing config

- .golangci.reference.yml
- pkg/config/linters_settings.go
- pkg/golinters/wsl.go
Now options docs aligned with wsl's and settings supports all of wsl configs.
> wsl: support all configs and update docs

- .golangci.yml
- internal/cache/cache.go
- internal/cache/readme.md
- internal/renameio/readme.md
- internal/renameio/umask_test.go
- internal/robustio/readme.md
- internal/robustio/robustio.go
- internal/robustio/robustio_darwin.go
- internal/robustio/robustio_flaky.go
- internal/robustio/robustio_other.go
- internal/robustio/robustio_windows.go
- pkg/golinters/goanalysis/runner_action.go
- add some readme
- update robustio
- add comments on skip-dirs
- fix flaky tests on Windows and Darwin
> dev: add doc about internal package extracted from Go

- .golangci.reference.yml
PR extracts the info in the description of #2017 into the reference YAML config file. I didn't create an issue first because this PR is simple, and it's just moving existing info written by a maintainer.
I was migrating from `staticcheck` to `golangci-lint`, so I naturally tried to configure the `checks` of the `staticcheck` linter, and it took me some time to find #2017 to understand why it didn't work. This PR can be helpful for this kind of cases.
> docs: specify what code checks are related to staticcheck sub-linter

- .golangci.reference.yml
- go.mod
- go.sum
- pkg/config/linters_settings.go
- pkg/golinters/dupword.go
- pkg/lint/lintersdb/manager.go
- test/testdata/dupword.go
[dupword](https://github.com/Abirdcfly/dupword) is a linter that checks for duplicate words in the source code (usually miswritten)
Examples in real code and related issues can be viewed in https://github.com/Abirdcfly/dupword/issues/3
https://github.com/Abirdcfly/dupword
> feat: add linter dupword
