golangci/golangci-lint

- pkg/golinters/paralleltest.go
- test/testdata/configs/paralleltest.yml
- test/testdata/paralleltest_custom.go
just add tests to prove that `ignore-missing` option works.
> paralleltest: add tests of the ignore-missing option

- go.mod
- go.sum
- pkg/golinters/reassign.go
- pkg/lint/lintersdb/manager.go
Thanks to @MichaelUrman for fixing an issue with shadowing imports by switching to use `TypesInfo` for import tracking.
> build(deps): bump github.com/curioswitch/go-reassign v0.1.2 to v0.2.0

- .golangci.reference.yml
- go.mod
- go.sum
Downgrade Viper to v1.12.0
Related to #3280
> revive: fix configuration parsing

- pkg/golinters/lll.go
- test/testdata/configs/lll_import.yml
- test/testdata/lll_multi_import.go
- test/testdata/lll_single_import.go
Skip long line check on imports.
Fixes #3251
> lll: skip imports

- pkg/printers/checkstyle.go
- pkg/printers/codeclimate.go
- pkg/printers/codeclimate_test.go
- pkg/printers/github_test.go
when I output code climate format report,  GitLab CI code quality report can show the report, but  GitLab MR code quality widget can not.
MR: https://jihulab.com/premium-plan/features/04Verify/code-quality-report/golang/-/merge_requests/1
```
golangci-lint run --enable-all --out-format code-climate:gl-code-quality-report.json
```
<details>
</details>
I try to add those required columns in the docs: https://github.com/codeclimate/platform/blob/master/spec/analyzers/SPEC.md#data-types
add `type` is useless: https://jihulab.com/premium-plan/features/04Verify/code-quality-report/golang/-/merge_requests/3
```
golangci-lint run --enable-all --out-format code-climate:report.json
cat report.json | jq '.[] += { type: "issue" }' > gl-code-quality-report.json
```
add `severity` is usefull: …
> code-climate: add default severity

- .golangci.reference.yml
`gomnd` has been updated in #3295.
New version introduced [more functions](https://github.com/tommy-muehle/go-mnd/commit/86c7103981d88b6598d38e3927275cab84f17192) which always ignored.
This PR updates reference accordingly.
> docs(gomnd): add missing always ignored functions

- .github/ISSUE_TEMPLATE/bug_report.yml
As I wasted @ldez's time in issue #3354, the least I can do is add a note to the issue template that should disambiguate things a touch and prevent this from reoccurring.
> chore: Add a clarifying note to the bug report template

- go.mod
- go.sum
Reverts golangci/golangci-lint#3393
> Revert "build(deps): bump github.com/shirou/gopsutil/v3 from 3.22.10 to 3.22.11"

- pkg/lint/lintersdb/manager.go
> feat: remove deprecated linters from presets

- .golangci.reference.yml
- pkg/config/linters_settings.go
- pkg/golinters/wsl.go
According to [documentation](https://github.com/bombsimon/wsl/blob/master/doc/configuration.md#force-err-cuddling) `enforce` is misspelled for `force-err-cuddling` flag. It also fix the configuration assignment when creating a new WSL linter.
> wsl: fix force-err-cuddling flag

- .golangci.reference.yml
I believe *struck* is a typo of **struct**. Sorry if spammy PR, but that word is tickling my brain :)
> doc: usage typo in tagliatelle

- go.mod
- go.sum
https://github.com/mvdan/unparam/compare/678bad134442...dc49ffedcfbc
Fixes #3426
> unparam: bump to HEAD

- .golangci.reference.yml
- go.mod
- go.sum
- pkg/config/linters_settings.go
- pkg/golinters/ginkgolinter.go
- pkg/lint/lintersdb/manager.go
- test/linters_test.go
- test/testdata/ginkgolinter/configs/ginkgolinter_default.yml
- test/testdata/ginkgolinter/configs/ginkgolinter_suppress_err.yml
- test/testdata/ginkgolinter/configs/ginkgolinter_suppress_len.yml
- test/testdata/ginkgolinter/configs/ginkgolinter_suppress_nil.yml
- test/testdata/ginkgolinter/ginkgolinter.go
- test/testdata/ginkgolinter/ginkgolinter_suppress_err.go
- test/testdata/ginkgolinter/ginkgolinter_suppress_len.go
- test/testdata/ginkgolinter/ginkgolinter_suppress_nil.go
- test/testdata/ginkgolinter/go.mod
- test/testdata/ginkgolinter/go.sum
The ginkgolinter checks the ginkgo and gomega assertions in go tests. See here for
additional details: https://github.com/nunnatsa/ginkgolinter
> Add the ginkgolinter linter

- docs/src/docs/contributing/new-linters.mdx
The binary releases aren't compatible with private linters. This commit adds a section in the new linters documentation that describes the requirements for private linters to work.
> docs: add note about binary requirement for plugin

- install.sh
Uses the releases API to validate a release.
Fixes #3509
> chore: fix install.sh to point at releases API

- install.sh
This is affecting existing users.
Fixes #3512
> chore: fix latest install to cater for existing users who installed using '-s latest'

- install.sh
GitHub engineers have pushed a change that has reverted the bug, so we can revert the changes.
https://github.com/orgs/community/discussions/45590#discussioncomment-4802887
The problem with the changes is the use of the API, this requires a GitHub token to avoid rate limits.
https://github.com/orgs/community/discussions/45590#discussioncomment-4802681
related to #3509, #3510, #3511, #3512, #3513.
> chore: fix install script (revert)

- .golangci.reference.yml
the current example listed for outputs leads to checkstyle XML being saved to a .json file, which is a bit confusing since the output is xml. this PR updates the example to use xml for the checkstyle report, and send json to stdout to still show those capabilities
> docs: update output example to use valid checkstyle example; add json example

- .github/workflows/post-release.yml
- .github/workflows/pr-extra.yml
- .github/workflows/pr.yml
- .github/workflows/tag.yml
- build/Dockerfile
- build/alpine.Dockerfile
- go.mod
- go.sum
- pkg/golinters/goanalysis/runner_loadingpackage.go
- pkg/golinters/gofmt_common.go
- pkg/lint/lintersdb/manager.go
- pkg/lint/load.go
- pkg/lint/runner.go
- test/testdata/notcompiles/typecheck_many_issues.go
This PR adds the support of go1.20.
Note for GitHub Action users: the Go version must be quoted (`'1.20'`) otherwise it is interpreted as a float (`1.2`).
~~This PR is to evaluate and prepare golangci-lint to [go1.20](https://tip.golang.org/doc/go1.20).~~
~~This PR will evolve during the beta and RC phases of [go1.20](https://tip.golang.org/doc/go1.20).~~
Fixes #3420
> go1.20 support

- .github/workflows/pr.yml
temporarily used go1.19 explicitly in 5afb30ed542f37b8099d2ec4c5aeefdb2835e7d4
> dev: use Go1.20 to run tests with the latest golangci-lint version

- go.mod
- go.sum
Fix ginkgolinter so it won't modify the ast tree. This PR bumps the ginkgolinter version to adopt the fix.
https://github.com/nunnatsa/ginkgolinter/compare/v0.7.1...v0.8.0
Fix #3548
> ginkgolinter: fix panic

- .golangci.yml
- go.mod
- go.sum
- pkg/golinters/unused.go
https://github.com/dominikh/go-tools/compare/58c4d7e4b720...v0.4.0
> staticcheck: bump to v0.4.0

- go.mod
- go.sum
https://github.com/go-toolsmith/astcopy/compare/v1.0.2...v1.0.3
related to:
- https://github.com/golangci/golangci-lint/issues/2649#issuecomment-1416239013
- https://github.com/go-toolsmith/astcopy/pull/5
> build(deps): bump github.com/go-toolsmith/astcopy from v1.0.2 to v1.0.3

- .github/workflows/tag.yml
Signed-off-by: jongwooo <jongwooo.han@gmail.com>
Resolve  #3557 
Update `tag.yml` to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
I found the workflow file that use `set-output` command through the following command:
```bash
$ find .github/workflows -name '*.yml' | xargs egrep '\bset-output\b'
```
**AS-IS**
```yml
echo ::set-output name=tag_name::${TAG}
echo ::set-output name=major_tag::${MAJOR}
echo ::set-output name=short_commit::${SHORT_COMMIT}
echo ::set-output name=date::${DATE}
if [[ ${{ matrix.target.Dockerfile }} == *"alpine"* …
```
> dev: replace deprecated command with environment file

- .golangci.reference.yml
This PR removes trailing whitespaces in `.golangci.reference.yml`.
> docs: remove trailing whitespaces

- pkg/lint/runner.go
This PR removes extra whitespace in the warning log about deprecated linter.
Instead of
```
WARN [runner] The linter "golint" is deprecated (since v1.41.0) due to: The repository of the linter has been archived by the owner.  Replaced by revive.
```
now prints without two whitespaces after `the owner`
```
WARN [runner] The linter "golint" is deprecated (since v1.41.0) due to: The repository of the linter has been archived by the owner. Replaced by revive.
```
> dev: do not print extra whitespace in deprecated lint log

- pkg/golinters/govet.go
Updates #3353 
It seems my comment was wrong in #3353. It was enabled by default in go vet.
https://github.com/golang/go/blob/release-branch.go1.20/src/cmd/vet/main.go
> govet: enable timeformat by default

- test/testshared/runner_test.go
This test removes duplicated `assert.Equal(t, test.expected.env, runner.env)` line in `TestRunnerBuilder_Runner`.
> dev: remove duplicated test asserts

- pkg/commands/cache.go
related #2971 
`golangci-lint cache status` always shows 10B if cache directory exists.
That's the size of trim.txt.
> fix: cache status size calculation

- go.mod
- go.sum
- test/testdata/musttag.go
- test/testdata/musttag_custom.go
https://github.com/junk1tm/musttag/compare/v0.4.5...v0.5.0
> build(deps): bump github.com/junk1tm/musttag from 0.4.5 to 0.5.0

- pkg/commands/executor.go
- pkg/golinters/gofumpt.go
- scripts/expand_website_templates/main.go
This PR refactors code to use `bytes.NewBuffer` or `bytes.NewBufferString` to shorten the code.
> dev: bytes.NewBuffer/bytes.NewBufferString to shorten initialization

- .gitignore
When running integration tests on Windows the file `golangci-lint.exe` is created.
> dev: git ignore golangci-lint.exe on Windows

- .golangci.reference.yml
- test/testdata/configs/importas.yml
- test/testdata/configs/importas_strict.yml
- test/testdata/fix/in/gci.go
- test/testdata/fix/out/gci.go
- test/testdata/gci.go
- test/testdata/goimports_local.go
- test/testdata/importas.go
- test/testdata/importas_strict.go
I completely remove `github.com/pkg/errors` from tests because the files inside tests are not considered to create the go.mod.
So when the latest dependency will remove `github.com/pkg/errors`, and then this package will be removed from the go.mod, a lot of tests will fail.
The latest dependency that uses `github.com/pkg/errors` is `forbidigo` and the dependency will be removed inside PR #3639.
> dev: remove github.com/pkg/errors inside tests

- docs/src/docs/contributing/new-linters.mdx
> docs: Clarify that custom linters are not enabled by default

- .golangci.reference.yml
- go.mod
- go.sum
- pkg/config/linters_settings.go
- pkg/golinters/ginkgolinter.go
- test/testdata/ginkgolinter/configs/ginkgolinter_allow_havelen0.yml
- test/testdata/ginkgolinter/configs/ginkgolinter_suppress_compare.yml
- test/testdata/ginkgolinter/ginkgolinter.go
- test/testdata/ginkgolinter/ginkgolinter_havelen0.go
- test/testdata/ginkgolinter/ginkgolinter_suppress_compare.go
- test/testdata/ginkgolinter/ginkgolinter_suppress_err.go
- test/testdata/ginkgolinter/ginkgolinter_suppress_nil.go
ginkgolinter version v0.9.0 brings two new rules. Both rules can be disabled from the configuration.
This PR bumps the ginkgolinter to v0.9.0 and adds the new configurations.
https://github.com/nunnatsa/ginkgolinter/compare/v0.8.1...v0.9.0
The two new rules are:
* haveLen(0) rule: `HaveLen(0)` ==> `BeEmpty()`
* wrong comparison rule: `Expect(x == y).To(BeTrue())` ==>
`Expect(x).To(Equal(y))`
The two new configurations are:
* `allow-havelen-0` - to not trigger warnings for the HaveLen(0) rule
* `suppress-compare-assertion` - to not trigger warnings for the wrong comparison rule.
Full details are in the ginkgolinter README.md file, here: https://github.com/nunnatsa/ginkgolinter#readme.
> build(deps): bump github.com/nunnatsa/ginkgolinter from 0.8.1 to 0.9.0

- pkg/golinters/gci.go
- pkg/golinters/goerr113.go
- pkg/golinters/thelper.go
> doc: replace golang with Go in descriptions for gci, thelper, goerr113

- docs/src/docs/usage/faq.mdx
This CI service [stopped](https://medium.com/golangci/golangci-com-is-closing-d1fc1bd30e0e) on 15-th of April, 2020.
> doc: remove from FAQ golangci.com mention

- .pre-commit-hooks.yaml
Fixes #1245
by passing filenames from pre-commit to `golangci-lint run` (which supports this since that issue was originally opened) and when used with `--new-from-rev HEAD` allows for partial commit support.
> feat: check only changed files in pre-commit hook

- .golangci.reference.yml
The default value for `go` and `lang-version` options are always overridden by the global [`run.go:`](https://github.com/alexandear/golangci-lint/blob/51f9218f6cc37b56af7ed85d573cc50b7b0e559a/.golangci.reference.yml#L73).
> docs: remove description for deprecated "go" option

- pkg/golinters/errcheck.go
The description of the linter's [README](https://github.com/kisielk/errcheck#readme) was changed.
Follows #3654.
> doc: enhance errcheck description

- pkg/lint/lintersdb/manager.go
- test/testdata/sqlclosecheck.go
- test/testdata/wastedassign.go
Closes https://github.com/sanposhiho/wastedassign/issues/41
Related to https://github.com/golangci/golangci-lint/discussions/3580, https://github.com/golangci/golangci-lint/issues/2649, https://github.com/golangci/golangci-lint/discussions/3396, https://github.com/letsencrypt/boulder/issues/6202, https://github.com/hashicorp/terraform-provider-aws/issues/18596
> wastedassign: remove limitation related to generics support

- pkg/lint/lintersdb/manager.go
I run my tests suite (not the golangci-lint tests) that contains multiple and complex generics usages and everything seems to work.
Related to #2649
Related to https://github.com/jingyugao/rowserrcheck/pull/28
> rowserrcheck: remove limitation related to generics support

- go.mod
- go.sum
https://github.com/matoous/godox/compare/6504466cf951...006bad1f9d26
> godox: bump to HEAD

- .golangci.reference.yml
- docs/src/docs/usage/false-positives.mdx
- pkg/fsutils/files.go
- pkg/lint/runner.go
- pkg/result/processors/base_rule.go
- pkg/result/processors/exclude_rules.go
- pkg/result/processors/exclude_rules_test.go
- pkg/result/processors/path_prefixer.go
- pkg/result/processors/severity_rules.go
- pkg/result/processors/severity_rules_test.go
- pkg/result/processors/skip_dirs.go
- pkg/result/processors/skip_files.go
- pkg/result/processors/skip_files_test.go
When someone invokes golangci-lint in a sub-directory, they can set the path prefix to make the output look like the invocation had been done in the root.
But this prefix was ignored when checking path patterns of exclude, severity, and skip files/dirs entries, so those with matching for directories only worked when golangci-lint was always invoked in the same directory.
The underlying problem is that the rules from the configuration get checked before updating the path associated with the issues in the path fixer.
To make the prefix work, it now gets passed down into processors and added there to the issue path before checking against the path pattern.
For exclude and severity rules, this could have been done through a separate parameter, but bundling it in a new `fsutils` helper struct …
> fix: consider path prefix when matching path patterns

- .github/CONTRIBUTING.md
- docs/gatsby-node.js
Correct the typo in `CONTRIBUTING.md` and in the success report message in `docs/gatsby-node.js`.
> docs: fix typos

- pkg/golinters/goanalysis/runner_action.go
Related to #3086
<details>
<summary>before the PR</summary>
```console
$ golangci-lint cache clean && golangci-lint run  --disable-all --print-issued-lines=false -Ebodyclose 
ERRO [runner] Panic: bodyclose: package "ent" (isInitialPkg: true, needAnalyzeSource: true): interface conversion: interface {} is nil, not *buildssa.SSA: goroutine 1176 [running]:
runtime/debug.Stack()
runtime/debug/stack.go:24 +0x65
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func1()
github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_action.go:102 +0x155
panic({0xfd4880, 0xc0022ec060})
runtime/panic.go:884 +0x213
github.com/timakin/bodyclose/passes/bodyclose.runner.run({0xc00157a0f0, {0x0, 0x0}, 0x0, {0x0, 0x0}, 0x0, 0x0}, 0xc00157a0f0) …
```
> fix: improve panic management

- pkg/commands/run.go
- pkg/fsutils/linecache.go
- pkg/lint/runner.go
- pkg/result/processors/fixer.go
- test/fix_test.go
This combination used to fail because the fixer was executed after the path prefixed.
Then the file paths that it processed didn't match the current working directory, leading to:
```
ERRO Failed to fix issues in file test/fix_sample/main.go: failed to get file bytes for test/fix_sample/main.go: can't read file test/fix_sample/main.go: open test/fix_sample/main.go: no such file or directory
```
Making the fixer a normal processor and moving it before the path prefixed avoids this problem.
Related to #2293 and #3626
> fix: combination of --fix and --path-prefix

- .pre-commit-hooks.yaml
In order to avoid the following error when running pre-commit
> Error: parallel golangci-lint is running
We need to force golangci-lint to run in sequence.
Fixes #3715
> fix(pre-commit): require_serial & pass_filenames

- pkg/lint/lintersdb/manager.go
- test/testshared/runner.go
- test/testshared/runner_test.go
The limitation was introduced when the generics appears to avoid compatibility problems.
Now the generics are in all versions of Go so we can remove restrictions.
> tests: remove go version restrictions

- .github/contributors/generate.ts
I suppose [`golangci-releaser`](https://github.com/golangci-releaser) is a service user.
> dev: remove golangci-releaser from generated team

- pkg/config/reader.go
> feat: remove warning when the config file is explicitly stdin

- .golangci.yml
This PR enables `revive` in the `.golangci.yml` config.
> dev: enable revive linter with default config

- .golangci.reference.yml
- .golangci.yml
- pkg/commands/run.go
- pkg/config/output.go
- pkg/golinters/nolintlint/nolintlint_test.go
- pkg/lint/lintersdb/enabled_set_test.go
- pkg/printers/tab.go
- pkg/printers/tab_test.go
- pkg/printers/text.go
- pkg/printers/text_test.go
- test/enabled_linters_test.go
- test/testshared/analysis_test.go
- test/testshared/runner_test.go
This PR introduces 2 changes:
- remove the color of the `tab` output
- add a new output `colored-tab`
I introduce a new `colored-tab` instead of `no-color-tab` to be homogeneous with `line-number` and `colored-line-number`.
I think that the removal of the color is a minor change because I don't see in which context it can be breaking.
Fixes #3728
> output: add colored-tab

- pkg/golinters/importas.go
Produce an error log when a package has multiple aliases:
```yml
importas:
no-unaliased: true
alias:
- alias: netv1
pkg: "k8s.io/api/networking/v1"
- alias: networkingv1
pkg: "k8s.io/api/networking/v1"
```
Produce an error log when an alias is used for several packages:
```yml
importas:
no-unaliased: true
alias:
- alias: netv1
pkg: "k8s.io/api/networking/v1"
- alias: netv1
pkg: "k8s.io/api/networking/v1beta1"
```
> importas: detect duplicate alias or package in the configuration

- go.mod
- go.sum
- pkg/golinters/nakedret.go
- test/testdata/nakedret.go
Handling of naked returns inside conditionals as well as from nested functions has been added upstream, in https://github.com/alexkohler/nakedret/pull/12 and more commits.
This should resolve #1317.
> build(deps): bump github.com/alexkohler/nakedret to 2.0.1

- .golangci.yml
- pkg/commands/run.go
- pkg/golinters/gocritic_test.go
- pkg/logutils/logutils.go
- pkg/printers/checkstyle.go
- pkg/printers/checkstyle_test.go
- pkg/printers/codeclimate.go
- pkg/printers/codeclimate_test.go
- pkg/printers/github.go
- pkg/printers/github_test.go
- pkg/printers/html.go
- pkg/printers/html_test.go
- pkg/printers/json.go
- pkg/printers/json_test.go
- pkg/printers/junitxml.go
- pkg/printers/junitxml_test.go
- pkg/printers/printer.go
- pkg/printers/tab.go
- pkg/printers/tab_test.go
- pkg/printers/teamcity.go
- pkg/printers/teamcity_test.go
- pkg/printers/text.go
- pkg/printers/text_test.go
This PR removes `ctx` parameter from the `Printer.Print` method because it's not used in any of the printers.
Also, enable revive `unused-parameter` rule for detecting this. And fix occurred issues in other files.
> dev: remove unused ctx parameter from Printer

- pkg/golinters/gci.go
- test/testdata/configs/gci.yml
- test/testdata/fix/in/gci.go
- test/testdata/fix/out/gci.go
- test/testdata/gci.go
~~Adds custom-order flag~~
~~Supports gci StringArray breaking change introduced in version 0.10.0. CSV-style `-s one,two,three` must now be `use -s one -s two -s three` which now supports multiple prefixes.~~
~~Fixes #3776~~
Improve error message.
> gci: improve error message

- pkg/config/linters_settings.go
- pkg/lint/lintersdb/manager.go
- test/testdata/configs/usestdlibvars_non_default.yml
- test/testdata/usestdlibvars_non_default.go
> usestdlibvars: fix configuration

- docs/src/docs/contributing/new-linters.mdx
This PR fixes a minor grammatical issue in the new linters doc.
> docs: Fix minor typo in new-linters.mdx

- .golangci.reference.yml
- pkg/golinters/tagliatelle.go
Minor change to the Tagliatelle docs/config to add support for v0.5.0 which adds `upperSnake` casing. The gomod version has [already been updated by dependabot](https://github.com/golangci/golangci-lint/pull/3782).
Related:
- https://github.com/ldez/tagliatelle/pull/17
- https://github.com/SchemaStore/schemastore/pull/2941
> doc: update tagliatelle documentation

- docs/src/docs/usage/faq.mdx
Issue https://github.com/golangci/golangci-lint/issues/2649 is closed now. Suppose it works without limitations now.
> docs: update supported Go versions FAQ

- pkg/config/issues_test.go
- pkg/lint/lintersdb/enabled_set_test.go
This PR refactors tests:
- replace raw loops with `assert.Contains` and `assert.NotContains`;
- use `assert.ElementsMatch` instead of `sort.Stirngs` with `assert.Equal`.
> dev: simplify issues and enabled set tests

- .golangci.reference.yml
- go.mod
- go.sum
- pkg/golinters/mirror.go
- pkg/lint/lintersdb/manager.go
- test/testdata/mirror.go
[`mirror`](https://github.com/butuzov/mirror) - linter suggest alternative functions while working with `strings/[]byte` (e.g. `strings.HasPrefix` and `bytes.HasPrefix`, if it alternative can be used).
- `gocritic` as experimental implementation of `io.Writer` and `io.StringWriter` detection, which is fitting to the functionality of `mirror`,  but `mirror` instead checking additional functions from std lib, ignoring (for now) interface checking for `io.Writer` / `io.StringWriter`
- Currently intentionally ignoring constructions like this (in TODO)
```go
(&maphash.Hash{}).Write(aliasBytes("foobar"))
```
> mirror: linter that suggest using alternative string/[]byte functions

- go.mod
- go.sum
- pkg/golinters/depguard.go
Following the plan that I explained [here](https://github.com/golangci/golangci-lint/issues/3862#issuecomment-1572907138):
- create a fork inside the golangci org
- apply the fix
- use the fork as a dependency (I will create a dedicated module to avoid `replace` directives, because `replace` directives are not transitive, so users that are using that use the `tools` pattern will not have a problem.)
---
Summary of issue #3862:
depguard uses `build.Default.GOROOT` but this value is filled correctly only if the `GOROOT` is defined through an env var.
```console
$ go env | grep GOROOT
GOROOT="/usr/local/go"
$ env | grep GOROOT
$ export GOROOT=/usr/local/go
$ env | grep GOROOT
GOROOT=/usr/local/go
```
The "expander" cannot be overridden because it's a global variable inside an internal …
> depguard: fix GOROOT detection

- pkg/golinters/importas.go
skip the duplication check when the alias is a regular expression replacement pattern (ie. contains `$`).
Fixes #3867
> importas: fix duplication detection when aliases use regular expression replacement pattern

- go.mod
- go.sum
- pkg/golinters/depguard.go
I change our depguard fork to be able to handle the error.
Now the error (related to GOROOT) can only happen when the linter is called.
https://github.com/golangci/depguard/compare/ed68d37...4f22f85
I created an issue on the depguard repository to discuss a change in the API.
https://github.com/OpenPeeDeeP/depguard/issues/50
> depguard: throw error only when the linter is called

- go.mod
- go.sum
- pkg/golinters/depguard.go
Do the same thing as #3880 but remove our fork.
> build(deps): bump github.com/OpenPeeDeeP/depguard/v2 from v2.0.1 to 2.1.0

- pkg/printers/codeclimate.go
- pkg/printers/codeclimate_test.go
Use json encoder to write codeclimate report.
> codeclimate: less memory allocation

- go.mod
`nosnakecase` is a direct dependency, and I just tidied the `go.mod` file
> dev: tidy go deps

- .github/workflows/documentation.yml
Currently, only one person has access to the Netlify administration (it's not me) and this is a problem because it can be really difficult when we have to update something inside the Netlify admin.
It will be easier to diagnose and fix problems like #3663.
This PR introduces Github Pages in parallel with Netlify because we need to have the branch and the content before setting up the custom domain.
When we will set the custom domain, I will open another PR to remove Netlify-related files.
FYI: I tested this PR on my fork.
> dev: use to GitHub Pages

- go.mod
- go.sum
This version fixes https://github.com/nunnatsa/ginkgolinter/issues/88
> build(deps): bump github.com/nunnatsa/ginkgolinter from 0.12.2 to 0.12.1

- .goreleaser.yml
- install.sh
This is related to issue #3849. I believe this is all that's necessary to add support for building illumos/amd64 releases. Please provide any feedback if something feels incomplete.
> Add support for generating illumos/amd64 targeted builds

- docs/src/docs/contributing/new-linters.mdx
- pkg/commands/executor.go
- pkg/lint/lintersdb/custom_linters.go
- pkg/lint/lintersdb/manager.go
> fix: include custom linters in `enable-all`

- go.mod
- go.sum
- pkg/config/linters_settings.go
- pkg/golinters/misspell.go
- test/testdata/configs/misspell.yml
- test/testdata/misspell.go
misspell: convert ignore-words to lowercase
https://github.com/golangci/misspell/compare/v0.4.0...v0.4.1
Fixes #3406
> build(deps): bump github.com/golangci/misspell 0.4.0 to 0.4.1

- .github/ISSUE_TEMPLATE/bug_report.yml
Move "Yes, I've included all information below (version, config, etc.)." to the end of the form to enforce the need to include all the required information.
> dev: improve bug report template

- scripts/expand_website_templates/main.go
resolves #3927 
The idea was to add the description for each linter before the snippet in the /linters section.
**Additional**
I added a formatting function that normalizes all linters' descriptions. This function uppercases the first letter and adds a final dot if missing.
This is for better understanding so the user doesn't have to scroll all the way up to read the linter's description.
I call the function GetAllSupportedLinterConfigs() and create a map with each linter's name and description. This way I decrease the complexity since I use just one loop to make it and the later search is O(1).
Everything is working fine.
From this:
To this: 
**Additional**
From this:
To this:
Looking forward to your comments :)
> docs: add linters description

- .golangci.reference.yml
- go.mod
- go.sum
- pkg/config/linters_settings.go
- pkg/golinters/decorder.go
Hi everyone :),
I've just updated my linter with a few more config options. This pr adds new options to golangci-lint. 
Please let me know if I miss any spots or if you want anything else to change before merging.
https://gitlab.com/bosi/decorder/-/compare/v0.2.3...v0.4.0
> build(deps): bump gitlab.com/bosi/decorder from 0.2.3 to 0.4.0

- .golangci.reference.yml
- go.mod
- go.sum
- pkg/config/linters_settings.go
- pkg/golinters/ginkgolinter.go
- test/testdata/ginkgolinter/configs/ginkgolinter_suppress_focused_containers.yml
- test/testdata/ginkgolinter/ginkgolinter.go
- test/testdata/ginkgolinter/ginkgolinter_havelen0.go
- test/testdata/ginkgolinter/ginkgolinter_suppress_async.go
- test/testdata/ginkgolinter/ginkgolinter_suppress_compare.go
- test/testdata/ginkgolinter/ginkgolinter_suppress_err.go
- test/testdata/ginkgolinter/ginkgolinter_suppress_focused_containers.go
- test/testdata/ginkgolinter/ginkgolinter_suppress_len.go
- test/testdata/ginkgolinter/ginkgolinter_suppress_nil.go
This PR bumps ginkgolinter to v0.13.3
This version is a bugfix, and it set the new focused container rule to be disabled by default.
The configuration flag name was change to reflact that, so this PR also fixes the configuration parameter name:
`suppress-focus-container` ==> `forbid-focus-container`
https://github.com/nunnatsa/ginkgolinter/compare/v0.13.0...v0.13.3
@ldez - I don't want to wait for the auto-bump job, because this change breaks the previous change (not released yet).
> build(deps): bump github.com/nunnatsa/ginkgolinter from 0.13.0 to 0.13.3

- .golangci.reference.yml
- go.mod
- go.sum
- pkg/golinters/tagalign.go
- test/testdata/configs/tagalign_strict.yml
- test/testdata/tagalign_strict.go
The strict style of `tagalign` must be used together with align and sort option, or it will be ignored.
Also add a test case for strict style.
https://github.com/4meepo/tagalign/compare/v1.3.1...v1.3.2
> build(deps): bump github.com/4meepo/tagalign from 1.3.1 to 1.3.2

- .github/workflows/documentation.yml
- .github/workflows/post-release.yml
- .github/workflows/pr-extra.yml
- .github/workflows/pr.yml
- .github/workflows/tag.yml
- .golangci.yml
- build/Dockerfile
- build/alpine.Dockerfile
- go.mod
- pkg/config/config.go
- pkg/golinters/gocritic.go
- pkg/lint/linter/config.go
- pkg/lint/lintersdb/manager.go
- test/fix_test.go
- test/linters_test.go
This PR is to evaluate and prepare golangci-lint to [go1.21](https://tip.golang.org/doc/go1.21).
This PR will evolve during the beta and RC phases of [go1.21](https://tip.golang.org/doc/go1.21).
> go1.21 support

- pkg/lint/lintersdb/manager.go
Trims the Go version to keep only M.m.
Since Go 1.21 the version inside the go.mod can be a patched version (ex: 1.21.0).
https://go.dev/doc/toolchain#versions
This a problem with staticcheck and gocritic.
https://github.com/dominikh/go-tools/issues/1431
Related to #3933
> fix: trim Go version

- go.mod
- go.sum
- pkg/golinters/gocritic.go
- test/fix_test.go
- test/linters_test.go
> build(deps): bump github.com/quasilyte/go-ruleguard from v0.3.19 to v0.4.0

- pkg/lint/lintersdb/custom_linters.go
Fixes #4001
I will create a PR after the merge of this one to restore the log.
> plugin: temporarily hide warning about using plugins using the old API

- .github/workflows/pr.yml
- .github/workflows/tag.yml
Some CI config cleanups, noticed while working on something else. `GITHUB_TOKEN` env scoping not fully tested, but I believe it could work like this.
> dev: CI cleanups

- .golangci.reference.yml
- pkg/golinters/govet.go
ref
- https://github.com/golang/go/issues/59407
- https://github.com/golang/go/issues/56986
> govet: add directive and slog passes

- build/Dockerfile
- build/alpine.Dockerfile
Related to https://github.com/golangci/golangci-lint/issues/3982#issuecomment-1662587360
Related to https://github.com/golangci/golangci-lint/issues/4033#issuecomment-1686025933
```console
$ git clone git@github.com:openshift-pipelines/pipelines-as-code.git
...
$ cd pipelines-as-code
$ docker run --rm -it -v $(pwd):/app -w /app golangci/golangci-lint:v1.54.1 sh
cmd/pipelines-as-code-controller/main.go:1: : error obtaining VCS status: exit status 128
Use -buildvcs=false to disable VCS stamping. (typecheck)
package main
cmd/pipelines-as-code-watcher/main.go:1: : error obtaining VCS status: exit status 128
Use -buildvcs=false to disable VCS stamping. (typecheck)
package main
cmd/pipelines-as-code-webhook/main.go:1: : error obtaining VCS status: exit status 128
Use -buildvcs=false to disable …
```
> fix: add all directories as safe git directories inside the Docker image

- .golangci.reference.yml
- go.mod
- go.sum
- pkg/config/linters_settings.go
- pkg/golinters/dupword.go
- test/testdata/configs/dupword_ignore_the.yml
- test/testdata/dupword_ignore_the.go
For Abirdcfly/dupword#26
need an option for allowing some duplicate words without an annotation.
https://github.com/Abirdcfly/dupword/compare/v0.0.12...v0.0.13
> build(deps): bump github.com/Abirdcfly/dupword from 0.0.12 to 0.0.13

- .golangci.reference.yml
G602 (Slice access out of bounds) was added in gosec 2.17.
gosec Release/Changelog: https://github.com/securego/gosec/releases/tag/v2.17.0
> docs: add gosec G602 to includes/excludes inside .golangci.reference.yml

- .golangci.yml
- test/ruleguard/dup.go
- test/ruleguard/rangeExprCopy.go
- test/ruleguard/strings_simplify.go
This PR enables `gocheckcompilerdirectives` and fixes compiler directives.
> dev: enable gocheckcompilerdirectives linter

- docs/src/docs/usage/false-positives.mdx
Add `source` options to `exclude-rules` docs.
Fix #3409
> docs: add source options to exclude-rules docs

- go.mod
- go.sum
https://github.com/golangci/gofmt/compare/f2edd75033f2...933a45ce4cd8
> feat: update gofmt and goimports

- .golangci.reference.yml
- go.mod
- go.sum
- pkg/config/linters_settings.go
- pkg/golinters/testifylint.go
- pkg/lint/lintersdb/manager.go
- test/testdata/testifylint.go
Hi!
https://github.com/Antonboom/testifylint
1. Supports `analysis.SuggestedFix` (but no integration in `golangci-lint`? https://github.com/golangci/golangci-lint/issues/1779)
2. Supports `analysis.Diagnostic.Category` & `URL` (but no usage of this feature in `golangci-lint`?)
P.S. For local dev you need `1.21`, but the module itself I returned to `1.20` by replacing useful package (`slices`) with own code 😢 
---
Recreated from https://github.com/golangci/golangci-lint/pull/4072, because of
> Add `testifylint` linter

- .golangci.reference.yml
- go.mod
- go.sum
- pkg/golinters/gochecksumtype.go
- pkg/golinters/unparam.go
- pkg/lint/lintersdb/manager.go
- test/testdata/gochecksumtype.go
`gochecksumtype` is a linter that checks that type switches on "sum types" in Go are exhaustive.
https://github.com/alecthomas/go-check-sumtype
This is based on BurntSushi/go-sumtype, but fixes, modernises and simplifies it.
fixes #402
> feat: add `gochecksumtype` linter

- .golangci.reference.yml
- pkg/config/linters_settings.go
- pkg/golinters/unused.go
- pkg/lint/lintersdb/manager.go
Allow users to tune `unused`'s behavior.
To avoid mutating global parameters, this PR avoids re-using the exported `analysis.Analyzer` and implement it in the same fashion as staticcheck's [internal/cmd/unused](https://github.com/dominikh/go-tools/blob/4ec1f474ca6c0feb8e10a8fcca4ab95f5b5b9881/internal/cmd/unused/unused.go#L68)
Fixes #4085
> unused: support passing in options

- .golangci.reference.yml
- go.mod
- go.sum
- pkg/golinters/inamedparam.go
- pkg/lint/lintersdb/manager.go
- test/testdata/inamedparam.go
I'd like to add the following linter: https://github.com/macabu/inamedparam 
It detects interface methods that don't have a named param and nudges to name them to improve clarity.  
I haven't found something similar in the available golangci-lint linters.
> Add "inamedparam": checks for interface method with unnamed params

- pkg/commands/root.go
This PR changes the description for `verbose` and `silent` command options to start with the upper character.
> docs: uppercase command option descriptions for consistency

- .golangci.reference.yml
- go.mod
- go.sum
- pkg/config/linters_settings.go
- pkg/golinters/sloglint.go
- pkg/lint/lintersdb/manager.go
- test/testdata/configs/sloglint_args_on_sep_lines.yml
- test/testdata/configs/sloglint_attr_only.yml
- test/testdata/configs/sloglint_kv_only.yml
- test/testdata/configs/sloglint_no_raw_keys.yml
- test/testdata/sloglint.go
- test/testdata/sloglint_args_on_sep_lines.go
- test/testdata/sloglint_attr_only.go
- test/testdata/sloglint_kv_only.go
- test/testdata/sloglint_no_raw_keys.go
Hello,
I'd like to add the [`sloglint`](https://github.com/go-simpler/sloglint) linter.
It ensures consistent code style when using `log/slog`.
Currently, the following checks are available:
- Forbid mixing key-value pairs and attributes within a single function call (default)
- Enforce using either key-value pairs or attributes for the entire project (optional)
- Enforce using constants instead of raw keys (optional)
- Enforce putting arguments on separate lines (optional)
I've tested it on several big projects that use `log/slog`, and it works just fine 😎
> feat: add `sloglint` linter

- go.mod
- go.sum
https://github.com/golangci/gofmt/compare/933a45ce4cd8...f50ced29576e
Fixes #4136
> fix: update gofmt

- go.mod
- go.sum
https://github.com/uudashr/gocognit/compare/v1.0.7...v1.1.0
related to https://github.com/uudashr/gocognit/issues/35 and https://github.com/golangci/golangci-lint/pull/4129#issuecomment-1770313331
**This update is done by hand because dependabot is not able to downgrade dependency.**
> build(deps): bump github.com/uudashr/gocognit from 1.1.1 to 1.1.0

- .golangci.reference.yml
Closes https://github.com/golangci/golangci-lint/issues/4134
@ldez, hi!
I reviewed all linters and yes, you are right:
> The majority of those empty defaults are real.
If you don't see the point in this pr, you can close it, I won't mind.
Thanks
> docs: describe enabled and disabled by default analyzers of govet

- .golangci.reference.yml
- go.mod
- go.sum
- pkg/golinters/perfsprint.go
- pkg/lint/lintersdb/manager.go
- test/testdata/perfsprint.go
https://github.com/catenacyber/perfsprint
This is a linter for performance, aiming at usages of `fmt.Sprintf` which have faster alternatives in the standard library such as `strconv.Itoa`
---
I hope I did this correctly by following https://golangci-lint.run/contributing/new-linters/ and https://disaev.me/p/writing-useful-go-analysis-linter/
`make vendor README.md` did not work
See https://github.com/golang/go/pull/59144 for an example on the Go std lib
> Add perfsprint linter

- pkg/printers/github.go
- pkg/printers/github_test.go
This commit addresses an issue in the GitHub Actions printer where file paths were using backslashes on Windows systems.
As result we didn't see correct annotations in the PRs. To ensure proper formatting we always convert to forward slash separator in filepathes.
> output: convert backslashes to forward slashes for GitHub Action annotations printer

- .golangci.reference.yml
- go.mod
- go.sum
- pkg/config/linters_settings.go
- pkg/golinters/sloglint.go
- test/testdata/configs/sloglint_context_only.yml
- test/testdata/configs/sloglint_key_naming_case.yml
- test/testdata/sloglint_context_only.go
- test/testdata/sloglint_key_naming_case.go
A few options have been added:
- ContextOnly: enforce using methods that accept a context
- KeyNamingCase: enforce a single key naming convention
https://github.com/go-simpler/sloglint/compare/v0.1.2...v0.2.0
> build(deps): bump go-simpler.org/sloglint from 0.1.2 to 0.2.0

- go.mod
- go.sum
- pkg/golinters/revive.go
- pkg/golinters/whitespace.go
- test/testdata/fix/in/whitespace.go
- test/testdata/fix/out/whitespace.go
The `whitespace` linter is rewritten to use `annalysis.Analyzer`. This PR will make use of the new code.
---
~~This is a draft PR until https://github.com/ultraware/whitespace/pull/8 is merged and a new release has been made.~~
> whitespace: update after moving to the `analysis` package

- pkg/golinters/asciicheck.go
- pkg/golinters/bidichk.go
- pkg/golinters/bodyclose.go
- pkg/golinters/cyclop.go
- pkg/golinters/errchkjson.go
- pkg/golinters/errname.go
- pkg/golinters/goprintffuncname.go
- pkg/golinters/grouper.go
- pkg/golinters/ifshort.go
- pkg/golinters/ineffassign.go
- pkg/golinters/nakedret.go
- pkg/golinters/noctx.go
- pkg/golinters/paralleltest.go
- pkg/golinters/rowserrcheck.go
- pkg/golinters/sqlclosecheck.go
- pkg/golinters/thelper.go
- pkg/golinters/tparallel.go
- pkg/golinters/wastedassign.go
- pkg/golinters/wrapcheck.go
This PR refactors linters constructors to use `analyzer.Name`  and `analyzer.Doc` instead of hardcoded strings.
> dev: use analyzer fields for name, doc instead of hardcoded strings

- pkg/golinters/zerologlint.go
This PR does the same changes as in the https://github.com/golangci/golangci-lint/pull/4214 but for zerologlint.
[zerologlint 0.1.4](https://github.com/golangci/golangci-lint/pull/4222) has [necessary changes](https://github.com/ykadowak/zerologlint/commit/b7e040a44bb3339aa00853a331bd1430224fa446) for Name and Doc fields.
> dev: use zerologlint analyzer fields for name and doc

- .golangci.reference.yml
- pkg/config/config.go
Fix documentation to follow what code does. Reference https://github.com/golangci/golangci-lint/blob/master/pkg/config/config.go#L70
> docs: fix Go version fallback 

- docs/src/docs/contributing/website.mdx
https://rocketdocs.netlify.app/ (which takes to https://rocketdocs.gatsbyjs.io/) is not available anymore. Change URL to code repository.
> doc: fix URL not available

- build/Dockerfile
- build/alpine.Dockerfile
goreleaser currently strips the leading `v` off of the SemVer tag when passing to ldflags, while the container build does not remove it.
Remove the leading `v`, if present, off of the version in container builds so that the version returned by `golangci-lint --version` is consistent regardless of whether the program is running standalone or in a container.
As discussed in https://github.com/golangci/golangci-lint/discussions/4268.
Fixes #4263
> fix: make versioning inside Docker image consistent with binaries

- .golangci.reference.yml
- pkg/config/linters_settings.go
- pkg/golinters/misspell.go
Adds an option `mode`:
- default: checks all the file content.
- restricted: checks only comments.
This option is closed to the CLI flags `source` of `misspell` but I changed the naming and the value to have something less misleading.
> misspell: add mode option

- .golangci.reference.yml
Add options that were only referenced in CLI with `--help` to `.golangci.reference.yml`.
> doc: add missing fields to .golangci.reference.yml

- go.mod
- go.sum
- pkg/golinters/goanalysis/runner_action.go
- pkg/lint/lintersdb/custom_linters.go
- pkg/lint/runner.go
This PR replaces [github.com/hashicorp/go-multierror](https://pkg.go.dev/github.com/hashicorp/go-multierror) package with the native [joining errors](https://pkg.go.dev/errors#Join) mechanism.
> dev: replace hashicorp/go-multierror with errors.Join

- .golangci.yml
- pkg/commands/executor.go
- pkg/commands/run.go
- pkg/config/issues.go
- pkg/config/reader.go
- pkg/fsutils/fsutils.go
- pkg/golinters/golint.go
- pkg/golinters/lll.go
- pkg/golinters/misspell.go
- pkg/golinters/nolintlint.go
- pkg/lint/lintersdb/custom_linters.go
- pkg/packages/errors.go
- pkg/result/processors/diff.go
- pkg/result/processors/skip_files.go
This PR enables `errorlint` linter in `.golangci.yml` and fixes up issues:
```
non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
comparing with == will fail on wrapped errors. Use errors.Is to check for a specific error
```
> dev: enable errorlint linter

- go.mod
- go.sum
- pkg/golinters/goanalysis/runner.go
- pkg/golinters/gocritic.go
- pkg/golinters/govet_test.go
- pkg/golinters/thelper.go
- pkg/lint/lintersdb/enabled_set.go
- pkg/lint/lintersdb/enabled_set_test.go
- pkg/printers/checkstyle.go
- pkg/printers/junitxml.go
- pkg/result/processors/nolint.go
- scripts/expand_website_templates/main.go
This PR replaces raw loops with functions from [slices](https://pkg.go.dev/golang.org/x/exp/slices) and [maps](https://pkg.go.dev/golang.org/x/exp/maps) packages. By doing this, we are simplifying our code base, enhancing readability, and improving maintainability.
https://github.com/golang/exp/compare/dd950f8aeaea...be819d1f06fc
> dev: replace raw loops with funcs from slices and maps

- docs/src/docs/usage/configuration.mdx
This is just a simple grammatical fix, which could have been a mishandled merge conflict. Either way, its pretty trivial. 
Fixes #4301
> docs: fix grammar

- docs/src/docs/usage/faq.mdx
rephrases the doc to try to be more clear about the nature of `typecheck`.
> docs: improve typecheck FAQ

- pkg/lint/lintersdb/manager.go
- pkg/lint/lintersdb/manager_test.go
> fix: parse Go RC version

- .golangci.reference.yml
This adds `errors.Join(` to the signatures ignored by default, which has been added to the wrapcheck linter in v2.8.0 a while ago. See https://github.com/tomarrell/wrapcheck/releases/tag/v2.8.0
> docs: adjust wrapcheck ignoreSigs to new defaults

- .github/workflows/pr.yml
- go.sum
The PR updates "Check go mod" action step to check also `go.sum`. This reverts #1397. Additionally, the PR cleans `go.sum`.
> dev: check go.sum is up to date

- go.mod
- go.sum
- pkg/config/reader.go
References:
- https://github.com/mitchellh/mapstructure/pull/328#issuecomment-1858922295
- https://github.com/mitchellh/mapstructure/issues/349
- https://www.theregister.com/2023/12/15/hashimoto_departs_hashicorp/
> dev: replace mitchellh/mapstructure by go-viper/mapstructure/v2

- docs/src/docs/usage/install/index.mdx
The PR modifies "Install from Source" doc section. Changes:
- remove outdated info about an old compiler bug which was fixed;
- capitalize the first letter in a numbered list because each item is a sentence ([see](https://www.purchase.edu/editorial-style-guide/general-style-preferences/punctuation/bulleted-and-numbered-lists/)).
> docs: adjust list from why install from source is not recommended

- .golangci.reference.yml
- pkg/commands/run.go
- pkg/config/run.go
In this PR I added a flag that enables basic stats collection and printing per linter using the `--show-stats-per-linter` flag to the `run` subcommand. This only prints the stats to the terminal after running all the linters.
**Note to the reviewers:**
I tried implementing it using `e.runAnalysis` to return the stats from the `run.Run`, yet it made things more complicated. I can still do it if you prefer that approach and I'd be happy to have your feedback. Also, I can either update the `printers.Print` interface to accept the stats or add a extra field (somewhere), so that the stats are printed based on the formatter used, and not just to the terminal.
Closes #2924.
> feat: implement stats per linter with a flag

- .golangci.reference.yml
- pkg/commands/config.go
- pkg/commands/linters.go
- pkg/commands/run.go
- test/testshared/runner.go
- test/testshared/runner_test.go
`config` and `linters` command would present all flags from `run` command to users. This PR removes unnecessary flags from those commands.
> dev: remove unrelated flags from config and linters command

- go.mod
- go.sum
Fix of regress after golangci-lint v1.56.0:
https://github.com/Antonboom/testifylint/releases/tag/v1.1.1
https://github.com/Antonboom/testifylint/compare/v1.1.0...v1.1.1
> build(deps): bump github.com/Antonboom/testifylint from 1.1.0 to 1.1.1

- pkg/golinters/govet.go
- pkg/golinters/govet_test.go
The PR refactors `govet`'s `isAnalyzerEnabled` implementation by changing to `switch` and using `slices.Contains` instead of raw `for` loop.
> dev: refactor govet impl with slices.Contains

- .golangci.yml
- pkg/lint/lintersdb/manager.go
This PR enables `nilness` analyzer for `govet` and fixes up appearing lint issues through golangci-lint repo:
```sh
❯ golangci-lint run
pkg/lint/lintersdb/manager.go:239:15: nilness: tautological condition: non-nil != nil (govet)
if govetCfg != nil {
^
pkg/lint/lintersdb/manager.go:243:18: nilness: tautological condition: non-nil != nil (govet)
if gocriticCfg != nil {
^
pkg/lint/lintersdb/manager.go:247:17: nilness: tautological condition: non-nil != nil (govet)
if gofumptCfg != nil && gofumptCfg.LangVersion == "" {
^
```
> dev: fix govet.nilness lint issues

- .golangci.yml
- pkg/golinters/nolintlint/nolintlint.go
- pkg/lint/lintersdb/custom_linters.go
- #4002
- remove deprecated linters from "don't enable:" section.
- restore some `nolint` directives.
> dev: handle old TODO

- docs/src/docs/usage/faq.mdx
> docs: explain limitation of new-from-rev and new-from-patch

- .golangci.reference.yml
- pkg/config/linters_settings.go
- pkg/golinters/revive.go
Closes #4364
<details>
To test the configuration locally, you can use this script:
```bash
#!/bin/sh -e
rm -rf reviveexclude
mkdir reviveexclude && cd $_
go mod init helloworld
cat > main.go  <<EOF
package main
// Foo is foo.
func Foo(a string, b string) string {
return a
}
EOF
cat > main_test.go  <<EOF
package main
// Bar is bar.
func Bar(a string, b string) string {
return a
}
EOF
cat > .golangci.yml  <<EOF
linters:
enable:
- revive
revive:
enable-all-rules: true
rules:
- name: package-comments
disabled: true
- name: unused-parameter
exclude: ["TEST"]
issues:
exclude-use-default: false
max-issues-per-linter: 0
max-same-issues: 0
EOF
```
</details>
> revive: add exclude option

- pkg/golinters/govet.go
As per https://github.com/golangci/golangci-lint/discussions/4363#discussioncomment-8413385, I think it's good to clarify this. Aim is to get this on the [docs page](https://golangci-lint.run/usage/linters/#govet). I did not add a `.` at the end of the sentence as it seems the docs build does that.
> docs: improve `govet` description

- .goreleaser.yml
Fixes https://github.com/golangci/golangci-lint/discussions/4391
<details>
```console
$ docker run --rm -it golangci/golangci-lint:v1.56 sh  
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
golangci-lint has version 1.56.2 built with go1.22.0 from 58a724a0 on 2024-02-15T18:01:51Z
```
```console
$ docker run --rm -it golangci/golangci-lint:latest sh
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support" …
```
> dev: fix Docker image on tag

- .golangci.reference.yml
- go.mod
- go.sum
- pkg/golinters/copyloopvar.go
- pkg/lint/lintersdb/manager.go
- test/testdata/copyloopvar.go
I'd like to add https://github.com/karamaru-alpha/copyloopvar.
This linter detects places where loop variables are copied.
For Go 1.21(set GOEXPERIMENT=loopvar) and Go 1.22~, it is unnecessary to copy loop variables because these variables have per-iteration scope instead of per-loop scope.
cf. [Fixing For Loops in Go 1.22](https://go.dev/blog/loopvar-preview)
> For Go 1.22, we plan to change for loops to make these variables have per-iteration scope instead of per-loop scope. 
> Go 1.21 includes a preview of the scoping change. If you compile your code with GOEXPERIMENT=loopvar set in your environment, then the new semantics are applied to all loops.
> feat: add copyloopvar linter

- .golangci.reference.yml
- pkg/config/linters_settings.go
- pkg/golinters/misspell.go
- pkg/golinters/misspell_test.go
- test/testdata/configs/misspell_custom.yml
- test/testdata/misspell_custom.go
Allows to add custom typo/corrections.
> misspell: add extra-words

- install.sh
Fix install.sh usage message:
1. Use angle brackets to mark replaceable items `<bindir>` and `<tag>`. See https://stackoverflow.com/a/23242584
2. Mark that `<bindir>` is attached to `-b` option
> dev: install.sh fix usage message

- docs/src/docs/contributing/architecture.mdx
The PR makes the following changes to the `Architecture` document:
- actualizes code snippets;
- replaces whitespace with tabs in Go code;
- improve grammar slightly.
> docs: update code snippets in Architecture

- .golangci.yml
- pkg/commands/cache.go
- pkg/commands/config.go
- pkg/commands/executor.go
- pkg/commands/help.go
- pkg/commands/linters.go
- pkg/commands/root.go
- pkg/commands/run.go
- pkg/commands/version.go
- pkg/config/config.go
- pkg/config/linters_settings.go
- pkg/config/output.go
- pkg/config/reader.go
- pkg/config/run.go
- pkg/golinters/gochecknoglobals.go
- pkg/golinters/govet.go
- pkg/goutil/env.go
- pkg/lint/lintersdb/manager.go
- pkg/lint/lintersdb/validator.go
- test/bench/bench_test.go
- test/run_test.go
This is the first part of the rewrite of the command line (the `Executor`).
I split the changes into several PRs to ease the review.
This PR mainly moves, organizes, and splits the current code.
There are no major changes, but I spent a lot of time analyzing the code to be able to make the right changes to prepare for the new step.
I also removed all the deprecated flags.
They have been deprecated for multiple years (2018), so it is safe to remove them.
I made small commits to ease the review: each commit contains one change.
I recommend reviewing each commit first instead of the full change because it's easier to follow changes.
I already have the next PR, but this PR must be merged first.
related to https://github.com/golangci/golangci-lint/pull/4397#discussion_r1494525093
FYI with …
> dev: clean up Executor 

- pkg/lint/lintersdb/enabled_set.go
- pkg/lint/lintersdb/enabled_set_test.go
- pkg/lint/lintersdb/validator_test.go
- add tests on Validator
- add tests on EnableSet
I don't add tests on the Manager because I will add them in the PR with the rewrite of the Manager (this is the step next after #4412).
> dev: add tests on linterdb package

- pkg/config/issues.go
- pkg/config/issues_test.go
- pkg/config/severity_test.go
When working on #4419, I saw that those validation methods were not tested.
And I find a bug when using `path` and `path-except` at the same time.
> dev: add test on ExcludeRule and SeverityRule

- .golangci.reference.yml
- go.mod
- go.sum
- pkg/config/linters_settings.go
- pkg/golinters/copyloopvar.go
- pkg/lint/lintersdb/builder_linter.go
- test/testdata/configs/copyloopvar.yml
- test/testdata/copyloopvar.go
- test/testdata/copyloopvar_custom.go
I'm pleased to announce an upgrade [copyloopvar](https://github.com/karamaru-alpha/copyloopvar), now featuring support for the `ignore-alias` option. This new option allows the assignment of loop variables to variables with different names.
The detailed implementation can be found below. Please check it at your convenience.
https://github.com/karamaru-alpha/copyloopvar/releases/tag/v1.0.8
https://github.com/karamaru-alpha/copyloopvar/compare/v1.0.4...v1.0.8
> build(deps): bump github.com/karamaru-alpha/copyloopvar from 1.0.4 to 1.0.8

- pkg/lint/lintersdb/builder_linter.go
The PR changed replacement string for the deprecated `nosnakecase` linter from `revive(var-naming)` to `revive 'var-naming'` to be consistent with the replacement string `govet 'fieldalignment'` for `maligned`.
Before:
```
❯ golangci-lint run -E nosnakecase -E maligned -v --disable-all --no-config
WARN [runner] The linter 'nosnakecase' is deprecated (since v1.48.1) due to: The repository of the linter has been deprecated by the owner. Replaced by revive(var-naming). 
WARN [runner] The linter 'maligned' is deprecated (since v1.38.0) due to: The repository of the linter has been archived by the owner. Replaced by govet 'fieldalignment'. 
```
After:
```
❯ ./golangci-lint run -E nosnakecase -E maligned -v --disable-all --no-config
WARN [runner] The linter 'nosnakecase' is deprecated (since …
```
> dev: adjust replacement msg for nosnakecase

- .github/workflows/post-release.yml
The post-release workflow does 2 things:
- generate contributors list for the readme
- generate GitHub Action assets
And then create a PR with all the generated content.
The generation of the contributor list takes more than 1 hour and can fail.
https://github.com/golangci/golangci-lint/actions/workflows/post-release.yml
The generation of GitHub Action assets is really quick, and those assets are required to be able to install the new version from GitHub Action.
Each time it fails, I'm forced to do the work by hand.
I changed the workflow
- to not fail on a failure of the update of the readme.
- to create 2 PRs: one for the readme, and one for the assets.
So even if the readme generation fails, the assets are updated.
> dev: split post-release workflow

- .golangci.reference.yml
- .golangci.yml
- pkg/commands/flagsets.go
- pkg/commands/run.go
- pkg/config/output.go
- pkg/config/run.go
During the review of the PR about `show-stats` I missed that the value was not in the right structure.
This PR deprecated the old `run.show-stats`, and replaced it with `output.show-stats`.
The flag `--show-stats` is not impacted, it's only about the file configuration.
The old `run.show-stats` still works but with a deprecation log message.
> fix: move show-stats field from run to output

- pkg/lint/lintersdb/builder_linter.go
Based on the feedback from #4453, linters using `SuggestedFixes` are currently not autofixable due to #1779 which is what [`dupword` is using](https://github.com/Abirdcfly/dupword/blob/main/dupword.go#L136), so it shouldn't be marked as autofixable.
> docs: don't mark dupword as autofixable

- pkg/lint/runner.go
- pkg/result/processors/base_rule.go
- pkg/result/processors/exclude.go
- pkg/result/processors/exclude_rules.go
- pkg/result/processors/exclude_rules_test.go
- pkg/result/processors/exclude_test.go
- pkg/result/processors/severity.go
Merges `ExcludeRulesCaseSensitive` and `ExcludeRules` to simplify the code.
Merges `ExcludeCaseSensitive` and `Exclude` to simplify the code.
One change by commit.
Same as #4451
> dev: simplify exclude processors

- .golangci.reference.yml
- pkg/result/processors/cgo.go
The abbreviation "for example" can be written without periods as "eg" according to https://dictionary.cambridge.org/us/dictionary/english/eg. However, I chose to use the more popular variant "e.g."
> docs: fix typo in 'e.g.'

- pkg/commands/flagsets.go
- pkg/config/loader.go
This PR is a proposal for a new flag (not a file configuration).
This new flag will allow running only one specific linter without modifying the file configuration.
I named this flag `--only` but I'm not sure about this name.
I think `--force` can be ambiguous :thinking:.
This flag will override all the options of the `linters` section from the file configuration (`enable`, `disable`, `enable-all`, `disable-all`, `fast`, and `presets` ).
So you can run a linter with the right `linters-settings` section from the file without modifying the file configuration.
Before:
```bash
golangci-lint run --no-config --disable-all --enable=yourlintername
```
After:
```bash
golangci-lint run --enable-only=yourlintername
golangci-lint run --no-config --enable-only=yourlintername
```
Related to #3453, …
> feat: allow running only a specific linter without modifying the file configuration

- .golangci.reference.yml
- pkg/golinters/govet.go
- pkg/logutils/logutils.go
The PR adds the debug key `govet` that can be used to see default, all available, and enabled `govet` analyzers:
```
GL_DEBUG=govet ./golangci-lint run --enable=govet
```
Example of debug output:
```sh
❯ GL_DEBUG=govet ./golangci-lint run --enable=govet
DEBU [govet] All available analyzers (41): [appends asmdecl assign atomic atomicalign bools buildtag cgocall composites copylocks deepequalerrors defers directive errorsas fieldalignment findcall framepointer httpresponse ifaceassert loopclosure lostcancel nilfunc nilness printf reflectvaluecompare shadow shift sigchanyzer slog sortslice stdmethods stringintconv structtag testinggoroutine tests timeformat unmarshal unreachable unsafeptr unusedresult unusedwrite] 
DEBU [govet] Default analyzers (32): [appends asmdecl assign atomic bools …
```
> dev: add GL_DEBUG=govet to see enabled analyzers

- .golangci.yml
The previous explanation was not clear about the list of linters we use.
> docs: add explanation about the configuration inside repo 

- .golangci.reference.yml
- pkg/commands/flagsets.go
- pkg/config/config.go
- pkg/config/output.go
- pkg/config/output_test.go
- pkg/result/processors/sort_results.go
- pkg/result/processors/sort_results_test.go
Allows to change the sort order of the results.
This PR allows sorting by linter name, severity, and file information (file path, line, and column).
I still don't really understand the need behind this, but I found a "generic" way to do it, so I did it :shrug: 
By "generic" I mean an option not specific (like `--sort-results-by-linter`) and which can evolve without breaking changes (we can add more order types).
<details><summary>Demo</summary>
No sorting:
```console
$ go run ./cmd/golangci-lint run --out-format=tab               
pkg/lint/linter/linter.go:44:19      revive          unused-parameter: parameter 'ctx' seems to be unused, consider removing or renaming it as _
pkg/config/output.go:61:1            gochecknoinits  don't use `init` function
pkg/config/output.go:62:2 …
```
> feat: add sort-order option

- pkg/golinters/gosec.go
gosec has severities, then we can use them as value.
> feat: use gosec severities

- pkg/golinters/goanalysis/issue.go
- pkg/golinters/goanalysis/runners.go
The severity from linters needs to be stored into the cache, if not, the severity between 2 calls is not consistent.
<details><summary>To test the PR</summary>
```bash
#!/bin/sh -e
rm -rf testexample
mkdir testexample && cd $_
go mod init helloworld
cat > main.go  <<EOF
// this is a very very very very very very very very very very very very very very very very very very very very very very long line.
package main
func main() {
newDnsZone()
}
func newDnsZone() error {
return nil
}
EOF
cat > .golangci.yml  <<EOF
linters:
enable:
- revive
- errcheck
- lll
revive:
ignore-generated-header: false
severity: error
confidence: 0.8
rules:
- name: var-naming
severity: warning
severity:
default-severity: error
keep-linter-severity: true
case-sensitive: true
rules: …
```
> fix: store and read severity from linters in the cache

- .golangci.reference.yml
- pkg/commands/run.go
When I created #4441, I tested the PR but I forgot that the default value is not `0` but the number of CPUs.
But when you set explicitly the default to `0`, it panics:
```console
$ go run ./cmd/golangci-lint run -j 0
c.cfg.Run.Concurrency 0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1536a36]
goroutine 1 [running]:
go.uber.org/automaxprocs/maxprocs.Set({0xc000295c00, 0x1, 0xc000295c00?})
/home/ldez/sources/go/pkg/mod/go.uber.org/automaxprocs@v1.5.3/maxprocs/maxprocs.go:89 +0x76
github.com/golangci/golangci-lint/pkg/commands.(*runCommand).persistentPreRunE(0xc0002a0ea0, 0xc00038c908, {0x93f76a?, 0xc0003c2600?, 0xc0003c2600?})
/home/ldez/sources/go/src/github.com/golangci/golangci-lint/pkg/commands/ru …
```
> fix: panic when concurrency=0

- pkg/commands/linters.go
- pkg/commands/root.go
- pkg/commands/run.go
- pkg/printers/json.go
- pkg/result/processors/severity_test.go
- the logger wrapper is only used by the `run` command
- the configuration doesn't need to be a command constructor argument.
- the base logger should be created inside the `root` command to be able to set `verbose` option.
> dev: clean up command contructors

- pkg/commands/run.go
- pkg/lint/runner.go
- pkg/printers/printer.go
- pkg/printers/printer_test.go
the printer doesn't need the full configuration, the Output configuration is enough.
> dev: the printer just needs Output configuration

- .golangci.reference.yml
- pkg/config/severity.go
- pkg/lint/runner.go
- pkg/result/processors/processor_test.go
- pkg/result/processors/severity.go
- pkg/result/processors/severity_test.go
When I created #4452, I thought that only one linter produced issues with severities.
But it's not true as you can see here #4470
The previous option was global: affects all the linters.
The first problem is that `revive` uses `warning` and `error` as severity, but `gosec` uses `low`, `medium`, and `high`.
I don't want to convert one to another because:
- 2 severities vs 3 severities
- some tools allow only the usage of specific severity
- it's not possible to say what is the best set of values for severities
The second problem is related to the fact that some tools allow only the usage of specific severity.
The current option will keep the severity value from all linters, then the values will be a mix of the different sets.
If you need to use only one set of severities, you need to …
> feat: syntax to not override severity from linters

- .golangci.reference.yml
- go.mod
- go.sum
This reverts commit 9c492afc8396d16bb640661afecf8e2968f04c60 (#4429).
Related to https://github.com/daixiang0/gci/issues/193
> build(deps): downgrade github.com/daixiang0/gci from 0.13.0 to 0.12.3

- cmd/golangci-lint/main.go
<details><summary>Before</summary>
```console
$ make build
go build -o golangci-lint ./cmd/golangci-lint
$ ./golangci-lint version                    
golangci-lint has version (devel) built with go1.22.0 from (unknown, mod sum: "") on (unknown)
```
```console
$ go run ./cmd/golangci-lint version
golangci-lint has version (devel) built with go1.22.0 from (unknown, mod sum: "") on (unknown)
```
```console
$ go install ./cmd/golangci-lint
...
$ golangci-lint version
golangci-lint has version (devel) built with go1.22.0 from (unknown, mod sum: "") on (unknown)
```
</details>
<details><summary>With the PR</summary>
```console
$ make build                                 
go build -o golangci-lint ./cmd/golangci-lint
$ ./golangci-lint version
golangci-lint has version (devel) built with …
```
> dev: improve version output

- .custom-gcl.reference.yml
- docs/src/docs/contributing/new-linters.mdx
- docs/src/docs/plugins/module-plugins.mdx
- pkg/commands/internal/builder.go
The PR improves https://github.com/golangci/golangci-lint/pull/4437 and it's doc:
- Change to use numeric list instead of bullet list due to the previous sentence "can be added through 2 plugin systems".
- Start each line with a capital letter and end with the period for consistency.
- Remove `.` at the end of log messages for consistency with the rest of the [codebase](https://github.com/search?q=repo%3Agolangci%2Fgolangci-lint+Infof%28&type=code).
> docs: improve grammar in the custom linter article

- pkg/commands/custom.go
In the future, we might extend [misspell.extra-words](https://github.com/golangci/golangci-lint/blob/59202b196d4e212fda84e5a7419ebab54df3fec5/.golangci.next.reference.yml#L1364) in .golangci.yml with this typo.
> dev: fix a typo in the log about preserving temp

- .golangci.next.reference.yml
- cmd/golangci-lint/main.go
- docs/src/docs/usage/install/index.mdx
- pkg/commands/run.go
- pkg/result/processors/severity.go
Related to @Antonboom reviews.
> dev: minor clean up

- Makefile
- docs/package.json
- docs/static/.gitignore
- jsonschema/golangci.next.jsonschema.json
I was expecting that the store would be a proxy, but that's not the case.
I think that relying on GitHub repo and a specific branch is not a good idea.
The new URLs:
- https://golangci-lint.run/jsonschema/golangci.jsonschema.json
- https://golangci-lint.run/jsonschema/golangci.next.jsonschema.json
- https://golangci-lint.run/jsonschema/custom-gcl.next.jsonschema.json
Related to https://github.com/SchemaStore/schemastore/pull/3634
Related to #4487
> docs: publish JSON schema on golangci-lint.run

- cmd/golangci-lint/main.go
- pkg/commands/custom.go
- Use `cmd.Context()` instead of `context.Background`. Currently, they are the same but this might change in the future.
- Remove the space from the `custom` command short description for consistency with other commands in this repo.
- Capitalize the stderr output message and add a semicolon for clarity:
- before:
```
> ./custom-golangci-lint run
...
failed executing command with error build linters: plugin(someplugin): plugin "someplugin" not found
```
- after: 
```
> ./custom-golangci-lint run
...
Failed executing command with error: build linters: plugin(someplugin): plugin "someplugin" not found
```
> dev: use `cmd.Context` inside custom command

- pkg/commands/root.go
The PR defines the global flag `help (h)` to override the default help flag from [the cobra](https://github.com/spf13/cobra/blob/v1.7.0/command.go#L1136C1-L1151C1).
1. Root:
- Before:
- After:
2. Nested command:
- Before:
- After:
> dev: display help message with green color

- README.md
This PR improves the second sentence in README:
- fixes the grammar `IDE` -> `IDEs`;
- slightly rewrite the whole sentence.
> docs: improve "about golangci-lint" in README

- pkg/config/output.go
- pkg/config/output_test.go
- pkg/result/processors/sort_results.go
- pkg/result/processors/sort_results_test.go
Review from #4467 by @Antonboom
> dev: clean up

- pkg/result/processors/sort_results.go
- pkg/result/processors/sort_results_test.go
Replace all comparator implementations with one (`comparator`) and simple functions.
Less code but the same behavior.
> chore: simplify comparators

- .golangci.yml
- pkg/fsutils/fsutils.go
- pkg/golinters/goanalysis/runner.go
- pkg/golinters/goanalysis/runners.go
- pkg/golinters/nolintlint/nolintlint.go
- pkg/golinters/testpackage.go
- pkg/lint/load.go
- pkg/lint/runner.go
- pkg/logutils/out.go
- pkg/printers/printer.go
- pkg/result/processors/identifier_marker.go
- pkg/result/processors/identifier_marker_test.go
- pkg/result/processors/max_per_file_from_linter.go
- pkg/result/processors/nolint.go
- pkg/result/processors/nolint_test.go
- pkg/result/processors/uniq_by_line.go
- scripts/website/expand_templates/linters.go
The PR reformats code with `gofumpt` linter.
> dev: reformat code with gofumpt

- pkg/golinters/gochecknoglobals.go
The description of the `gochecknoglobals` is currently verbose:
I propose to condense it in this PR.
> docs: shorten description for gochecknoglobals linter

- go.mod
- go.sum
https://github.com/golangci/plugin-module-register/compare/f76272ec86ee...v0.1.0
**This update is done by hand because dependabot is not allowed to update dependencies from golangci org.**
> build(deps): bump github.com/golangci/plugin-module-register to 0.1.0

- pkg/golinters/gocritic.go
- pkg/lint/lintersdb/builder_linter.go
Since the previous refactor of the commands, the configuration is fully loaded before the build of the linters, so we don't need a closure.
The configuration is inside the linter context, we can use it instead of passing it as a parameter.
> dev: review config path usage inside gocritic

- docs/src/docs/contributing/workflow.mdx
- docs/src/docs/index.mdx
- docs/src/docs/welcome/faq.mdx
- docs/src/docs/welcome/install.mdx
- docs/src/docs/welcome/integrations.mdx
This PR fixes broken links on the https://golangci-lint.run/ found by the [linkchecker](https://linkchecker.github.io/linkchecker/).
<details>
<summary>linkchecker output</summary>
```
❯ linkchecker --no-warnings https://golangci-lint.run/
INFO linkcheck.cmdline 2024-03-15 21:14:06,351 MainThread Checking intern URLs only; use --check-extern to check extern URLs.
LinkChecker 10.4.0
Copyright (C) 2000-2016 Bastian Kleineidam, 2010-2023 LinkChecker Authors
LinkChecker comes with ABSOLUTELY NO WARRANTY!
This is free software, and you are welcome to redistribute it under
certain conditions. Look at the file `COPYING' within this distribution.
Read the documentation at https://linkchecker.github.io/linkchecker/
Write comments and bugs to https://github.com/linkchecker/linkchecker/issues
Start …
```
> docs: fix website broken links

- .golangci.next.reference.yml
- .golangci.reference.yml
Sync settings here and in https://github.com/ldez/tagliatelle?tab=readme-ov-file#as-a-golangci-lint-linter
> docs: add more tagliatelle examples

- pkg/commands/run.go
- pkg/config/run.go
- pkg/lint/runner.go
After #4516, this PR removes completely the usage of `cfg.Run.Args`.
Now, the `Run` structure contains only real configuration.
> dev: remove Run.Args

- .golangci.next.reference.yml
- jsonschema/golangci.next.jsonschema.json
- pkg/commands/flagsets.go
- pkg/config/loader.go
- pkg/config/output.go
- pkg/config/output_test.go
- pkg/printers/printer.go
- pkg/printers/printer_test.go
This PR improves the syntax inside the configuration file to specify output formats.
The previous syntax has been defined when only the format type was an option.
However, the syntax has evolved to support output paths and multiple formats.
```yml
output:
format: "checkstyle:report.xml,json:stdout,colored-line-number"
```
This is a flag syntax friendly but not a file syntax friendly.
I propose this new syntax:
```yml
output:
formats:
- format: checkstyle
path: report.xml
- format: json
path: stdout
- format: colored-line-number
```
The CLI flag keeps the same syntax.
```
--out-format=checkstyle:report.xml,json:stdout,colored-line-number
```
To keep this new option compatible with the GitHub Action, the CLI must override the configuration file.
The previous field `output.format` is …
> feat: new output.formats file configuration syntax

- build/buildx-alpine.Dockerfile
- build/buildx.Dockerfile
The mode `auto` to download and use a Go version higher than the version inside the Docker image.
https://go.dev/doc/toolchain
Fixes #4239
> fix: use GOTOOLCHAIN=auto inside the Docker images

- pkg/config/loader.go
`UseDefaultExcludeDirs` is true by default but `UseDefaultSkipDirs` is now false by default.
> fix: deprecation message related to UseDefaultSkipDirs

- pkg/golinters/govet.go
If you are using this kind of configuration:
```yml
govet:
check-shadowing: true
enable-all: true
disable:
- fieldalignment
linters:
enable:
- govet
```
An error will appear:
```console
$ ./golangci-lint run ./...                                                     
Error: govet: enable-all and enable can't be combined
Failed executing command with error: govet: enable-all and enable can't be combined
```
This a new problem related to the previous refactor: the validation doesn't happen at the same time as before (and it's a good thing).
Inside the `govet` implementation, the pass `shadow` is added to `enable` when `check-shadowing` is true, but as it's a pointer to the configuration, then the real configuration is also modified.
Note: `check-shadowing` …
> govet: fix check-shadowing

- pkg/lint/context.go
90% of the contexts that lead to `no go files to analyze` error are related to missing `go mod tidy`.
A sample of issues on the topic:
- https://github.com/golangci/golangci-lint/issues/4168
- https://github.com/golangci/golangci-lint/discussions/3371
- https://github.com/golangci/golangci-lint/issues/3335
- https://github.com/golangci/golangci-lint/issues/1855
- https://github.com/golangci/golangci-lint/issues/1833
- https://github.com/golangci/golangci-lint/issues/1784
- https://github.com/golangci/golangci-lint/issues/870
- https://github.com/golangci/golangci-lint/issues/825
Before:
```console
$ golangci-lint run ./...                           
ERRO Running error: context loading failed: no go files to analyze 
```
After:
```console
$ ./golangci-lint run ./... …
```
> feat: improve 'no go files to analyze' message

- .golangci.next.reference.yml
- .golangci.yml
- jsonschema/golangci.next.jsonschema.json
- pkg/config/linters_settings.go
- pkg/config/loader.go
- test/testdata/configs/govet.yml
It was "unofficially" deprecated since v1.19 (2019) (inside #697).
https://github.com/golangci/golangci-lint/pull/697/files#diff-5144159bbaf9571c0fb12b9077a23f5dd046eda75d10c4d02c8317d071b54019R124
I think it's time to add a warning to deprecate it.
The deprecation message is complex because there are several possible configurations:
- `check-shadowing` + `enable-all`
- `check-shadowing` + `disable-all`
- `check-shadowing` + `enable`
- `check-shadowing` + `disable`
> govet: add a warning about the deprecation of check-shadowing

- pkg/commands/custom.go
- pkg/commands/linters.go
- pkg/commands/run.go
Some help displays are huge (e.g. `run`), and so it's too big to be useful when an error occurs.
I silenced some verbose help commands.
```go
// SilenceUsage is an option to silence usage when an error occurs.
SilenceUsage bool
```
> dev: silence help on some commands usage on error

- .golangci.next.reference.yml
- .golangci.reference.yml
- jsonschema/golangci.jsonschema.json
- jsonschema/golangci.next.jsonschema.json
Also added description for the values.
> docs: fix default value for sloglint no-global

- docs/src/docs/welcome/quick-start.mdx
The mix of file and package/directory (as documented inside the [quick start](https://golangci-lint.run/welcome/quick-start/)) doesn't work as expected.
Same thing for the usage of multiple files from different packages.
<details><summary>Examples</summary>
```console
$ golangci-lint run main.go          
main.go:11:5: Error return value is not checked (errcheck)
Bar()
^
```
```console
$ golangci-lint run pkga/... main.go
ERRO Running error: context loading failed: failed to load packages: failed to load packages: failed to load with go/packages: -: named files must be .go files: ./pkga/...
```
```console
$ golangci-lint run pkga main.go 
ERRO Running error: context loading failed: failed to load packages: failed to load packages: failed to load with go/packages: -: named files must be …
```
> docs: remove invalid example about mixing files and directory

- .golangci.yml
- pkg/config/linters_settings.go
- pkg/config/loader.go
- pkg/config/run.go
- pkg/golinters/godot.go
Currently, there are no warnings related to deprecated linter options.
> fix: display warnings on deprecated linter options

- pkg/printers/teamcity.go
- pkg/printers/teamcity_test.go
The [Inspection Type](https://www.jetbrains.com/help/teamcity/service-messages.html#Inspection+Type) is used in the TeamCity printer. The message type should be `inspectionType` as the doc specified, but the golangci-lint uses `InspectionType`(capitalized "I").
I'm not sure if it works with previous TeamCity versions, I'm currenly on "TeamCity Enterprise 2023.11.3 (build 147512)" and it doesn't work for me. Changing the `InspectionType` to `inspectionType` did the trick.
Update the TeamCity printer to have it align with the specification, and avoid any surprise in the future.
> fix: the TeamCity inspectionType service message

- pkg/config/output.go
One format was missing inside `AllOutputFormats` list.
```console
$ golangci-lint run --out-format=colored-tab                                                                                                                                                         
Error: unsupported output format "colored-tab"
Failed executing command with error: unsupported output format "colored-tab"
```
> fix: missing output format

- .markdownlint.yaml
The [markdownlint](https://github.com/DavidAnson/markdownlint) is not used in golangci-lint GitHub workflows for linting Markdown files, thus the `markdownlint.yaml` can be deleted.
> dev: remove unused markdownlint config file

- .golangci.yml
- pkg/commands/linters.go
> fix: hide useless warning

- pkg/commands/config.go
- pkg/commands/linters.go
- pkg/commands/run.go
- pkg/config/loader.go
- pkg/lint/package.go
- pkg/lint/package_test.go
- pkg/result/processors/autogenerated_exclude.go
- pkg/result/processors/invalid_issue.go
- pkg/result/processors/skip_dirs.go
- pkg/result/processors/skip_dirs_test.go
There is a mix between args from `os.Args` and args from Cobra.
The PR removes the usage `os.Args`, cleans the related functions, and adds tests.
> dev: clean code arround CLI args usage

- pkg/golinters/internal/diff_test.go
- pkg/lint/lintersdb/validator.go
- pkg/lint/lintersdb/validator_test.go
- pkg/logutils/mock.go
Displays a warning when using alternative names.
I used the `Validator` because the linter names and alternative names are required for the analysis, then it cannot be done inside the `Loader`.
FYI: `unused`, `gosimple`, `staticcheck` cannot be merged as one "linter" because their requirements are completely different.
Fixes #357
Related #3746
> feat: deprecate usage of linter alternative names

- test/testdata/fix/in/tagalign.go
- test/testdata/fix/out/tagalign.go
This PR adds a fix integration test for `tagalign`:
```
T=tagalign.go make test_fix
```
> dev: add fix test for tagalign linter

- .golangci.yml
- pkg/golinters/misspell_test.go
- pkg/result/processors/autogenerated_exclude_test.go
- pkg/result/processors/skip_files_test.go
The PR enables `testifylint` for this repo.
<details>
<summary>golangci-lint run</summary>
```
pkg/golinters/misspell_test.go:32:2: expected-actual: need to reverse actual and expected values (testifylint)
assert.Equal(t, replacer.Replacements, expected)
^
pkg/result/processors/autogenerated_exclude_test.go:255:4: require-error: for error assertions use require (testifylint)
assert.EqualError(t, err, test.expected)
^
pkg/result/processors/skip_files_test.go:52:2: require-error: for error assertions use require (testifylint)
assert.Error(t, err)
^
```
</details>
> dev: enable testifylint linter

- test/testdata/fix/in/mirror.go
- test/testdata/fix/out/mirror.go
This PR adds a fix integration test for `mirror`:
```
T=mirror.go make test_fix
```
> dev: add fix test for mirror linter

- .pre-commit-hooks.yaml
Add this as a way to easily ensure configs stay valid. Filenames are not passed to the hook, this means For the default case (config in one of the default searched files), the config is picked up automatically and there's nothing extra to configure. For the case of a non-standard config setup the hook can be configured like
repos:
-   repo: https://github.com/golangci/golangci-lint
rev: v1.57.2
hooks:
-   id: golangci-lint-config-verify
files: \.golangci-config\.yaml
args: ['--config', '.golangci-config.yaml']
> Add `pre-commit` hook to run `config verify`

- .golangci.next.reference.yml
- go.mod
- go.sum
- jsonschema/golangci.next.jsonschema.json
- pkg/golinters/fatcontext.go
- pkg/lint/lintersdb/builder_linter.go
- test/testdata/fatcontext.go
As described in a blog post I wrote (https://gabnotes.org/fat-contexts/), we've been bitten by contexts not shadowed inside loops.
This linter addresses this issue.
Github repo: https://github.com/Crocmagnon/fatcontext
> feat: add fatcontext linter

- .golangci.yml
- pkg/commands/config.go
- pkg/commands/linters.go
- pkg/commands/run.go
- pkg/config/config.go
- pkg/config/loader.go
- pkg/lint/lintersdb/validator.go
Instead of filling in useless elements, add an option to check or not the deprecation.
Related to #4587 and #4527
> dev: option to not check deprecation

- pkg/commands/config_verify.go
`jsonschema` uses [the default HTTP client](https://github.com/santhosh-tekuri/jsonschema/blob/v5.3.1/httploader/httploader.go#L20) for loading JSON schemas, which doesn't have request timeouts. This PR overrides the global HTTP client from the library with a client that includes a timeout.
> dev: set timeout for loading JSON schema

- docs/src/docs/contributing/new-linters.mdx
The text was not corresponding to the link.
Opening "Go Plugin System" was loading "Module Plugin System", and vice-versa .
> docs: fix links to Module and Go Plugins

- jsonschema/golangci.jsonschema.json
- jsonschema/golangci.next.jsonschema.json
> fix: JSON schema about severities

- .github/workflows/tag.yml
- .goreleaser.yml
- docs/src/docs/welcome/install.mdx
Inspired by:
- https://github.com/algolia/cli/blob/01a0555a0fc4f2678204f25013724245c9106ba6/.goreleaser.yml#L108
- https://github.com/algolia/cli/blob/01a0555a0fc4f2678204f25013724245c9106ba6/.github/workflows/releases.yml#L23
There is not a lot of usage of this goreleaser feature (about 35 repo): https://github.com/search?q=path%3A%2F%5C.goreleaser.yml%2F+chocolateys&type=code
I tried to publish previous versions by using goreleaser locally (it's not trivial to set up a stack on Docker/Linux).
- [1.56.2](https://community.chocolatey.org/packages/golangci-lint/1.56.2) -> failure because the verification bot doesn't use the right archive (`.nupkg`) even if I update it.
- [1.57.0](https://community.chocolatey.org/packages/golangci-lint/1.57.0) -> success
- …
> chore: add chocolatey

- docs/src/docs/index.mdx
- docs/src/docs/welcome/integrations.mdx
See https://github.blog/2022-06-08-sunsetting-atom/
> docs: remove deprecated Atom from Editor Integrations

- docs/src/docs/welcome/faq.mdx
This PR improves links for creating GitHub issues when a user opens it from:
- https://golangci-lint.run/welcome/faq/#golangci-lint-doesnt-work
- https://golangci-lint.run/welcome/faq/#how-do-you-add-a-custom-linter
> docs: use proper templates when creating GitHub issues

- pkg/commands/flagsets.go
```diff
--- 1.txt       2024-04-11 22:35:51
+++ 2.txt       2024-04-11 22:36:24
@@ -11,7 +11,8 @@
-E, --enable strings                 Enable specific linter
--enable-all                     Enable all linters
--fast                           Enable only fast linters from enabled linters set (first run won't be fast)
-  -p, --presets strings                Enable presets (bugs|comment|complexity|error|format|import|metalinter|module|performance|sql|style|test|unused) of linters. Run 'golangci-lint help linters' to see them. This option implies option --disable-all
+  -p, --presets strings                Enable presets (bugs|comment|complexity|error|format|import|metalinter|module|performance|sql|style|test|unused) of linters.
+                                       Run 'golangci-lint help …
```
> dev: improve formatting and description in flagsets

- pkg/commands/flagsets.go
- pkg/config/issues.go
Uses more explicit patterns, and improves the CLI render of the exclusions.
<details>
<summary>before</summary>
</details>
<details>
<summary>with the PR</summary>
</details>
> dev: clean DefaultExcludePatterns and improve CLI render

- pkg/commands/help.go
<details>
<summary>before</summary>
```
Enabled by your configuration linters:
bodyclose: checks whether HTTP response body is closed successfully [fast: false, auto-fix: false]
depguard: Go linter that checks if package imports are in a list of acceptable packages [fast: true, auto-fix: false]
dogsled: Checks assignments with too many blank identifiers (e.g. x, _, _, _, := f()) [fast: true, auto-fix: false]
dupl: Tool for code clone detection [fast: true, auto-fix: false]
errcheck: errcheck is a program for checking for unchecked errors in Go code. These unchecked errors can be critical bugs in some cases [fast: false, auto-fix: false]
errorlint: errorlint is a linter for that can be used to find code that will cause problems with the error wrapping scheme introduced in Go 1.13. [fast: …
```
> dev: remove alternatives names from CLI help

- pkg/commands/help.go
- scripts/website/expand_templates/linters.go
- scripts/website/types/types.go
Sorts deprecated linters at the end of lists.
```
usestdlibvars: A linter that detect the possibility to use variables/constants from the Go standard library. [fast: true, auto-fix: false]
varnamelen: checks that the length of a variable's name matches its scope [fast: false, auto-fix: false]
wastedassign: Finds wasted assignment statements [fast: false, auto-fix: false]
wrapcheck: Checks that errors returned from external packages are wrapped [fast: false, auto-fix: false]
wsl: add or remove empty lines [fast: true, auto-fix: false]
zerologlint: Detects the wrong usage of `zerolog` that a user forgets to dispatch with `Send` or `Msg` [fast: false, auto-fix: false]
deadcode [deprecated]: Deprecated [fast: false, auto-fix: false]
exhaustivestruct [deprecated]: Deprecated [fast: false, …
```
> dev: sorts deprecated linters at the end of lists

- pkg/result/processors/invalid_issue.go
- pkg/result/processors/invalid_issue_test.go
Related to https://github.com/golangci/golangci-lint/issues/4639#issuecomment-2053660195
> fix: keep only typecheck issues

- pkg/golinters/errcheck/errcheck.go
It's the same fix as in the https://github.com/golangci/golangci-lint/commit/7ad7949ca9bf236ee4f349de2cb384d5f7c90b08.
> dev: close errcheck exclude file

- .golangci.yml
- pkg/lint/lintersdb/builder_plugin_go.go
`revive` is already included in `.golangci.yaml`. This PR only enables one revive's rule:
```
Updated 1 path from the index
❯ golangci-lint run
pkg/lint/lintersdb/builder_plugin_go.go:51:10: indent-error-flow: if block ends with a return statement, so drop this else and outdent its block (revive)
} else {
linters = append(linters, lc)
}
```
> dev: eliminate redundant indentation

- pkg/lint/lintersdb/builder_linter.go
[execinquery](https://github.com/1uf3/execinquery) has been archived by the author.
FYI, I discussed this privately with the author.
> execinquery: deprecation

- .github/ISSUE_TEMPLATE/bug_report.yml
- pkg/lint/lintersdb/builder_plugin_go.go
This PR fixes the website links in the bug issue template and the warning log for the deprecated analyzer plugin.
> dev: fix broken links to the website

- pkg/commands/internal/builder.go
> fix: use plugin version

- install.sh
This PR fixes [shellcheck](https://www.shellcheck.net/) linter issues:
- [Quote this to prevent word splitting](https://www.shellcheck.net/wiki/SC2046)
- [In POSIX sh, == in place of = is undefined](https://www.shellcheck.net/wiki/SC3014)
- [Double quote to prevent globbing and word splitting](https://www.shellcheck.net/wiki/SC2086)
The function `log_prefix()` is removed because it's redefined below.
<details>
<summary>Details</summary>
```
❯ shellcheck install.sh
In install.sh line 154:
echo "$0"
^-------^ SC2317 (info): Command appears to be unreachable. Check usage (or ignore if invoked indirectly).
In install.sh line 203:
sunos) [ $(uname -o) == "illumos" ] && os=illumos ;;
^---------^ SC2046 (warning): Quote this to prevent word splitting.
^-- SC3014 (warning): In POSIX sh, == in …
```
> dev: fix shellcheck lint issues

- .goreleaser.yml
- reorganize the file
- add the changelog header automatically
> dev: improve goreleaser configuration

- pkg/golinters/typecheck.go
- pkg/lint/lintersdb/builder_linter.go
- pkg/lint/lintersdb/manager.go
- pkg/lint/lintersdb/manager_test.go
- test/enabled_linters_test.go
Currently, there are 2 problems:
1. `typecheck` uses `LoadModeTypesInfo` and `WithLoadForGoAnalysis`.
So the load mode of the linter config for the `metalinter` is always `LoadModeTypesInfo` and never `LoadModeSyntax`.
2. the `metalinter` has a hardcoded call to `WithLoadForGoAnalysis`, then the types are always loaded.  
As a consequence, the "fast" linters (like `lll`, `gofmt`, `misspell`, etc.) are slower than expected when either they are running alone or only "fast" linters are run.
This PR changes the config linter load mode of `typecheck` to `LoadModeNone` and removes `WithLoadForGoAnalysis` for this fake linter.
The `metalinter` goanalysis load mode is computed based on linters.
`typecheck` doesn't need an explicit load mode because it is never run alone, then at the end, the load …
> fix: speed up "fast" linters

- .golangci.next.reference.yml
- go.mod
- go.sum
- jsonschema/golangci.next.jsonschema.json
- pkg/golinters/canonicalheader/canonicalheader.go
- pkg/golinters/canonicalheader/canonicalheader_test.go
- pkg/golinters/canonicalheader/testdata/canonicalheader.go
- pkg/lint/lintersdb/builder_linter.go
[canonicalheader](https://github.com/lasiar/canonicalHeader) analyzes code and reports or fixes non-canonical header key in `net/http.Header`, [doc](https://pkg.go.dev/net/http#CanonicalHeaderKey).
The linter suggest canonical header:
```go
http.Header{}.Get("Test-Header")
```
instead of non-canonical header:
```go
http.Header{}.Get("TeSt-HeAdEr")
```
This change also speeds up the code a little, benchmark from repo:
```
name             time/op
Canonical-10     29.7ns ± 4%
NonCanonical-10  69.0ns ± 1%
name             alloc/op
Canonical-10      0.00B     
NonCanonical-10   16.0B ± 0%
name             allocs/op
Canonical-10       0.00     
NonCanonical-10    1.00 ± 0%
```
Now, the linter works only with value `net/http.Header` (not pointer) and with string literal.
----
The reason I …
> Add new linter canonicalheader

- pkg/lint/runner.go
- pkg/result/processors/base_rule.go
- pkg/result/processors/exclude.go
- pkg/result/processors/exclude_rules.go
- pkg/result/processors/exclude_rules_test.go
- pkg/result/processors/exclude_test.go
- pkg/result/processors/severity.go
- pkg/result/processors/severity_test.go
Removes `BaseRule`, `ExcludeRule`, `SeverityRule` duplications.
This deduplication allows simplification of the construction of severity processor, exclude processor, and exclude rules processor.
> dev: removes BaseRule, ExcludeRule, SeverityRule duplications

- pkg/lint/linter/config.go
- pkg/lint/linter/linter.go
- pkg/lint/lintersdb/builder_linter.go
- pkg/lint/lintersdb/manager.go
- scripts/website/dump_info/main.go
- scripts/website/expand_templates/thanks.go
- test/enabled_linters_test.go
This PR follows the [linter deprecation cycle](https://golangci-lint.run/product/roadmap/#linter-deprecation-cycle) and then the old deprecated linters will log an error (step 2) instead of a warning.
Also, the deprecated linters with the level `DeprecationError` will not be enabled when using `enable-all`.
The linters recently deprecated like `execinquery` or `gomnd` will log a warning and are still enabled when using `enable-all`.
As the documentation explains, the deprecated linters, not depending on the level, are still removed from `presets`.
> feat: log an error when using previously deprecated linters

- .golangci.yml
- pkg/config/linters_settings.go
- pkg/config/loader.go
The PR marks `errcheck.ignore` lint option as deprecated. See #332 and https://github.com/kisielk/errcheck#the-deprecated-method.
Related to #4673
> dev: deprecate errcheck.ignore option

- Makefile
In environment where CGO_ENABLED=0, some tests that require CGO will fail, in example
```
<REDACTED>
=== RUN   TestCgoOk
level=info msg="[test] ran [/tmp/TestCgoOk3811517097/001/golangci-lint
run --internal-cmd-test --allow-parallel-runners --no-config
--timeout=3m --enable-all -D nosnakecase --go=1.22 testdata/cgo] in
1.032596905s"
run_test.go:111:
Error Trace: /home/ms/go/src/git.sr.ht/~shulhan/golangci-lint/test/testshared/runner.go:282
/home/ms/go/src/git.sr.ht/~shulhan/golangci-lint/test/run_test.go:111
Error:          Not equal:
expected: ""
actual  : "level=error msg=\"[linters_context] typechecking error: build constraints exclude all Go files in /home/ms/go/src/git.sr.ht/~shulhan/golangci-lint/test/testdata/cgo\"\n"
<REDACTED>
```
> dev: set CGO_ENABLED=1 when running "test" task

- .golangci.next.reference.yml
- go.mod
- go.sum
- jsonschema/golangci.next.jsonschema.json
- pkg/golinters/nilnil/testdata/nilnil.go
Description here:
https://github.com/Antonboom/nilnil/releases/tag/v0.1.9
Full Changelog: https://github.com/Antonboom/nilnil/compare/v0.1.8...v0.1.9
`uintptr` and `unsafeptr` enabled by default (potentially breaking change) as really rare case (and I provide opportunity to tune config anyway).
> build(deps): bump github.com/Antonboom/nilnil from 0.1.8 to 0.1.9

- .golangci.next.reference.yml
- go.mod
- go.sum
- jsonschema/golangci.next.jsonschema.json
- pkg/config/linters_settings.go
- pkg/goanalysis/linter.go
- pkg/golinters/testifylint/testifylint.go
- Less false positives
- New checker `negative-positive`
- New option `go-require.ignore-http-handlers`
https://github.com/Antonboom/testifylint/releases/tag/v1.3.0
> build(deps): bump github.com/Antonboom/testifylint from 1.2.0 to 1.3.0

- .golangci.next.reference.yml
- jsonschema/golangci.next.jsonschema.json
- pkg/config/output.go
- pkg/printers/printer.go
- pkg/printers/sarif.go
- pkg/printers/sarif_test.go
This work supports exporting Sarif file format. It's a common enough format and I figured I'd help out by adding it. :)
Sarif documentation:
https://github.com/microsoft/sarif-tutorials/blob/main/docs/2-Basics.md#results
https://docs.oasis-open.org/sarif/sarif/v2.1.0/cs01/schemas/sarif-external-property-file-schema-2.1.0.json
fixes #2866
> Support Sarif output

- pkg/config/loader.go
- pkg/config/output.go
- pkg/printers/githubaction.go
Related to https://github.com/golangci/golangci-lint/issues/4695#issuecomment-2097087189
Related to #4700
> feat: deprecate github-actions format

- .golangci.next.reference.yml
- .golangci.reference.yml
- jsonschema/golangci.jsonschema.json
- jsonschema/golangci.next.jsonschema.json
Include `html` as a valid value for the output format into schema for the configuration file.
> chore: add html to the JSONSchema 

- docs/src/docs/product/roadmap.mdx
- pkg/lint/lintersdb/validator.go
- test/run_test.go
Follows https://github.com/golangci/golangci-lint/pull/4681
The log should be closed to the `Manager` because we need the list of linter's names defined inside the `disable` configuration and the `LinterConfigs` to check the state of the linter.
The warning will only appear on the `DeprecationError` level of deprecation.
> feat: add warning about disabled and deprecated linters (level 2)

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- adds emojis
- adds link to Slack
> dev: improve issue chooser

- go.mod
- go.sum
- pkg/config/loader.go
The update is done by hand because gosec is not released yet, and this is an important performance issue.
This update is safe because it only contains the Go version fix.
https://github.com/securego/gosec/compare/v2.20.0...5f0084eb01a9
Comparison with v1.58.1:
```
Benchmark 1: ./golangci-lint run --print-issued-lines=false --enable-only gosec
Time (mean ± σ):     569.2 ms ±  21.2 ms    [User: 2152.1 ms, System: 956.9 ms]
Range (min … max):   540.0 ms … 613.3 ms    10 runs
Benchmark 2: ./golangci-lint-v1.58.1 run --print-issued-lines=false --enable-only gosec
Time (mean ± σ):     536.4 ms ±  28.1 ms    [User: 2158.7 ms, System: 886.2 ms]
Range (min … max):   503.9 ms … 595.6 ms    10 runs
```
Comparison with v1.58.2:
```
Benchmark 1: ./golangci-lint run --print-issued-lines=false …
```
> build(deps): bump github.com/securego/gosec/v2 from 2.20.0 to 5f0084eb01a9

- pkg/commands/run.go
```console
$ golangci-lint run --cpu-profile-path gcil.pprof
Error: can't start CPU profiling: cpu profiling already in use
Failed executing command with error: can't start CPU profiling: cpu profiling already in use
```
> dev: fix double call to startTracing

- pkg/printers/sarif.go
- pkg/printers/sarif_test.go
if no issue is found, the sarif printer will produce a `nil` as a result, and `encoding/json` makes it a `null`, which is required to be an array in sarif format.
see https://github.com/Zxilly/go-size-analyzer/actions/runs/9254489826/job/25456396105 for real-world errors.
> fix: init empty result slice for SARIF printer

- Makefile
- scripts/bench/bench_local.sh
- scripts/bench/bench_version.sh
- scripts/bench/readme.md
Adds 2 targets to benchmark a linter.
```bash
LINTER=gosec VERSION=v1.59.0 make bench_local
```
```bash
LINTER=gosec VERSION_OLD=v1.58.2 VERSION_NEW=v1.59.0 make bench_version
```
It uses [Hyperfine](https://github.com/sharkdp/hyperfine).
It's not really possible to automate that because it will take too much time to run, but at least we will be able to benchmark manually a PR.
<details>
<summary>Demo</summary>
```console
$ LINTER=misspell VERSION_OLD=v1.57.2 VERSION_NEW=v1.59.0 make bench_version
golangci/golangci-lint info checking GitHub for tag 'v1.57.2'
golangci/golangci-lint info found version: 1.57.2 for v1.57.2/linux/amd64
golangci/golangci-lint info installed ./temp-v1.57.2/golangci-lint
golangci/golangci-lint info checking GitHub for tag 'v1.59.0'
golangci/golangci-lint info …
```
> dev: add targets to benchmark a linter

- pkg/commands/run.go
- pkg/commands/version.go
Displays the golangci-lint version in verbose mode.
This allows us to check the effective version inside issues.
> dev: display version in verbose mode

- pkg/printers/sarif.go
- pkg/printers/sarif_test.go
Some linters won't provider column value for issue, under this situation we should set it to 1.
For real world error see https://github.com/Zxilly/go-size-analyzer/actions/runs/9300840788/job/25597744381
> fix: SARIF format require issue column >= 1

- pkg/golinters/lll/lll.go
- test/run_test.go
Pardon if this has been discussed before, I couldn't find it in the issue/PR list.
As a user, I find it disorienting when tools inform me that I have made a mistake but do not offer any insights into how to resolve the issue.
In this case in particular, we have all the information, but then require the user to know the defaults and to traverse the config overrides.
It'd be nice to just provide this information. Impact to existing users should be minimal, including data transfer or storage of logs in CI, since teams who are already in compliance would not get the new log component, and teams who are not in compliance yet would get the message once and then be done.
Happy to circle back if there's prior art for how this information should be displayed.
Thanks!
> lll: Advertise max line length instead of just reporting failure

- .golangci.next.reference.yml
- go.mod
- go.sum
- jsonschema/golangci.next.jsonschema.json
- pkg/config/linters_settings.go
- pkg/golinters/testifylint/testdata/testifylint.go
- pkg/golinters/testifylint/testdata/testifylint_formatter_only.go
- pkg/golinters/testifylint/testdata/testifylint_formatter_only.yml
- pkg/golinters/testifylint/testifylint.go
https://github.com/Antonboom/testifylint/releases/tag/v1.4.0
Full Changelog: https://github.com/Antonboom/testifylint/compare/v1.3.1...v1.4.1
> build(deps): bump github.com/Antonboom/testifylint from 1.3.1 to 1.4.1

- .golangci.next.reference.yml
- .golangci.reference.yml
`whole-files` is related to new-from-rev and new-from-patch, it's better to have it near of those options.
> docs: move whole-files near of new-from-xxx

- pkg/golinters/revive/revive.go
supersedes #4816
FYI, this has no impact on performances.
> dev: improve revive construction

- pkg/printers/sarif.go
- pkg/printers/sarif_test.go
https://docs.oasis-open.org/sarif/sarif/v2.1.0/errata01/os/sarif-v2.1.0-errata01-os-complete.html#_Toc141790898
level can only be `none, note, warning, error`, some linter like `gosec` may report something like `high`
For real-world error, see https://github.com/Zxilly/go-size-analyzer/actions/runs/9586342361/job/26434117667
> fix: sanitize level property for SARIF

- scripts/bench/bench_local.sh
- scripts/bench/bench_version.sh
- use a warmup (limit fs side effect on the first run)
- use `go build` (more information about the [linker](https://pkg.go.dev/cmd/link))
- use named runs
> dev: improve benchmark scripts

- scripts/gen_github_action_config/go.mod
- scripts/gen_github_action_config/go.sum
- scripts/gen_github_action_config/main.go
- update dependencies
- re-organize the code
- add empty lines to improve readability
- improve error messages
> dev: clean gen_github_action_config

- docs/src/docs/contributing/workflow.mdx
- docs/src/docs/usage/linters.mdx
- scripts/website/expand_templates/linters.go
This PR creates an invisible span with ID to generate an anchor for all linter names.
Result:
link example: `http://localhost:8000/usage/linters/#bodyclose`
This also fixes:
- "back to the top" link for linter without repo (ex: [lll](https://golangci-lint.run/usage/linters/#lll))
- the behavior of "back to the top" link when the repo icon is not on the same line as the linter name (ex: [staticcheck](https://golangci-lint.run/usage/linters/#staticcheck)) 
Fixes #4841
> docs: add link on linter without configuration

- .github/new-linter-checklist.md
The PR improves the `.github/new-linter-checklist.md` file.
> docs: improve grammar of new linter checklist

- pkg/lint/runner.go
The current log:
```
INFO [runner] Processors filtering stat (out/in): skip_files: 13145/13145, cgo: 19030/19030, exclude: 13145/13145, invalid_issue: 13145/19030, skip_dirs: 13145/13145, autogenerated_exclude: 13145/13145, nolint: 0/13145, filename_unadjuster: 19030/19030, path_prettifier: 13145/13145, identifier_marker: 13145/13145, exclude-rules: 13145/13145
```
The "out/in" is unexpected, I think it's better to change the order to `in/out`.
> feat: improve processors filtering stats

- jsonschema/golangci.next.jsonschema.json
- pkg/config/linters_settings.go
- pkg/config/loader.go
- pkg/golinters/unused/unused.go
> unused: remove exported-is-used option

- .github/workflows/documentation.yml
- .github/workflows/post-release.yml
- .github/workflows/pr-documentation.yml
- .github/workflows/pr-extra.yml
- .github/workflows/pr.yml
- .github/workflows/tag.yml
- .goreleaser.yml
- build/buildx-alpine.Dockerfile
- build/buildx.Dockerfile
- go.mod
- go.sum
- pkg/golinters/govet/govet.go
- pkg/golinters/govet/govet_test.go
- test/run_test.go
- test/testshared/integration/run.go
This PR is to evaluate and prepare golangci-lint to [go1.23](https://tip.golang.org/doc/go1.23)
This PR will evolve during the beta and RC phases of [go1.23](https://tip.golang.org/doc/go1.23).
**Questions and problems related to go1.23 should be reported in the issue #4837.**
---
`golangci-lint` is a free and open-source project built by volunteers.
If you value it, consider supporting us, we appreciate it! :heart:
[![Open Collective backers and sponsors](https://img.shields.io/badge/OpenCollective-Donate-blue?logo=opencollective&style=for-the-badge)](https://opencollective.com/golangci-lint)
[![GitHub Sponsors](https://img.shields.io/badge/GitHub-Donate-blue?logo=github&style=for-the-badge)](https://github.com/sponsors/golangci)
> go1.23 support

- .github/workflows/post-release.yml
There are multiple jobs in the GitHub post-release workflow that reference the `GO_VERSION` environment variable, but it is only defined for the `update-docs` (aka `Update readme`) job.
This means that the static assets for version `1.60.1` are built with Go `1.22` instead of `1.23`.
You can confirm this by comparing the version of Go used in the `actions/setup-go@5` step of the [Update readme](https://github.com/golangci/golangci-lint/actions/runs/10379882256/job/28738784965) job to the one in [Update GitHub Action assets](https://github.com/golangci/golangci-lint/actions/runs/10379882256/job/28738785585).
> dev: fix GO_VERSION in post release workflow

- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/loader.go
To avoid issues related to the new version of Go, I would add a check to ensure that the Go version used to build is compatible with the Go version used by a project. 
Related to all the issues after each new release of Go.
A small extract of the related issues: #4909, #4908, #4932, #4933, etc.
Output example:
```console
$ ./golangci-lint run
Error: can't load config: the Go language version (go1.22) used to build golangci-lint is lower than the targeted Go version (1.23)
Failed executing command with error: can't load config: the Go language version (go1.22) used to build golangci-lint is lower than the targeted Go version (1.23)
```
> feat: check that Go version use to build is greater or equals to the Go version of the project

- go.mod
- go.sum
https://github.com/securego/gosec/compare/81cda2f91fbe...ab3f6c1c83a0
The update is done by hand because gosec is not released yet and we already use a pseudo version because of #4748.
> build(deps): bump github.com/securego/gosec/v2 from 81cda2f91fbe to ab3f6c1c83a0

- go.mod
- go.sum
Fixes #4940
https://github.com/quasilyte/go-ruleguard/compare/v0.4.2...0fe6f58b47b11c388e8aca96e08b017b77d48ac3
The update is done by hand because go-ruleguard is not released yet. I watch the release of this repo, so I will be notified when a release will be done.
FYI, currently the CI of go-ruleguard is not stable https://github.com/quasilyte/go-ruleguard/issues/480
> build(deps): bump github.com/quasilyte/go-ruleguard to 0fe6f58b47b1

- pkg/golinters/nolintlint/internal/nolintlint.go
- pkg/golinters/nolintlint/internal/nolintlint_test.go
When using the `nolintlint` linter in autofix mode, it does not remove the empty line along with the unused linter directive if it starts from a new line. Expected behavior: should remove the empty line.
> nolintlint: remove empty line in unused directive replacement

- .golangci.next.reference.yml
- jsonschema/golangci.next.jsonschema.json
- pkg/config/output.go
- pkg/printers/junitxml.go
- pkg/printers/junitxml_test.go
- pkg/printers/printer.go
> feat: add junit-xml-extended format

- docs/src/docs/welcome/faq.mdx
Since v1.60.1, there have been a lot of issues/questions about `typecheck`.
So, I would like to add a new section inside the FAQ instead of repeating the same thing.
> docs: add additionnal info about typecheck

- pkg/golinters/gocritic/gocritic.go
- pkg/golinters/gocritic/gocritic_test.go
The PR replaces `"golang.org/x/exp/slices"` with `"slices"` because the minimum supported version is Go 1.22.
> dev: use slices package from stdlib

- .golangci.next.reference.yml
- go.mod
- go.sum
- jsonschema/golangci.next.jsonschema.json
- pkg/golinters/recvcheck/recvcheck.go
- pkg/golinters/recvcheck/recvcheck_integration_test.go
- pkg/golinters/recvcheck/testdata/recvcheck.go
- pkg/lint/lintersdb/builder_linter.go
[recvcheck](https://github.com/raeperd/recvcheck) checks for consistency on the receiver type (pointer/nonpointer)
let me know if i've done something wrong
https://github.com/raeperd/recvcheck
> Add recvcheck linter

- pkg/lint/lintersdb/builder_linter.go
Hi I found inconsistent usage in Since in [linters page](https://golangci-lint.run/usage/linters/)
So I fixed it with simple v prefix if not exists
> docs: consistent WithSince versions

- docs/src/docs/welcome/faq.mdx
It's a try to provide better information about the supported Go versions by golangci-lint.
> docs: improve FAQ about Go versions

- docs/src/docs/usage/false-positives.mdx
Related to https://github.com/golangci/golangci-lint/issues/5044#issuecomment-2379997625
> docs: adds a section about `exclude-dirs-use-default`

- .golangci.next.reference.yml
- .golangci.reference.yml
- .golangci.yml
Reorganize the configuration references (and the configuration) to improve readability.
Before:
- `run`
- `output`
- `linters-settings`
- `linters`
- `issues`
- `severity`
After:
-  `linters`
-  `linters-settings`
-  `issues`
-  `output`
-  `run`
-  `severity`
> docs: reorganize configuration files

- docs/src/docs/welcome/install.mdx
The section was inside a `<details>` tag, so the content was not enough visible.
I also rewrote some points and added new ones.
> docs: improve 'install from sources' section

- pkg/goanalysis/runner_loadingpackage.go
`golangci-lint` should respect `GOARCH` when performing typechecking.
For example, the code below fails to build with `GOARCH=arm`, but succeeds with `GOARCH=amd64`:
```
// -uintptr(x-y) creates a static assertion of x==y
const _ = -uintptr(unsafe.Sizeof((*byte)(nil)) - 8)
```
`golangci-lint` currently does not respect `GOARCH` for typechecking because it does not set `types.Config.Sizes`, which tells the typecheck package how to determine the size of machine-specific types (like pointers and `uintptr`). By default, [if `types.Config.Sizes` is `nil`](https://pkg.go.dev/go/types#Config), `SizesFor("gc", "amd64")` is used by default. This will notably break typechecking for 32-bit platforms.
This PR sets `types.Config.Sizes` from `build.Default`, which is set by the `GOARCH` environment …
> fix: type sizing when cross-compiling (32-bit)

- .golangci.next.reference.yml
- go.mod
- go.sum
- jsonschema/golangci.next.jsonschema.json
- pkg/config/linters_settings.go
- pkg/golinters/nilnil/nilnil.go
- pkg/golinters/nilnil/testdata/nilnil.go
- pkg/golinters/nilnil/testdata/nilnil_detect_opposite.go
- pkg/golinters/nilnil/testdata/nilnil_detect_opposite.yml
- pkg/golinters/nilnil/testdata/nilnil_pointers_only.go
- pkg/golinters/nilnil/testdata/nilnil_pointers_only.yml
https://github.com/Antonboom/nilnil/compare/v0.1.9...v1.0.0
> build(deps): bump github.com/Antonboom/nilnil from 0.1.9 to 1.0.0

- .github/new-linter-checklist.md
- docs/src/docs/contributing/new-linters.mdx
- update checklist
- reorganize new linter section
> docs: improve new linter section

- go.mod
- go.sum
- pkg/golinters/goprintffuncname/goprintffuncname.go
- pkg/lint/lintersdb/builder_linter.go
The repository has been transferred to the org.
I updated the module.
https://github.com/golangci/go-printf-func-name/compare/7558a9eaa5af...v0.1.0
**This update is done by hand because dependabot is not able to handle module name change.**
> build(deps): bump github.com/golangci/go-printf-func-name from 7558a9eaa5af to v0.1.0

- pkg/golinters/internal/staticcheck_common.go
- pkg/logutils/logutils.go
The usage of `internal.SetAnalyzerGoVersion` was removed in #4907.
> dev: remove unused function SetAnalyzerGoVersion

- pkg/printers/codeclimate.go
- pkg/printers/codeclimate_test.go
- pkg/result/issue.go
CodeClimateIssue declares to contain just enough fields to support Gitlab CI Code Quality. But there's a field called `check_name`, which is not generated by golangci-lint, but is stated as required in both [Code Climate spec](https://github.com/codeclimate/platform/blob/master/spec/analyzers/SPEC.md#data-types) and [Gitlab CI Code Quality reference](https://docs.gitlab.com/ee/ci/testing/code_quality.html#implement-a-custom-tool). I moved linter's name from the `description` field to the `check_name` field. I'm not sure if there can be any issue made by an unknown linter, but I made a default value for this field as well, just to be sure.
I also updated the corresponding test and the link to the Gitlab page (the previous one reported 404).
> code-climate: add check_name field

- internal/cache/cache.go
- internal/cache/cache_test.go
- internal/cache/testdata/hello.go
- pkg/timeutils/stopwatch.go
Before reviewing the content of this PR, and if you want, I propose a quick "game" to illustrate the goal of this PR:
- Open the current version of  `internal/cache/cache.go` locally
- You have 10 seconds to read and explain what the method `Get` is doing
- Now open my version of the method `Get` and do the same thing
- Do you see the difference? :smile_cat:
Extends `stopwatch` to simplify the usage.
Isolates usage of `iosem`.
Factorizes methods to increase the readability.
Follows #5100
> Improve readability and maintenance of `internal/cache`

- pkg/goanalysis/runner_action.go
- pkg/lint/runner.go
- pkg/result/processors/fixer.go
Uses method and function created inside #5101 about `Stopwatch` outside of the cache package.
> dev: extends usage of new Stopwatch methods

- .golangci.next.reference.yml
The PR corrects a typo in linter name in `.golangci.next.reference.yml`.
> docs: fix iface linter name

- .golangci.next.reference.yml
- .golangci.reference.yml
- assets/linters-info.json
- pkg/lint/lintersdb/builder_linter.go
See https://github.com/dominikh/go-tools/commit/5ea1adf1d2bcac545a68019ee984b2fa35cdb78e
> docs: replace staticcheck.io with staticcheck.dev

- pkg/config/config.go
To reproduce:
- clone this repo: https://github.com/ldez/cuddly-funicular
- use a version of golangci-lint compiled with go1.22
<details><summary>before</summary>
```console
$ docker run --rm -v $(pwd):/app -w /app -it golang:1.23.2-alpine sh  
/app # GOTOOLCHAIN=go1.22.1 go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.61.0
...
/app # golangci-lint version
golangci-lint has version v1.61.0 built with go1.22.1 from (unknown, modified: ?, mod sum: "h1:VvbOLaRVWmyxCnUIMTbf1kDsaJbTzH20FAMXTAlQGu8=") on (unknown)
/app # rm -rf /go/pkg/mod/golang.org/toolchain@*
/app # go version
go version go1.23.2 linux/amd64
/app # golangci-lint run
```
</details>
<details><summary>after</summary>
```console
$ docker run --rm -v $(pwd):/app -w /app -it golang:1.23.2-alpine sh  
/app # …
```
> fix: improve Go detection

- .golangci.next.reference.yml
- .golangci.reference.yml
- jsonschema/golangci.jsonschema.json
- jsonschema/golangci.next.jsonschema.json
The pattern `^print.*$` also matches `printer`, but it's expected to match only [`print` or `println`](https://go.dev/ref/spec#Bootstrapping) built-in functions.
> docs: improve forbidigo pattern examples for built-in functions

- .golangci.next.reference.yml
- .golangci.reference.yml
This PR fixes links for gocritic checks and replaces `https://go-critic.github.io` with `https://go-critic.com`.
E.g. the link "https://go-critic.com/overview.html#badSyncOnceFunc" is wrong, must be "https://go-critic.com/overview.html#badsynconcefunc".
> docs: fix links to gocritic checks

- .golangci.next.reference.yml
- .golangci.reference.yml
The PR fixes documentation for `sloglint`.
> docs: missing doc link for sloglint.args-on-sep-lines

- internal/go/cache/cache.go
Inside Go this error is ignored.
https://github.com/golang/go/blob/239dbd7dbac883d6f9b6522774a0dfd519f77fa8/src/cmd/go/internal/cache/cache.go#L288
As I explained inside #5098:
> The main modifications are about error handling: the official Go cache implementation ignores many errors, and the implementation inside Golangci-lint reports those "hidden" errors.
We should convert this error to an `entryNotFoundError` error, then the error will be "ignored".
Before this PR, something like that can happen:
<details>
```
WARN [linters_context/goanalysis] Failed to get persisted facts: failed to get data from low-level cache by key nilness/facts for package sync: open /home/ldez/.cache/golangci-lint/9a/9abfb2d9d6ddfa499fad612dd9d0a49dd6bc977b77567ba7a1bb3f93c4df2416-d: no such file or directory …
```
> fix: ignore cache error when file not found

- .golangci.next.reference.yml
- .golangci.reference.yml
- jsonschema/golangci.jsonschema.json
- jsonschema/golangci.next.jsonschema.json
To decrease common confusing. People often expect that they can continue use not-f assertions if only format string is used (without args).
> docs: improve testifylint description of require-f-funcs flag

- docs/src/docs/product/performance.mdx
Because `golint` is deprecated long time ago.
> docs: remove golint on 'performance' page

- .goreleaser.yml
Goreleaser allows us to publish AUR (`-bin`), and we can integrate that into our release system.
Currently, I maintain this manually, this will remove a bit of work related to the release.
> dev: publish AUR -bin automatically

- .github/workflows/tag.yml
- .goreleaser.yml
Goreleaser allows us to publish Snap, so we can integrate that inside our release system.
Currently, there is a snap https://snapcraft.io/golangci-lint
So I will contact the owner of this package.
https://github.com/alexmurray/golangci-lint-snap/issues/6
> dev: publish snap

- .goreleaser.yml
Related to https://aur.archlinux.org/packages/golangci-lint-bin#comment-999855
I fixed the PKGBUILD manually, so no need to create a new release. 
The problem happen because:
```yml
archives:
- format: tar.gz
wrap_in_directory: true # <-----
```
so we have to move the directory that wraps the files.
> dev: fix AUR prepare step

- pkg/printers/codeclimate.go
The link https://docs.gitlab.com/ee/ci/testing/code_quality.html#implement-a-custom-tool does not exist ~~and should be https://docs.gitlab.com/17.6/ee/ci/testing/code_quality.html#implement-a-custom-tool.~~
> docs: fix GitLab doc link in CodeClimateIssue comment

- go.mod
- go.sum
- test/bench/bench_test.go
https://github.com/shirou/gopsutil/compare/v3.24.5...v4.24.10
**This update is done by hand because dependabot is not able to handle major version.**
> build(deps):  bump github.com/shirou/gopsutil to v4.24.10

- go.mod
- go.sum
- pkg/commands/config_verify.go
- test/configuration_file_test.go
https://github.com/santhosh-tekuri/jsonschema/compare/v6.0.0-beta1...v6.0.1
It's impossible to compare v5 and v6 on GitHub because ["There isn’t anything to compare. v5.3.1 and v6.0.1 are entirely different commit histories"](https://github.com/santhosh-tekuri/jsonschema/compare/v5.3.1...v6.0.1).
Used the following commands for tests:
```sh
$ go run ./cmd/golangci-lint config verify
```
```sh
$ go run ./cmd/golangci-lint config verify --schema jsonschema/golangci.jsonschema.json
$ echo $?
0
```
```sh
$ go run ./cmd/golangci-lint config verify -c .golangci.next.reference.yml --schema ./jsonschema/golangci.next.jsonschema.json
jsonschema: "linters-settings.goheader" does not validate with "/properties/linters-settings/properties/goheader/oneOf": "oneOf failed, subschemas 0, 1 matched" …
```
> build(deps): bump santhosh-tekuri/jsonschema/v5 to v6

- pkg/golinters/asasalint/asasalint.go
- pkg/golinters/bidichk/bidichk.go
- pkg/golinters/dupword/dupword.go
- pkg/golinters/errchkjson/errchkjson.go
- pkg/golinters/errorlint/errorlint.go
- pkg/golinters/gosmopolitan/gosmopolitan.go
- pkg/golinters/grouper/grouper.go
- pkg/golinters/maintidx/maintidx.go
- pkg/golinters/musttag/musttag.go
- pkg/golinters/nilnil/nilnil.go
- pkg/golinters/testpackage/testpackage.go
- pkg/golinters/thelper/thelper.go
- pkg/golinters/usestdlibvars/usestdlibvars.go
Refactor linters constructors:
- rename parameters `setting`, `s`, and `cfg` to `settings`
- rename variables `cfgMap`, `linterCfg` to `cfg`.
> dev: refactor linter constructors for consistency

- go.mod
- pkg/config/config.go
- pkg/golinters/gomodguard/testdata/go.mod
- pkg/golinters/gomodguard/testdata/go.sum
- pkg/golinters/gomodguard/testdata/gomodguard.yml
Fixes #4894
<details><summary>To reproduce</summary>
```bash
#!/bin/bash -e
rm -rf wpsample
mkdir wpsample
cd wpsample
go work init
mkdir a b
echo module a > a/go.mod
echo go 1.20 >> a/go.mod
echo module b > b/go.mod
echo go 1.22 >> b/go.mod
echo package main > b/main.go
go work use a
go work use b
cd b
golangci-lint run --enable=copyloopvar,intrange
```
</details>
Note:
By adding `golang.org/x/mod` as a dependency, a bug inside the integration test for `gomodguard` has been detected.
The test used the `go.mod` of golangci-lint instead of a dedicated `go.mod` so we never saw the problem.
The module defined inside the `allowed` section was not a module but a package (`golang.org/x/mod/modfile`) and as the `go.mod` of golangci-lint didn't contain `golang.org/x/mod` the problem was hidden. …
> fix: improve Go version detection inside workspace

- pkg/golinters/cyclop/cyclop.go
- pkg/lint/lintersdb/builder_linter.go
I checked the code of all the linters to ensure that every load mode was right, and I found only 1 wrong load mode.
Also, I removed `WithLoadForGoAnalysis` on `NoopDeprecated` because those linters are doing nothing, so they don't need extra analysis data.
> dev: remove useless call to WithLoadForGoAnalysis

- README.md
Followup from #5148. It's now supported to filter out users since https://github.com/opencollective/contributors-svg/pull/68 got merged so this will restore the previously ignored users + add `dependabot[bot]`.
> docs: Ignore previously ignored contributors

- README.md
It's possible to not specify the `skip` query string for each element but instead use a `,` so this changes the URL to be a bit shorted. Also there was a typo in the previous URL missing an `=` for one element.
---
Sorry for the noise with multiple PRs. Was going to fix the missing `=` but found they also added support for comma separated input making the URL a bit shorted so switched to that.
> docs: Make contributors URL shorter

- .golangci.next.reference.yml
- .golangci.yml
- internal/x/LICENSE
- internal/x/tools/analysisflags/readme.md
- internal/x/tools/analysisflags/url.go
- internal/x/tools/analysisinternal/analysis.go
- internal/x/tools/analysisinternal/readme.md
- jsonschema/golangci.next.jsonschema.json
- pkg/goanalysis/runner.go
- pkg/goanalysis/runner_action.go
- pkg/goanalysis/runner_action_cache.go
- pkg/goanalysis/runner_checker.go
- pkg/goanalysis/runner_loadingpackage.go
Updates the code borrowed from x/tools
Continuation of the work done inside #5109
I still have not found the Lost Ark but I am near the Temple of Doom :smile_cat:
> dev: sync checker with x/tools@v0.28.0

- go.mod
- pkg/commands/help.go
This is for consistency with the documentation.
Before:
```console
$ go run ./cmd/golangci-lint/ help linters
Enabled by default linters:
errcheck: errcheck is a program for checking for unchecked errors in Go code. These unchecked errors can be critical bugs in some cases [fast: false, auto-fix: false]
gosimple: Linter for Go source code that specializes in simplifying code [fast: false, auto-fix: false]
govet: Vet examines Go source code and reports suspicious constructs. It is roughly the same as 'go vet' and uses its passes. [fast: false, auto-fix: false]
ineffassign: Detects when assignments to existing variables are not used [fast: true, auto-fix: false]
staticcheck: It's a set of rules from staticcheck. It's not the same thing as the staticcheck binary. The author of staticcheck …
```
> dev: format linter descriptions inside help command

- pkg/printers/teamcity.go
The PR refactors the implementation of an unexported function `cutVal` in the `printers` package.
> dev: simplify cutVal implementation

- pkg/commands/help.go
The PR changes the output for the `golangci-lint linters help` command.
I think outputting `[fast: false, auto-fix: false]` is redundant, and `help` prints nothing if the linter is slow and does not have auto-fix. If a linter is fast, the command prints green `[fast]`. If a linter can auto fix, the command prints green `[auto-fix]`. If a linter is fast and has auto fix - `[fast, auto-fix]` in green.
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
> dev: enhance help linters output on fast and auto-fix capabilities

- pkg/commands/help.go
Adds the option `--json` to the command `help linters`.
<details>
<summary>Some examples of the usage</summary>
```bash
go run ./cmd/golangci-lint/ help linters --json | jq '[ .[] | select(.name=="nolintlint") ]'
```
```bash
go run ./cmd/golangci-lint/ help linters --json | jq '[ .[] | select(.fast) ]'
```
```bash
go run ./cmd/golangci-lint/ help linters --json | jq '[ .[] | select(.fast==false) ]'
```
```bash
go run ./cmd/golangci-lint/ help linters --json | jq '[ .[] | select(.autoFix==true) ]'
```
```bash
go run ./cmd/golangci-lint/ help linters --json | jq '[ .[] | select(.autoFix==true and .fast==false) ]'
```
```bash
go run ./cmd/golangci-lint/ help linters --json | jq '[ .[] | select(any(.presets[]; . == "style")) ]'
```
```bash
go run ./cmd/golangci-lint/ help linters --json | jq …
```
> feat: display linters help as JSON

- docs/src/docs/index.mdx
The PR sets contributor's image on the website to be the same as in the [README](https://github.com/golangci/golangci-lint/blob/ba4b6df5eae5908e1f634b03bf257372aea9e5fe/README.md?plain=1#L53).
Follows #5200
> docs: update contributors image

- .golangci.next.reference.yml
I discovered the feature of enforcing empty aliases with 
- #5221 
A fix was provided
- #5222
I think it could be interesting to document it.
> docs: empty alias with importas

- pkg/golinters/gosec/gosec.go
- pkg/golinters/gosec/gosec_test.go
- pkg/golinters/gosec/testdata/gosec_nosec.go
- pkg/golinters/gosec/testdata/gosec_nosec.yml
> gosec: handling of global nosec option when it is false

- Makefile
- docs/src/docs/contributing/workflow.mdx
- docs/src/docs/index.mdx
The PR removes:
- Outdated update contributors instructions from the workflow page.
- Unused `make` target `update_contributors_list`.
- Irrelevant `TODO` on the index page.
Follows #5148.
> docs: remove outdated update contributors instructions

- pkg/golinters/goheader/goheader.go
- pkg/golinters/goheader/testdata/fix/in/goheader_4.go
- pkg/golinters/goheader/testdata/fix/out/goheader_4.go
- pkg/result/processors/fixer.go
`Location()` returns the position of the first element that needs to be changed, and `Expected` contains all the header lines.
If the first element to change is at L3 and the beginning of the header is at L1, you have a beautiful Christmas tree based on comment separators.
The problem has been here since the introduction of the auto fix for goheader (golangci-lint v1.57.0).
https://github.com/golangci/golangci-lint/pull/4396/files#diff-36750bd1c0da16befa607266d41aca09351630ed97e4ae48f96b63f60e6cbb6dR103
<details><summary>To reproduce</summary>
```go
/*
Copyright 2024 The Awesome Project Authors
Use of this source code is governed by LICENSE
*/
package sandbox
func Foo() {}
```
```yml
linters:
enable:
- goheader
goheader:
values:
const:
AUTHOR: The …
```
> goheader: fix invalid position

- docs/src/docs/welcome/integrations.mdx
This PR updates "Shell Completion" guide.
> docs: update completion guide

- pkg/lint/lintersdb/builder_linter.go
decoder, sloglint, tagalin are not formatters but just linters related to "style".
> fix: remove decoder, sloglint, tagalin from 'format' preset

- .goreleaser.yml
Since v2.5.0, goreleaser can publish the AUR from sources.
https://goreleaser.com/customization/aursources/
Related to https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=golangci-lint
Follows #5146
> dev: publish AUR from sources

- pkg/golinters/gci/internal/analyzer.go
- pkg/golinters/gci/testdata/gci.go
- pkg/golinters/gci/testdata/gci_cgo.go
- pkg/golinters/gofmt/gofmt.go
- pkg/golinters/gofmt/testdata/gofmt.go
- pkg/golinters/gofmt/testdata/gofmt_cgo.go
- pkg/golinters/gofmt/testdata/gofmt_no_simplify.go
- pkg/golinters/gofmt/testdata/gofmt_rewrite_rules.go
- pkg/golinters/gofumpt/gofumpt.go
- pkg/golinters/gofumpt/testdata/gofumpt.go
- pkg/golinters/gofumpt/testdata/gofumpt_cgo.go
- pkg/golinters/gofumpt/testdata/gofumpt_with_extra.go
- pkg/golinters/goimports/goimports.go
- pkg/golinters/goimports/testdata/goimports.go
- pkg/golinters/goimports/testdata/goimports_cgo.go
- pkg/golinters/goimports/testdata/goimports_local.go
- pkg/golinters/internal/diff.go
- test/run_test.go
The formaters are not classic linter, it makes no sense to use exclusions for them, so I think nobody (or at least very very few people) will be affected by this change.
IMHO, we don't need to create a v2 to change those messages.
Fixes #138
> feat: improve formatter messages

- .golangci.next.reference.yml
- pkg/commands/flagsets.go
- pkg/commands/run.go
Currently, if the timeout is <=0, you have an immediate "context deadline exceeded".
This is useless, so now timeout <=0 means infinite timeout.
The default timeout is not changed.
Fixes #957
> feat: disable timeout if timeout <= 0

- .golangci.next.reference.yml
- jsonschema/golangci.next.jsonschema.json
- pkg/commands/flagsets.go
- pkg/config/issues.go
- pkg/config/loader.go
- pkg/config/output.go
- pkg/result/processors/uniq_by_line.go
- pkg/result/processors/uniq_by_line_test.go
This PR deprecated the old `output.uniq-by-line`, and replaced it with `issues.uniq-by-line`.
This option has a meaning close to `max-issues-per-linter` and `max-same-issues`.
The flag `--uniq-by-line` is not impacted, it's only about the file configuration.
The old `output.uniq-by-line` still works but with a deprecation log message.
> fix: move uniq-by-line field from output to issues

- .golangci.next.reference.yml
- go.mod
- go.sum
- jsonschema/golangci.next.jsonschema.json
- pkg/golinters/nilnesserr/nilnesserr.go
- pkg/golinters/nilnesserr/nilnesserr_integration_test.go
- pkg/golinters/nilnesserr/testdata/nilnesserr.go
- pkg/golinters/nilnesserr/testdata/nilnesserr_cgo.go
- pkg/lint/lintersdb/builder_linter.go
https://github.com/alingse/nilnesserr
`nilnesserr` report that returns a nil value error after checking some error not nil 
```go
err := do()
if err != nil {
return err
}
err2 := do2()
if err2 != nil {
return err
}
```
The difference between `nilness` and `nilerr` is that `nilnesserr` can analyze whether an err is nil in some complex positions through SSA (using code from [`nilness`](https://cs.opensource.google/go/x/tools/+/refs/tags/v0.28.0:go/analysis/passes/nilness/nilness.go) and has been modified), which can help avoid some unrelated error returns.  the nilerr only checked the latest `if` block and the const nil 
I also used https://github.com/alingse/go-linter-runner to analyze some public go repos and fixed some false-positive bug. the result can be seen at …
> Add nilnesserr linter

- docs/src/docs/contributing/faq.mdx
The main changes are:
- Changed `.golangci.reference.yml` to `.golangci.next.reference.yml`.
- The linter's config is in the `linters_settings.go` file, not in `config.go`.
- Fixed grammar issues.
> docs: update "Contributing FAQ"

- pkg/golinters/gci/internal/analyzer.go
- pkg/golinters/gofmt/gofmt.go
- pkg/golinters/gofumpt/gofumpt.go
- pkg/golinters/goimports/goimports.go
Uses clearer descriptions for formatters.
> dev: clarifies and homogenizes formatter descriptions

- .golangci.next.reference.yml
- go.mod
- go.sum
- jsonschema/golangci.next.jsonschema.json
- pkg/golinters/exptostd/exptostd.go
- pkg/golinters/exptostd/exptostd_integration_test.go
- pkg/golinters/exptostd/testdata/exptostd.go
- pkg/golinters/exptostd/testdata/exptostd_cgo.go
- pkg/golinters/exptostd/testdata/exptostd_go123.go
- pkg/golinters/exptostd/testdata/exptostd_go123_cgo.go
- pkg/golinters/exptostd/testdata/fix/in/exptostd.go
- pkg/golinters/exptostd/testdata/fix/out/exptostd.go
- pkg/golinters/exptostd/testdata/go.mod
- pkg/golinters/exptostd/testdata/go.sum
- pkg/lint/lintersdb/builder_linter.go
This linter detects functions from `golang.org/x/exp/` that can be replaced by std functions.
https://github.com/ldez/exptostd
<details><summary>Example</summary>
```go
package foo
import (
"fmt"
"golang.org/x/exp/maps"
)
func foo(m map[string]string) {
clone := maps.Clone(m)
fmt.Println(clone)
}
```
It can be replaced by:
```go
package foo
import (
"fmt"
"maps"
)
func foo(m map[string]string) {
clone := maps.Clone(m)
fmt.Println(clone)
}
```
</details>
> Add exptostd linter

- pkg/goanalysis/position.go
- pkg/golinters/godox/godox.go
- pkg/golinters/gofmt/gofmt.go
- pkg/golinters/gofumpt/gofumpt.go
- pkg/golinters/gofumpt/testdata/fix/in/gofumpt_cgo.go
- pkg/golinters/gofumpt/testdata/fix/out/gofumpt_cgo.go
- pkg/golinters/goheader/goheader.go
- pkg/golinters/goimports/goimports.go
- pkg/golinters/goimports/testdata/fix/in/goimports_cgo.go
- pkg/golinters/goimports/testdata/fix/out/goimports_cgo.go
- pkg/golinters/lll/lll.go
- pkg/golinters/misspell/misspell.go
- pkg/golinters/nestif/nestif.go
> fix: filter files

- pkg/goanalysis/position.go
- pkg/golinters/gofumpt/testdata/gofumpt.go
> fix: invalid position when missing EOL

- pkg/golinters/goheader/goheader.go
1. When there is a build directives, goheader reports invalid issues.
2. Inside golangci-lint we are using the same code as goheader to fix the missing offset when `//` comment.
The problem is that a build directive starts with `//` so we apply the offset.
This produces a negative position (`-1`) and then the report will refer to the previous file inside the fileset.
> goheader: skip issues with invalid positions

- pkg/golinters/gofmt/testdata/gofmt_too_many_empty_lines.go
- pkg/golinters/gofumpt/testdata/gofumpt_too_many_empty_lines.go
- pkg/golinters/internal/diff.go
- pkg/golinters/internal/diff_test.go
- pkg/golinters/internal/testdata/delete_last_line.diff
> fix: invalid from position

- pkg/goanalysis/position.go
- pkg/golinters/dupl/dupl.go
- pkg/golinters/gomodguard/gomodguard.go
- pkg/golinters/internal/util.go
- pkg/golinters/revive/revive.go
- pkg/golinters/revive/revive_integration_test.go
- pkg/golinters/revive/testdata/fix/in/revive.go
- pkg/golinters/revive/testdata/fix/out/revive.go
- pkg/golinters/revive/testdata/revive-fix.yml
Keep only Go files to avoid build artifacts.
> fix: filter Go filenames

- pkg/goformatters/analyzer.go
- pkg/goformatters/internal/commons.go
- pkg/goformatters/internal/diff.go
The PR refactors code:
- Change `patch string` to `patch []byte` in  `ExtractDiagnosticFromPatch`.
- Rename `theDiff` to `patch` in the `goformatters.NewAnalyzer`.
- Use `patch` instead of `string(patch)` as `%q` will correctly output byte slice as string.
> dev: avoid string conversion by passing byte slice

- pkg/commands/help.go
- pkg/commands/help_test.go
```
panic: runtime error: index out of range [0] with length 0
goroutine 1 [running]:
github.com/golangci/golangci-lint/pkg/commands.formatDescription({0x0, 0x0})
/tmp/custom-gcl2430187412/golangci-lint/pkg/commands/help.go:222 +0x125
github.com/golangci/golangci-lint/pkg/commands.printLinters({0xc0006251c0, 0x7, 0xc0006ad428?})
/tmp/custom-gcl2430187412/golangci-lint/pkg/commands/help.go:187 +0x1d9
github.com/golangci/golangci-lint/pkg/commands.(*lintersCommand).execute(0xc000926f50, 0xc000743a90?, {0x0?, 0x0?, 0x0?})
/tmp/custom-gcl2430187412/golangci-lint/pkg/commands/linters.go:102 +0x285
github.com/spf13/cobra.(*Command).execute(0xc000910308, {0x2a45c40, 0x0, 0x0})
/home/ldez/sources/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:985 +0xaaa …
```
> fix: avoid panic with plugin without description

- .golangci.next.reference.yml
- .golangci.reference.yml
This PR enhances the documentation for the `depguard` linter by providing detailed explanations of the `list-mode` options and clarifying the ability to match packages exactly by appending `$` to the end of the package name.
> docs: clarify depguard configuration

- .golangci.yml
> chore: remove duplicate linter inside the configuration

- pkg/golinters/gocritic/gocritic.go
- pkg/golinters/govet/govet.go
Uses the same format as #5325
<details><summary>govet before</summary>
```console
$ GL_DEBUG=govet golangci-lint run --enable-only=govet      
DEBU [govet] All available analyzers (43): [appends asmdecl assign atomic atomicalign bools buildtag cgocall composites copylocks deepequalerrors defers directive errorsas fieldalignment findcall framepointer httpresponse ifaceassert loopclosure lostcancel nilfunc nilness printf reflectvaluecompare shadow shift sigchanyzer slog sortslice stdmethods stdversion stringintconv structtag testinggoroutine tests timeformat unmarshal unreachable unsafeptr unusedresult unusedwrite waitgroup] 
DEBU [govet] Default analyzers (33): [appends asmdecl assign atomic bools buildtag cgocall composites copylocks defers directive errorsas framepointer httpresponse …
```
> dev: linter log consistency

- .golangci.next.reference.yml
- pkg/golinters/revive/revive.go
Here is the result
```
$ GL_DEBUG=revive go run cmd/golangci-lint/main.go run --enable-only=revive
DEBU [revive] All available analyzers checks (81): [add-constant argument-limit atomic banned-characters bare-return blank-imports bool-literal-in-expr call-to-gc cognitive-complexity comment-spacings comments-density confusing-naming confusing-results constant-logical-expr context-as-argument context-keys-type cyclomatic datarace deep-exit defer dot-imports duplicated-imports early-return empty-block empty-lines enforce-map-style enforce-repeated-arg-type-style enforce-slice-style error-naming error-return error-strings errorf exported file-header file-length-limit filename-format flag-parameter function-length function-result-limit get-return identical-branches if-return …
```
> dev: displays revive rules inside debug logs

- pkg/logutils/logutils.go
The PR moves the constant `logutils.DebugKeyForbidigo` below to the rest linter debug keys.
> dev: move `forbidigo` debug const to const linters group 

- jsonschema/golangci.next.jsonschema.json
I would like to suggest this simple addition
It could avoid loosing time as I did.
I was using EXC014 (instead of EXC0014) and I had to debug everything to figure our the problem was between keyboard and chair.
I validated it worked with the following command:
```shell
go run cmd/golangci-lint/main.go config verify --schema jsonschema/golangci.next.jsonschema.json --config /path/golangci.yml
```
I also checked at the code and it should be safe
https://github.com/golangci/golangci-lint/blob/v1.63.4/pkg/config/issues.go#L233-L247
> docs: add default exclusion names to the JSONSchema

- docs/src/docs/contributing/quick-start.mdx
We don't maintain issues with the `label:"good first issue"`, so it's not useful information and I propose to remove it.
> docs: remove "good first issue" mention

- pkg/printers/codeclimate.go
- pkg/printers/codeclimate_test.go
Keeps only supported severity names: https://github.com/codeclimate/platform/blob/master/spec/analyzers/SPEC.md#data-types
Closes #5349
> fix: fallback on unknown severities for code climate

- .golangci.next.reference.yml
The PR extends reference:
- add `early-return.allowJump` option https://github.com/mgechev/revive/pull/1138
- fix `filename-format` regexp https://github.com/mgechev/revive/pull/1132
Follows #5346
> docs: improve revive configuration examples

- docs/src/docs/contributing/faq.mdx
Adds the same content as https://github.com/golangci/golangci-lint/blob/master/.github/PULL_REQUEST_TEMPLATE.md?plain=1
> docs: update FAQ about updating linter

- pkg/config/output.go
- pkg/printers/codeclimate.go
- pkg/printers/junitxml.go
- pkg/printers/junitxml_test.go
- pkg/printers/printer.go
- pkg/printers/tab.go
> dev: cleanup printers

- .golangci.next.reference.yml
- docs/src/docs/welcome/faq.mdx
- go.mod
- go.sum
- jsonschema/golangci.next.jsonschema.json
- pkg/config/issues.go
- pkg/result/processors/diff.go
Adds new `issues.new-from-merge-base` option.
`git merge-base` is a better approach than an explicit revision:
```mermaid
gitGraph:
commit id:"a"
commit id:"b" type:HIGHLIGHT
branch my_branch
checkout main
commit id:"c"
checkout my_branch
commit id:"d"
commit  id:"e"tag:"HEAD" type:HIGHLIGHT
checkout main
commit id:"f"
commit id:"g" type:HIGHLIGHT
```
When using `issues.new-from-rev=main`, the diff will be between `e` and `g`, which is wrong.
With `issues.new-from-merge-base=main`, the diff will be between `e` and `b`, which is right.
The new option uses `git merge-base <ref> HEAD` internally. (https://github.com/golangci/revgrep/blob/43995b04fc9795de8791e8a9d82206f95d8acaf1/patch.go#L182)
Reference: https://git-scm.com/docs/git-merge-base
Some real-life examples:
- …
> feat: add new issues.new-from-merge-base option

- pkg/commands/run.go
- pkg/printers/printer.go
- pkg/printers/printer_test.go
I missed this element of the configuration when I introduced `run.relative-path-mod`.
Related to #5339
Related to #5297
Fixes #3656
> feat: use run.relative-path-mode for output format paths

- .golangci.next.reference.yml
- jsonschema/golangci.next.jsonschema.json
- pkg/config/linters_settings.go
- pkg/golinters/usetesting/testdata/usetesting.go
- pkg/lint/lintersdb/builder_linter.go
The PR deprecates `tenv` in favor of `usetesting`.
The default configuration of `usetesting` is updated accordingly.
> tenv: deprecation

- .github/peril/README.md
- .github/peril/settings.json
- .github/workflows/codeql.yml
- .github/workflows/documentation.yml
- .github/workflows/post-release.yml
- .github/workflows/pr.yml
- .golangci.next.reference.yml
- .golangci.reference.yml
- .goreleaser.yml
- CHANGELOG.md
- assets/linters-info.json
- docs/src/components/SearchBar/README.md
- docs/src/docs/contributing/debug.mdx
- docs/src/docs/contributing/faq.mdx
- docs/src/docs/contributing/new-linters.mdx
- docs/src/docs/contributing/workflow.mdx
- docs/src/docs/index.mdx
- docs/src/docs/plugins/go-plugins.mdx
- docs/src/docs/usage/configuration.mdx
- docs/src/docs/usage/false-positives.mdx
- docs/src/docs/welcome/install.mdx
- install.sh
- pkg/golinters/gocritic/testdata/ruleguard/README.md
- pkg/lint/lintersdb/builder_linter.go
- pkg/printers/codeclimate.go
- scripts/bench/bench_local.sh
- scripts/bench/bench_version.sh
For external references, this has the advantage of not breaking if a project changes its default branch.
For internal references, it allows us to change the default branch.
More changes are required to change the default branch, and this PR doesn't imply a change of the default branch.
This can be useful to handle v2.
Related to #4866
> dev: use HEAD as references

- assets/github-action-config-v1.json
- assets/github-action-config.json
- scripts/gen_github_action_config/main.go
- scripts/gen_github_action_config/testdata/github-action-config-v1.json
- scripts/gen_github_action_config/testdata/github-action-config.json
- scripts/gen_github_action_config/types.go
The field `AssetURL` is not used by the GitHub Action.
Related to https://github.com/golangci/golangci-lint-action/pull/1158
> dev: remove unused AssetURL from github action assets

- scripts/website/copy_jsonschema/main.go
The destination of the copy of the latest schema was wrong.
> dev: fix JSONSchema publication

- docs/src/docs/welcome/install.mdx
I found a typo in the third point and decided to improve the grammar for the entire "Install from Sources" paragraph.
> docs: update install from sources paragraph

- CHANGELOG.md
> docs: option name typo inside changelog

- pkg/goformatters/gci/internal/config/config.go
- pkg/goformatters/gci/internal/section/section.go
- pkg/golinters/gci/testdata/gci_go124.go
The modified versions of `section.Parse` and `section.DefaultSections` were not called.
Related to #5402
> gci: fix section parsing

- pkg/commands/flagsets.go
> fix: add missing new-from-merge-base flag

- CHANGELOG.md
The PR fixes a few typos and trims trailing whitespace in CHANGELOG.
Follows #5401
> docs: fix typos in changelog

- jsonschema/golangci.jsonschema.json
- jsonschema/golangci.next.jsonschema.json
- jsonschema/golangci.v1.57.jsonschema.json
- jsonschema/golangci.v1.58.jsonschema.json
- jsonschema/golangci.v1.59.jsonschema.json
- jsonschema/golangci.v1.60.jsonschema.json
- jsonschema/golangci.v1.61.jsonschema.json
- jsonschema/golangci.v1.62.jsonschema.json
- jsonschema/golangci.v1.63.jsonschema.json
- test/testdata/configs/custom_linter_goplugin.yml
- test/testdata/configs/custom_linter_module.yml
- test/testdata/configs/custom_linter_notype.yml
Hello!
The following config:
```yaml
custom:
foo:
path: "bin/linter/myplugin.so"
```
is considered broken under current JSON schema for config:
```jsonc
{
"custom": {
"type": "object",
"patternProperties": {
"^.*$": {
"type": "object",
"additionalProperties": false,
"properties": {
"type": {
"enum": [ "module", "goplugin" ],
"default": "goplugin"
},
"path": {
"type": "string",
"examples": [ "/path/to/example.so" ]
}, /* ... */
},
"oneOf": [
{
"properties": {
"type": { "enum": [ "module" ] }
}
},
{
"required": [ "path" ]
}
]
}
}
}
}
```
for two reasons:
* In JSON Schema, `oneOf` requires *exactly one of each options*. When both sub-schemas match the object, the validation fails.
* In JSON Schema, all properties are deemed optional unless explicitly stated to be …
> Require type for oneOf mutual exclusion

- .gitattributes
- assets/github-action-config-v2.json
- scripts/gen_github_action_config/main.go
- scripts/gen_github_action_config/main_test.go
- scripts/gen_github_action_config/testdata/github-action-config-v2.json
Generates `assets/github-action-config-v2.json` dedicated for v2
> dev: GitHub actions assets v2

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
I think it is interesting to know how users install golangci-lint.
> dev: ask about installation inside issue template

- pkg/commands/config.go
The JSON is easier to parse.
Inside the GitHub action, I use the command to have the path, it works but a JSON is more robust.
> feat: add an option to display config path as JSON

- pkg/config/base_rule.go
- pkg/config/formatters_settings.go
- pkg/config/linters.go
- pkg/config/linters_settings.go
- pkg/config/severity.go
This is a requirement for the migration command.
> dev: add missing mapstructure tags

- .golangci.next.reference.yml
- jsonschema/golangci.next.jsonschema.json
- pkg/config/linters_settings.go
- pkg/golinters/gci/testdata/gci.yml
- pkg/golinters/gofmt/testdata/gofmt_no_simplify.yml
- pkg/golinters/gofmt/testdata/gofmt_rewrite_rules.yml
- pkg/golinters/gofumpt/testdata/gofumpt-fix.yml
- pkg/golinters/gofumpt/testdata/gofumpt_with_extra.yml
- pkg/golinters/goimports/testdata/goimports_local.yml
- test/testdata/configs/multiple-issues-fix.yml
Some other changes will be added when I will add the new linters configuration (#5299).
Follows #5357
Fixes #5296
> feat: remove compatibility layer for formatters configuration

- .golangci.next.reference.yml
- pkg/golinters/revive/testdata/revive.go
- pkg/golinters/revive/testdata/revive.yml
It's possible to define user functions for the `revive.error-strings` rule.
See mgechev/revive#1245
> docs: add arguments to `revive.error-strings`

- .golangci.next.reference.yml
- .golangci.yml
- jsonschema/golangci.next.jsonschema.json
- pkg/config/linters_settings.go
- pkg/config/severity.go
- pkg/golinters/forbidigo/forbidigo.go
- pkg/golinters/forbidigo/testdata/forbidigo.yml
- pkg/golinters/forbidigo/testdata/forbidigo_struct.yml
- pkg/golinters/misspell/misspell.go
- pkg/golinters/misspell/testdata/misspell.yml
- pkg/golinters/predeclared/testdata/predeclared_custom.yml
- test/testdata/configs/output.yml
- test/testdata/configs/path-except.yml
- `severity.default-severity` ->`severity.default`
- forbidigo: multi-type (string, slice) -> slice
- `forbidigo.forbid[].p` -> `forbidigo.forbid[].pattern`
- `predeclared.q` -> `predeclared.qualified-name`
- `wrapcheck.ignoreInterfaceRegexps` -> `wrapcheck.ignore-interface-regexps`
- `wrapcheck.ignorePackageGlobs` -> `wrapcheck.ignore-package-globs`
- `wrapcheck.ignoreSigRegexps` -> `wrapcheck.ignore-sig-regexps`
- `wrapcheck.ignoreSigs` ->	`wrapcheck.ignore-sigs`
- `misspell.ignore-words` -> `misspell.ignore-rules`
- `gomodguard.blocked.local_replace_directives` -> `gomodguard.blocked.local-replace-directives`
> feat: configuration options renaming

- pkg/golinters/govet/testdata/govet_fieldalignment.go
- test/testshared/directives.go
the govet fieldalignment test currently fails on 32bit targets because it assumes `uintptr` always has a size of 8 bytes.
this pr (edited after some discussion) adds build tags to skip it on platforms where that is not the case.
> govet: skip fieldalignment test on 32bit platforms

- .golangci.next.reference.yml
- jsonschema/golangci.next.jsonschema.json
- pkg/commands/flagsets.go
- pkg/config/output.go
- pkg/config/output_test.go
- pkg/result/processors/sort_results.go
- pkg/result/processors/sort_results_test.go
- test/run_test.go
The `sort-results` is dropped, the results will always be sorted.
The new default sort order is: linter, file.
> feat: new default sort order

- .golangci.next.reference.yml
- .golangci.yml
- jsonschema/golangci.next.jsonschema.json
- pkg/config/formatters_settings.go
- pkg/config/linters_settings.go
- pkg/goformatters/goimports/goimports.go
- pkg/golinters/goimports/testdata/goimports_local.yml
- pkg/golinters/predeclared/predeclared.go
- pkg/golinters/predeclared/testdata/predeclared_custom.yml
- `predeclared.ignore`
- `goimports.local-prefixes`
> feat: convert comma separated to slices

- .golangci.yml
- jsonschema/golangci.next.jsonschema.json
- pkg/result/processors/max_per_file_from_linter.go
Applies the same default limitations on all formatters.
> chore: apply same default limitations on all formatters

- .golangci.next.reference.yml
Reading the reference, I found that the `goheader.template` missed comments `#` when marking empty lines:
<details><summary>Details</summary>
<p>
Before:
```yaml
template: |-
#
```
After:
```yaml
template: |-
#
#
#
#
```
</p>
</details> 
But then I realized, why do we need to comment the example header at all? Better is to put copyright text right into the template, so that people can use it as is:
```yaml
template: |-
{{ AUTHOR }} {{ COMPANY }} {{ YEAR }}
SPDX-License-Identifier: Apache-2.0
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at:
http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the …
```
> docs: update goheader.template reference

- pkg/commands/config_verify.go
- pkg/commands/config_verify_test.go
The version information has changed in go1.24.
Fixes #5478
> fix: use commit hash when version is v0.0.0

- docs/src/docs/welcome/install.mdx
- docs/src/docs/welcome/integrations.mdx
Since there's some kind of official documentation for this, I decided to link it.
edit: we could even link to the [official "CI/CD component"](https://gitlab.com/components/code-quality-oss/codequality-os-scanners-integration/-/blob/main/templates/golangci.yml) if wanted.
> docs: add GitLab documentation

- .golangci.next.reference.yml
- .golangci.reference.yml
- jsonschema/golangci.jsonschema.json
- jsonschema/golangci.next.jsonschema.json
- jsonschema/golangci.v1.57.jsonschema.json
- jsonschema/golangci.v1.58.jsonschema.json
- jsonschema/golangci.v1.59.jsonschema.json
- jsonschema/golangci.v1.60.jsonschema.json
- jsonschema/golangci.v1.61.jsonschema.json
- jsonschema/golangci.v1.62.jsonschema.json
- jsonschema/golangci.v1.63.jsonschema.json
Tested with https://regex101.com/r/7h45UC/1
While doing https://github.com/sapcc/go-makefile-maker/pull/248 we noticed that valid time.Durations are not accepted in the schema which got validated by the github action with verify=true (https://github.com/sapcc/go-makefile-maker/actions/runs/13635720861/job/38113890543?pr=248) but the command itself ran fine locally.
After this change everything works fine when running the following locally:
```
./golangci-lint config verify -c ~/go-makefile-maker/.golangci.yaml --schema jsonschema/golangci.jsonschema.json
```
> dev: fix schema not accepting valid timeout

- go.mod
- go.sum
- pkg/golinters/dupl/dupl.go
https://github.com/golangci/dupl/compare/581e38e7914a679bf734ac1e0a4cb544819ade54...f665c8d69b32
Fixes #5504
> build(deps): bump github.com/golangci/dupl from 3e9179ac440a to f665c8d69b32

- pkg/commands/internal/migrate/migrate_formatters.go
- pkg/commands/internal/migrate/testdata/json/empty.golden.json
- pkg/commands/internal/migrate/testdata/toml/empty.golden.toml
- pkg/commands/internal/migrate/testdata/yaml/empty.golden.yml
- pkg/commands/internal/migrate/testdata/yaml/issues_07_a.golden.yml
- pkg/commands/internal/migrate/testdata/yaml/issues_07_b.golden.yml
- pkg/commands/internal/migrate/testdata/yaml/unknown-fields.golden.yml
- pkg/goformat/runner.go
When I created the `fmt` command, it was for the v1, so I created a compatibility layer.
With the v2, this command should follow the same rule as `run` (with some exceptions because the internal process is totally different from the `run`).
> feat: drop v1 compatibility with exclude-dirs-use-default for fmt

- go.mod
- go.sum
- pkg/commands/migrate.go
This is an attempt to improve the funding strategy.
> chore: call to action

- .github/workflows/pr.yml
- pkg/commands/formatters.go
- pkg/commands/help_formatters.go
- pkg/commands/help_linters.go
- pkg/commands/linters.go
- pkg/commands/migrate.go
- pkg/commands/version.go
- adds `--json` flags to `golangci-lint formatters` command
- adds `--json` flags to `golangci-lint linters` command
- modify `golangci-lint version` command to use `--json` instead of `--format json`
<details><summary>before</summary>
```bash
golangci-lint version --format short
golangci-lint version --debug
golangci-lint version --format json
golangci-lint version --format json --debug
```
</details>
<details><summary>after</summary>
```bash
golangci-lint version --short
golangci-lint version --debug
golangci-lint version --json
golangci-lint version --json --debug
```
</details>
> feat: use homogeneous JSON flags

- pkg/config/loader.go
Detects if a user tries to enable or disable `typecheck`.
`typecheck` is not a linter.
- https://golangci-lint.run/welcome/faq/#why-do-you-have-typecheck-errors
- https://golangci-lint.run/welcome/faq/#why-is-it-not-possible-to-skipignore-typecheck-errors
> feat: error if typecheck is enabled or disabled

- pkg/config/config.go
- pkg/config/formatters.go
- pkg/config/linters.go
Linters cannot be enabled inside the formatters section.
> feat: detects linters inside formatters

- docs/src/docs/welcome/install.mdx
We strongly discourage the usage of `go tool` but users do it, so we can recommend some approach to limit the problems.
We will continue to strongly discourage this usage, this will not become a supported or recommended method.
> docs: go tool note

- pkg/golinters/revive/revive.go
We can use the `Failure` instead of 2 channels and JSON serialization.
> dev: simplify revive implementation

- docs/src/config/sidebar.yml
- docs/src/docs/index.mdx
- Removes FOSSA image (not really useful, and we don't have real access to the data)
- Consistent quoting of the sidebar item (useful when you need to apply modification on several items)
- Adds a link to the legacy documentation of the v1
> docs: add a link to the documentation of the v1

- .golangci.next.reference.yml
- go.mod
- go.sum
- jsonschema/golangci.jsonschema.json
- jsonschema/golangci.next.jsonschema.json
- pkg/config/linters_settings.go
- pkg/golinters/nilnil/nilnil.go
- pkg/golinters/nilnil/testdata/nilnil_multiple_nils.go
- pkg/golinters/nilnil/testdata/nilnil_multiple_nils.yml
https://github.com/Antonboom/nilnil/releases/tag/v1.1.0
https://github.com/Antonboom/nilnil/compare/v1.0.1...v1.1.0
> build(deps): bump github.com/Antonboom/nilnil from 1.0.1 to 1.1.0

- .golangci.next.reference.yml
This PR updates reference by adding arguments to these `revive` rules:
- defer
- dot-imports
- enforce-repeated-arg-type-style
- exported
- import-alias-naming
> docs: add arguments to a few revive rules

- docs/src/docs/welcome/install.mdx
Changes:
- Rename `Brew` to [`Homebrew`](https://github.com/Homebrew/brew#homebrew).
- Add link to the official formula.
- Fix grammar.
> docs: update Homebrew installation manual

- docs/src/docs/welcome/install.mdx
- remove `-v`
- fix the wrong cache path
- improve the command by reusing the Go cache too
> docs: improve Docker example with cache reuse

- pkg/commands/run.go
- pkg/config/loader.go
- test/enabled_linters_test.go
The version validation was done after the configuration validations.
Related to https://github.com/golangci/golangci-lint/issues/5597#issuecomment-2748533645
> fix: validate version before configuration

- pkg/config/loader.go
- pkg/golinters/golines/testdata/fix/in/golines-custom.go
- pkg/golinters/golines/testdata/fix/out/golines-custom.go
- pkg/golinters/golines/testdata/golines-custom.yml
This fixes the issue retaining the existing code pattern, but I'm wondering why we don't just do this instead of checking for each enabled formatter:
```go
l.cfg.Linters.Settings.FormatterSettings = l.cfg.Formatters.Settings
```
I'm assuming for now that there is a good reason :)
Fixes #5603
> fix: copy golines settings during linter settings load

- pkg/commands/internal/migrate/migrate_linters_settings.go
- pkg/commands/internal/migrate/testdata/yaml/linters-settings_forbidigo.golden.yml
- pkg/commands/internal/migrate/testdata/yaml/linters-settings_forbidigo.yml
> fix: forbidigo migration

- docs/src/docs/product/migration-guide.mdx
- docs/src/docs/usage/configuration.mdx
Related to https://github.com/golangci/golangci-lint/issues/5608#issuecomment-2749143347
> docs: add example of the field version

- README.md
The `adaptive` property adjusts the image's style based on GitHub's dark/light theme.
<details><summary>Screenshots</summary>
<p>
Before:
After:
</p>
</details>
> docs: adaptive stargazers image

- pkg/commands/config.go
- pkg/commands/fmt.go
- pkg/commands/formatters.go
- pkg/commands/linters.go
- pkg/commands/run.go
- pkg/config/loader.go
Related to https://github.com/golangci/golangci-lint/issues/5597#issuecomment-2750760561
> fix: enable formatters with flags

- docs/src/docs/product/migration-guide.mdx
Adds details about the flags migration.
> docs: add section about flags migration

- scripts/website/expand_templates/linters.go
The [configuration example](https://golangci-lint.run/usage/configuration/) lacks the `version` field.
<details><summary>Details</summary>
<p>
Before:
After:
</p>
</details> 
Follows #5609
> docs: add version field to configuration sample

- docs/src/docs/usage/false-positives.mdx
- pkg/result/processors/nolint_filter_test.go
`golint` is deprecated and removed from golangci-lint.
> docs: remove golint in nolint example

- .golangci.next.reference.yml
- .golangci.reference.yml
`gci`, `gofmt`, `gofumpt`, and `goimports` can't be inside `linters.enable` or `linters.disable`.
> docs: fix config reference for formatters

- .golangci.next.reference.yml
- .golangci.reference.yml
- docs/src/docs/usage/configuration.mdx
- scripts/website/expand_templates/linters.go
- Fixes duplicated section introduced by #5632
- Uses the reference to generate the doc.
> docs: improve version documentation

- scripts/website/expand_templates/linters.go
Fixes #5642 
<details>
</details>
> docs: fix settings examples

- .golangci.next.reference.yml
> docs: cleanup config reference

- pkg/lint/lintersdb/builder_linter.go
- scripts/website/expand_templates/thanks.go
- scripts/website/expand_templates/thanks_test.go
<details><summary>update misspell repository URL</summary>
The [original misspell repository](https://github.com/client9/misspell) has been archived.
I updated the URL of the repository, but keep the right author inside the Thanks page.
</details>
> dev: rewrite and simplify thanks page generation

- .golangci.next.reference.yml
- .golangci.reference.yml
- jsonschema/golangci.jsonschema.json
- jsonschema/golangci.next.jsonschema.json
`tenv` is removed in v2, but we forgot to remove also its settings.
> docs: remove tenv linter settings

- docs/src/@rocketseat/gatsby-theme-docs/src/styles/global.js
- scripts/website/expand_templates/exclusions.go
<details>
</details>
Markdown table doesn't work because of a problem related to `|` character with the current Markdown parser (note, escaping doesn't work either).
The tag `<code>` cannot be used because it breaks the MDX parsing.
For now, we don't need to handle the other exclusion fields.
> docs: improve default exclusions render

- docs/src/docs/welcome/install.mdx
This PR fixes the "`go tool` usage recommendations" section in the following documentation page: https://golangci-lint.run/welcome/install/#install-from-sources
| Before | After
| :--: | :--:
| <img width="740" alt="image" src="https://github.com/user-attachments/assets/77a9e04d-c598-431c-ae3a-95c5c8e2029e" /> | <img width="704" alt="image" src="https://github.com/user-attachments/assets/e60aeb01-cb1b-461a-9674-7faf6194f316" />
> docs: fix `go get -tool` command

- .golangci.next.reference.yml
- pkg/config/placeholders.go
- pkg/golinters/depguard/depguard.go
- pkg/golinters/gocritic/gocritic.go
- pkg/golinters/gocritic/gocritic_settings.go
- pkg/golinters/gocritic/gocritic_settings_test.go
- pkg/golinters/gocritic/testdata/gocritic.yml
- pkg/golinters/goheader/goheader.go
- pkg/golinters/internal/commons.go
- pkg/lint/lintersdb/builder_linter.go
In the rare cases, the linter configuration should be relative to the configuration path, even when using other relative path modes other than `cfg`.
Those cases are relative to paths that reference "external files".
Fixes #5646
> feat: add config path placeholder

- go.mod
- go.sum
- pkg/commands/fmt.go
- pkg/goformat/runner.go
<details><summary>--diff</summary>
</details>
<details><summary>--diff-colored</summary>
</details>
> feat: colored diff for fmt command

- .golangci.next.reference.yml
- jsonschema/golangci.next.jsonschema.json
- pkg/config/formatters.go
- pkg/goformat/runner.go
- pkg/result/processors/exclusion_paths.go
> feat: add warn-unused option for fmt command

- docs/src/docs/product/migration-guide.mdx
Thanks for maintaining golangci-lint always!
golangci-lint helps me and my team prevent bugs by making static analysis easy to execute. 👏
When I read the migration guide to `v2`, I wondered, "How should I migrate preset linters to v2 config file? Should I indentify what linters belong to the preset, and write out each linter name to `v2` config file one by one?".
After executing the `migrate` command, I realized the `migrate` command did it instead of me. 😂
I believe it would be easier to understand if this were described in migration guide.
So I suggest adding description that shows the `migrate` command automatically migrates `linters.presets` to `linters.enable`.
<details>
</details>
> docs: explicitly describe that the `migrate` command automatically migrate `linters.presets`

- docs/src/docs/welcome/integrations.mdx
- https://github.com/golang/vscode-go/releases/tag/v0.47.1
- https://github.com/golang/vscode-go/commit/5e6ba196ad79435b0cbad30ed229be97fb8a7e20
- https://github.com/golang/vscode-go/issues/3732
This will be inside the next release  of vscode-go (v0.48.0)
> docs: update section about vscode integration

- pkg/golinters/mnd/mnd.go
- pkg/golinters/mnd/testdata/mnd_custom.go
- pkg/golinters/mnd/testdata/mnd_custom.yml
The PR removes `newMND` and adds a test that runs `mnd` with custom settings.
> dev: simplify mnd implementation

- docs/src/docs/welcome/integrations.mdx
In GoLand 2025.1 we have reworked and bundled the plugin for golangci-lint support. We would like to update the integration in IDEs page accordingly and share it with the community.
> docs: update section about GoLand integration

- pkg/commands/run.go
- pkg/config/config.go
- pkg/config/loader.go
- pkg/logutils/logutils.go
> fix: add go.mod hash to the cache salt

- .github/workflows/pr-checks.yml
Since several weeks, the `check-generated` fails 50% of time, due to a GitHub API problem:
```
2025/04/16 14:50:06 failed to fetch all releases: failed to fetch releases page from GitHub: non-200 OK status code: 504 Gateway Timeout
```
In all cases, we don't need to always check it, as the asset is generated automatically after a release.
> dev: disable check-generated job

- pkg/goanalysis/runners.go
Fixes #5744
FYI, in most cases, the related information will not be displayed because the reports will be on the same line (`uniq-by-line` is true by default.)
> fix: related information position

- docs/src/docs/welcome/integrations.mdx
Related to https://github.com/golangci/golangci-lint/pull/5740#issuecomment-2816219744
> docs: GoLand IDE only support v1 for now

- go.mod
- go.sum
- pkg/golinters/fatcontext/fatcontext.go
- scripts/website/expand_templates/thanks.go
**This update is done by hand because Dependabot cannot handle a module name change.**
https://github.com/Crocmagnon/fatcontext/compare/v0.7.2...v0.8.0
related to https://github.com/golangci/golangci-lint/discussions/5756
> build(deps): bump go.augendre.info/fatcontext from 0.7.2 to 0.8.0

- docs/src/docs/welcome/integrations.mdx
Related to #5750
Related to #5740
The changelog of Goland 2025.1 is wrong.
> docs: GoLand IDE support v2

- CHANGELOG.md
Due to an error related to Snapcraft, some artifacts of the v2.1.3 release have not been published.
```
⨯ release failed after 24m40s             
error=
│ 1 error occurred:
│ 	* snapcraft packages: failed to push dist/golangci-lint_armv6.snap package: exit status 1: Uploading... (--->)
│ Uploading... (<---)
│ Issue encountered while processing your request: [500] Internal Server Error.
│ Full execution log: '/home/runner/.local/state/snapcraft/log/snapcraft-20250424-171708.489628.log'
Error: The process '/opt/hostedtoolcache/goreleaser-action/2.8.1/x64/goreleaser' failed with exit code 1
```
> chore: prepare release

- go.mod
- go.sum
- pkg/golinters/makezero/makezero.go
**This update is done by hand because Dependabot cannot handle a module name change.**
https://github.com/ashanbrown/makezero/compare/v1.2.0...v2.0.1
> build(deps): bump github.com/ashanbrown/makezero from 1.2.0 to 2.0.1

- pkg/golinters/dupl/dupl.go
- pkg/golinters/errcheck/errcheck.go
- pkg/golinters/gochecknoinits/gochecknoinits.go
- pkg/golinters/gocognit/gocognit.go
- pkg/golinters/goconst/goconst.go
- pkg/golinters/gocyclo/gocyclo.go
- pkg/golinters/internal/util.go
- pkg/golinters/prealloc/prealloc.go
`*config.Config` of `FormatCode` function is unused.
> chore: remove dead code

- .golangci.next.reference.yml
- jsonschema/golangci.next.jsonschema.json
- pkg/config/linters_settings.go
- pkg/golinters/errcheck/errcheck.go
> errcheck: add verbose option

- .golangci.reference.yml
This is my first time creating a pull request.  
Please let me know if I made any mistakes in the process.
The current documentation lists the `defer` rule configuration for `revive` as follows:
```yaml
- name: defer
severity: warning
disabled: false
exclude: [""]
arguments:
- "call-chain"
- "loop"
- "method-call"
- "recover"
- "immediate-recover"
- "return"
```
However, this format is incorrect. According to the official `revive` rule descriptions ([source](https://github.com/mgechev/revive/blob/HEAD/RULES_DESCRIPTIONS.md#defer)), the `arguments` field should be passed as a **nested list**:
```yaml
- name: defer
severity: warning
disabled: false
exclude: [""]
arguments: [["call-chain", "loop", "method-call", "recover", "return"]]
```
In `revive`, the `Configure` method for the `defer` …
> docs: fix revive defer rule configuration

- cmd/golangci-lint/main.go
> dev: consistent version

- docs/src/docs/contributing/new-linters.mdx
- docs/src/docs/plugins/go-plugins.mdx
Related to https://github.com/golangci/golangci-lint/discussions/5807
> docs: note about plugin system

- .golangci.next.reference.yml
- pkg/goformat/runner.go
Related to https://gophers.slack.com/archives/CS0TBRKPC/p1748028690710039
Currently, when using `--stdin` and a generated file modified by hand (yes, I know, it should not happen, but :shrug:) the file is emptied.
> fix: write the input to stdout when using stdin and there are no changes

- pkg/commands/migrate.go
The check was done in the wrong place, so it was not triggered
when the config was already migrated.
Another error message was reported about jsonschema validation issues.
Because a v2 config file does not validate against the v1 schema.
That was misleading.
<details><summary>Before</summary>
```console
$ golangci-lint migrate 
jsonschema: "linters.exclusions" does not validate with "/properties/linters/properties/exclusions/additionalProperties": additional properties 'presets' not allowed
jsonschema: "linters" does not validate with "/properties/linters/additionalProperties": additional properties 'default', 'settings' not allowed
jsonschema: "" does not validate with "/additionalProperties": additional properties 'version', 'formatters' not allowed
Failed executing command with error: …
```
> fix: error message when trying to migrate a migrated config

- pkg/commands/formatters.go
The flags were the ones of the linters commands.
The help text was displaying the linters help text.
And the completions was allowing to use `--disable`, `--fast-only`, `--enable-only`, and others that
are not supported by the formatters commands.
<details><summary>Before</summary>
```console
$ golangci-lint formatters --help
List current formatters configuration
Usage:
golangci-lint formatters [flags]
Flags:
-c, --config PATH           Read config from file path PATH
--no-config             Don't read config file
--default string        Default set of linters to enable (default "standard")
-D, --disable strings       Disable specific linter
-E, --enable strings        Enable specific linter
--enable-only strings   Override linters configuration section to only run the specific linter(s) …
```
> fix: formatters CLI flags help message

- pkg/commands/internal/migrate/migrate_linter_names.go
- pkg/goformatters/internal/diff.go
- pkg/golinters/govet/govet_test.go
- pkg/golinters/tagliatelle/tagliatelle.go
- pkg/report/log.go
- pkg/result/processors/base_rule.go
- pkg/result/processors/nolint_filter.go
- test/testshared/integration/run.go
- test/testshared/runner.go
Run the command:
```
go run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@latest -fix -test ./...
```
and revert some unnecessary changes.
> dev: some simplifications

- pkg/golinters/staticcheck/staticcheck.go
- pkg/logutils/logutils.go
The PR adds a new option `staticcheck` for `GL_DEBUG` allowing to print staticcheck checks and configuration.
```shellsession
$ make build && GL_DEBUG=staticcheck ./golangci-lint linters -v
go build -o golangci-lint ./cmd/golangci-lint
INFO [config_reader] Config search paths: [./ /Users/alexandear/src/github.com/golangci/golangci-lint /Users/alexandear/src/github.com/golangci /Users/alexandear/src/github.com /Users/alexandear/src /Users/alexandear /Users /] 
INFO [config_reader] Used config file .golangci.yml 
INFO [config_reader] Module name "github.com/golangci/golangci-lint/v2" 
DEBU [staticcheck] All available checks (160): QF1001,QF1002,QF1003,QF1004,QF1005,QF1006,QF1007,QF1008,QF1009,QF1010,QF1011,QF1012,S1000,S1001,S1002,S1003,S1004,S1005,S1006,S1007,S1008,S1009,S1010,S1011,S1012,S …
```
> dev: display list of staticcheck checks in debug

- pkg/commands/run.go
`print-resources-usage` flag is a relic of the past and is mainly useless.
Closes #5859
> feat: deprecate print-resources-usage flag

- .golangci.next.reference.yml
> docs: add a note about `GL_DEBUG=staticcheck`

- pkg/goanalysis/pkgerrors/errors.go
- pkg/lint/runner.go
Fixes #5863
<details>
<summary>to reproduce</summary>
```yml
version: '2'
issues:
max-issues-per-linter: 0
max-same-issues: 0
uniq-by-line: false
```
```go
package main
import (
"context"
)
func main() {
context.Background(1)
}
```
```console
$ golangci-lint run
main.go:1: : # github.com/golangci/sandbox
./main.go:8:21: too many arguments in call to context.Background
have (number)
want () (typecheck)
package main
...
main.go:1: : # github.com/golangci/sandbox
./main.go:8:21: too many arguments in call to context.Background
have (number)
want () (typecheck)
package main
201 issues:
* typecheck: 201
```
</details>
> fix: deduplicate typecheck errors

- docs/src/docs/product/migration-guide.mdx
Update migration guide to reflect cmd flags `--print-issued-lines` and `--print-linter-name`.
> docs: update migration guide with --print-issued-lines

- pkg/goanalysis/runner.go
- pkg/goanalysis/runner_action.go
- pkg/goanalysis/runner_checker.go
- pkg/goanalysis/runner_loadingpackage.go
Stops the analysis after the first package analysis error.
- Improve the speed when there are errors (about three times faster based on my test cases)
- Improve error reports
- Revert #5884 (because there is no accumulation of errors with this PR)
<details><summary>before</summary>
```console
$ ./golangci-lint run -v
INFO golangci-lint has version (devel) built with go1.24.3 from (751b9ca1972cd9a2b6de4de20a74dd281f970f5a, modified: false, mod sum: "") on 2025-06-19T12:16:25Z 
INFO [config_reader] Config search paths: [./ /home/ldez/sources/experimental/alingse-kubernetes /home/ldez/sources/experimental /home/ldez/sources /home/ldez /home /] 
INFO [config_reader] Used config file .golangci.yaml 
INFO [config_reader] Module name "k8s.io/kubernetes" 
INFO maxprocs: Leaving GOMAXPROCS=16: CPU …
```
> fix: stop the analysis after the first package analysis error

- pkg/goformatters/gci/gci.go
<details><summary>This code will be formatted</summary>
```go
package main
import (
"fmt"
"os"
)
type Foo struct {
Value string
}
```
</details>
<details><summary>This code will NOT be formatted</summary>
```go
package main
type Foo struct {
Value string
}
```
</details>
The code is formatted only if the imports are updated by `gci`.
This is not consistent.
> fix: formats consistently the code with gci

- .golangci.yml
- pkg/commands/run.go
- pkg/golinters/wsl/wsl.go
- pkg/lint/linter/config.go
- pkg/lint/lintersdb/builder_linter.go
The goal is to display a suggested migration configuration when running golangci-lint.
~~The code related to the command `migrate` is ambiguous due to the difference between the default values of v4 and v5.~~
Edit: I removed the part related to the `migrate` command because I'm not fully happy with the approach.
> dev: add suggested migration for linter configuration

- assets/github-action-config-v1.json
- assets/github-action-config.json
- scripts/gen_github_action_config/main.go
The current releases size used inside the query creates a 504 (and I don't know why).
It was failing during the 3 latest releases (so I updated the files manually).
https://github.com/golangci/golangci-lint/actions/workflows/post-release.yml
Reducing this size fixes the 504 problem, and doesn't change the result as we iterate over the cursor.
> dev: fix GitHub Action assets generation

- docs/src/docs/welcome/faq.mdx
Adds the command line to check the Go version used to build golangci-lint.
> docs: add the command to check the Go version used to build

- docs/src/docs/contributing/new-linters.mdx
Fixes #5924
Uses the Wayback Machine for now.
In the future, I think I will write a new tutorial.
> docs: fix tutorial URL

- go.mod
- pkg/goanalysis/runner_action.go
- pkg/goanalysis/runner_loadingpackage.go
I tested the PR with a huge cycle of thousands of runs with typecheck error on 3 projects.
This neither changes the report from the previous PR nor the performance from the previous PR.
It closes the channel after the actions analysis instead of during the actions analysis.
Fixes #5923
> fix: panic: close of closed channel

- pkg/golinters/godox/godox.go
> godox: trim filepath from report messages

- docs/content/docs/formatters/_index.md
- docs/content/docs/linters/_index.md
- docs/layouts/_partials/clickable-badge.html
- docs/layouts/_shortcodes/filter-bar.html
Improve and simplify the filter bar.
The build uses `--minify` flag to minify the website, which removes whitespace between elements, and so the filter bar is compacted.
This flag cannot be used with the target `make serve` because this is very slow.
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
> docs: fix filter bar items

- docs/hugo.yaml
- docs/layouts/_partials/footer.html
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
> dev: better website footer

- docs/content/docs/configuration/_index.md
- docs/content/docs/contributing/_index.md
- docs/content/docs/contributing/architecture.md
- docs/content/docs/contributing/debug.md
- docs/content/docs/contributing/faq.md
- docs/content/docs/contributing/new-linters.md
- docs/content/docs/contributing/website.md
- docs/content/docs/contributing/workflow.md
- docs/content/docs/formatters/_index.md
- docs/content/docs/linters/_index.md
- docs/content/docs/linters/false-positives.md
- docs/content/docs/plugins/go-plugins.md
- docs/content/docs/plugins/module-plugins.md
- docs/content/docs/product/changelog.md
- docs/content/docs/product/migration-guide.md
- docs/content/docs/product/roadmap.md
- docs/content/docs/product/thanks.md
- docs/content/docs/welcome/faq.md
- docs/content/docs/welcome/install.md
- docs/content/docs/welcome/integrations.md
- docs/content/docs/welcome/quick-start.md
I discovered that we can create path [aliases](https://gohugo.io/content-management/urls/#aliases) to match the previous paths to the documentation.
<details>
<summary>mapping</summary>
| OLD                         | NEW                              |
|-----------------------------|----------------------------------|
| /welcome/install/           | /docs/welcome/install/           |
| /welcome/quick-start/       | /docs/welcome/quick-start/       |
| /welcome/integrations/      | /docs/welcome/integrations/      |
| /welcome/faq/               | /docs/welcome/faq/               |
| /usage/configuration/       | /docs/configuration/             |
| /usage/linters/             | /docs/linters/                   |
| /usage/false-positives/     | /docs/linters/false-positives/   |
| …
> dev: add website aliases

- docs/content/docs/product/migration-guide.md
- docs/content/docs/welcome/install.md
- docs/layouts/_shortcodes/details.html
- docs/layouts/_shortcodes/image-card.html
- Uses a table instead of a list inside the migration guide for presets
- Replace `<strong>` by a simple `<div>` for detail titles
- Better style images (remove border, hover, etc.)
> dev: minor doc style changes

- docs/assets/css/custom.css
- docs/content/docs/formatters/_index.md
- docs/content/docs/linters/_index.md
- docs/content/docs/plugins/_index.md
- docs/go.mod
- docs/go.sum
- docs/hugo.yaml
- docs/layouts/_partials/shortcodes/badge.html
- docs/layouts/_shortcodes/golangci/items/filter-badge.html
- docs/layouts/_shortcodes/golangci/items/settings.html
- https://github.com/imfing/hextra/compare/v0.10.2...v0.11.0
- https://github.com/imfing/hextra/releases/tag/v0.11.0
**This update is done by hand because dependabot is unable to update Hugo dependencies (they are not real modules.**
> dev: update Hextra to v0.11.0

- docs/content/docs/product/migration-guide.md
- Rename `VSCode` to `Visual Studio Code` for consistency with https://golangci-lint.run/docs/welcome/integrations/#visual-studio-code
- Add spaces to VS Code configuration.
> dev: style changes in migration guide

- pkg/goanalysis/pkgerrors/extract.go
- pkg/goanalysis/pkgerrors/extract_test.go
- pkg/goanalysis/runner_loadingpackage.go
This is not trivial to explain (even to reproduce the behavior), but in summary, golangci-lint should not return the error `fmt.Errorf("could not load export data: %w", err)` because it bypasses the `typecheck` report system.
When `typecheck` report system is bypassed, a log is printed instead of a report.
This is why there is:
```console
$ golangci-lint run 
WARN [runner] Can't run linter goanalysis_metalinter: buildir: failed to load package fake: could not load export data: no export data for "github.com/golangci/sandbox/fake" 
ERRO Running error: can't run linter goanalysis_metalinter
buildir: failed to load package fake: could not load export data: no export data for "github.com/golangci/sandbox/fake"
```
instead of
```console
$ ./golangci-lint run 
main.go:6:2: could not import …
```
> fix: no export data must always be handled as a typecheck error

- .golangci.reference.yml
- docs/data/linters_info.json
- docs/data/thanks.json
- jsonschema/golangci.jsonschema.json
- jsonschema/golangci.v2.4.jsonschema.json
- pkg/lint/lintersdb/builder_linter.go
- scripts/website/dump_info/thanks.go
> docs: update documentation assets

- pkg/commands/internal/builder.go
- pkg/commands/internal/dirhash.go
The `dirhash.HashDir` function should technically be used on a packaged module, which is different than a repo source code.
I adapted the code to basically follow the same rule as a packaged module.
Fixes #6099
> fix: ignore some files to hash the version for custom build

- go.mod
- go.sum
- pkg/golinters/nilerr/nilerr.go
Remove the fork
related to #6087
> build(deps): bump github.com/gostaticanalysis/nilerr from 0.1.1 to 0.1.2
